### ISSUE TITLE
Group By queries cause an EOFException

### ISSUE THREAD

**Issue by nocturnaltortoise** [crate/crate#7276] opened 2018-05-17 09:54 UTC
**CrateDB version**: 2.3.2

**Environment description**:
 - JVM version: 1.8.0_171
 - Kernel: Linux 4.4.38
 - Distribution: Ubuntu 16.04
 - Number of nodes: 3

**Problem description**:
We have a cluster with three nodes, one of which is the master node. At one point, the master node went offline, and so a different node was elected master. Some time after this, GROUP BY queries on a particular table started to fail, giving this error:
```
SQLActionException[RuntimeException: java.io.EOFException: read past EOF: MMapIndexInput(path="/mnt/data/crate/nodes/0/indices/8-h2FjCLS7C1lzXKVxLiug/0/index/_101ma.cfs") [slice=_101ma_Lucene54_0.dvd] [slice=var-binary]]
```
Restarting all the nodes did not fix it, but restarting in a particular order so that the old master node was elected as master seemed to.

**Steps to reproduce**:

1. Make a cluster with three nodes
2. Make a table with some data in it.
3. Take the master node offline.
4. Bring it back online once a different master has been elected.
5. Run a GROUP BY query, e.g. 
```sql
SELECT armada.wind_turbine_data.device_uuid AS armada_wind_turbine_data_device_uuid, count(armada.wind_turbine_data.timestamp) AS samples, max(armada.wind_turbine_data.timestamp) AS timestamp 
FROM armada.wind_turbine_data 
WHERE armada.wind_turbine_data.timestamp < 1526515200000 AND armada.wind_turbine_data.timestamp >= 1523923200000 GROUP BY armada.wind_turbine_data.device_uuid
```

Table Schema:
```sql
CREATE TABLE IF NOT EXISTS "armada"."wind_turbine_data" (
   "activity" FLOAT,
   "availability" FLOAT,
   "availability_true" FLOAT,
   "device_uuid" STRING,
   "direction_wind" FLOAT,
   "energy" FLOAT,
   "energy_cumulative" FLOAT,
   "interval_duration" INTEGER,
   "power_active" FLOAT,
   "power_theoretical" FLOAT,
   "rpm_generator" FLOAT,
   "rpm_rotor" FLOAT,
   "seconds_observed" INTEGER,
   "status" STRING,
   "timestamp" TIMESTAMP,
   "wind_speed" FLOAT,
   "wind_speed_max" FLOAT,
   PRIMARY KEY ("timestamp", "device_uuid")
)
CLUSTERED INTO 4 SHARDS
WITH (
   "allocation.max_retries" = 5,
   "blocks.metadata" = false,
   "blocks.read" = false,
   "blocks.read_only" = false,
   "blocks.write" = false,
   column_policy = 'dynamic',
   "mapping.total_fields.limit" = 1000,
   number_of_replicas = '0-1',
   "recovery.initial_shards" = 'quorum',
   refresh_interval = 1000,
   "routing.allocation.enable" = 'all',
   "routing.allocation.total_shards_per_node" = -1,
   "translog.durability" = 'REQUEST',
   "translog.flush_threshold_size" = 536870912,
   "translog.sync_interval" = 5000,
   "unassigned.node_left.delayed_timeout" = 60000,
   "warmer.enabled" = true,
   "write.wait_for_active_shards" = 'all'
)```

**Comment by mfussenegger** [comment] 2018-05-17 10:26
Thanks for reporting.
Do you have any logs from the master from the time frame when it went offline?

**Comment by nocturnaltortoise** [comment] 2018-05-17 11:49
I think this is the bit of the log just before the crash:
[crate-2018-05-11.log](https://github.com/crate/crate/files/2012992/crate-2018-05-11.log)

**Comment by matriv** [comment] 2018-05-18 12:55
@nocturnaltortoise It seems that there was some corrupted index due to the failure of the master node, and the error you encounter after that it's not specific to the Group By query.

- Do you see any `CorruptIndexException` in your logs when the master node failed?
- Was there any disk failure on the master node?

You could try to repair the index by using Lucene's tool [luke](http://www.getopt.org/luke/). You have to open the directory with the corrupt index with luke and then use `Tools->Check Index tool`.

**Comment by nocturnaltortoise** [comment] 2018-05-18 13:10
No, I can't find any CorruptIndexExceptions in the crate logs, on either the current master or the master when the error occurred. 
I'm not aware of any disk failures. 
I've found a command line tool called CLue https://github.com/javasoze/clue that might be easier to use on this server than Luke, so I'll have a look at the index with that and see if I can find anything.

**Comment by matriv** [comment] 2018-05-18 13:27
Ok, good! Please let us know how that goes.

**Comment by nocturnaltortoise** [comment] 2018-05-18 13:45
I used lucene's CheckIndex, i.e. 
```bash
sudo java -cp lucene-core-6.6.1.jar org.apache.lucene.index.CheckIndex /mnt/data/crate/nodes/0/indices/8-h2FjCLS7C1lzXKVxLiug/0/index
```
And I got this log, which seemed to suggest everything was ok, but _101ma isn't mentioned, which I guess is the relevant segment?
[lucene-integrity-check.log](https://github.com/crate/crate/files/2017111/lucene-integrity-check.log)

**Comment by matriv** [comment] 2018-05-18 14:16
But you have run it on the problematic "snapshot" of the directory?

Is it possible to send us logs from all nodes for a time window before and after the incident?

**Comment by nocturnaltortoise** [comment] 2018-05-21 09:38
I'm not sure what you mean, I tried pointing it at the _101ma.cfs file, which is the one mentioned in the error, but it didn't work unless I pointed it at the directory the file was in.
I've attached logs for the day of the incident on each of the three nodes, it has a bit of time after the incident and beforehand, most of the logs are full of an irrelevant message about content-type detection.
[crate-log-1.log](https://github.com/crate/crate/files/2022039/crate-log-1.log)
[crate-log-2.log](https://github.com/crate/crate/files/2022040/crate-log-2.log)
[crate-log-3.log](https://github.com/crate/crate/files/2022041/crate-log-3.log)

**Comment by matriv** [comment] 2018-05-28 10:18
Tried to reproduce the scenario by killing the master but couldn't get to the state of corrupt indexes.
It seems that something weird happened in your cluster (possibly a hw failure? - can you check your /var/log/messages and kernel messages?).

What I meant is that you stated that your cluster is running correctly if the old master resumes again as master, is that correct? No corruption anymore?

Since Luke finds no error in the index directory, do you still experience this exception when running the group by queries?

**Comment by nocturnaltortoise** [comment] 2018-05-29 10:49
Yes, we've had no problems with the queries or the corruption being mentioned since the master was switched back to the old master. I'm wondering whether the corruption was down to the master node crashing due to being out of heap memory? As that was what caused the original master node to go offline in the first place.

**Comment by matriv** [comment] 2018-05-29 12:26
This shouldn't happen, we didn't have a case where OOM caused any index corruption.
I'm closing this for now. Feel free to reopen if it occurs again (hopefully not) and try to store any log information (crate + OS logs) at the time period of the incident.

**Closed by matriv** 2018-05-29 12:26 UTC
