### ISSUE TITLE
Querying using an unknown OBJECT key fails when using table aliases, even when disabling "error_on_unknown_object_key"

### ISSUE THREAD

**Issue by amotl** [crate/crate#14365] opened 2023-07-05 21:11 UTC
### CrateDB version

5.3.3

### CrateDB setup information

Standard Docker invocation.
```shell
docker pull crate:5.3
docker run --rm -it --publish=4200:4200 --publish=5432:5432 \
    --env=CRATE_HEAP_SIZE=4g crate:5.3 \
    -Cdiscovery.type=single-node
```

### Problem description

Specifically when using table aliases, the mechanism to resolve a "query by unknown key within an OBJECT column" does not work, and the execution croaks.

It has been discovered while working on the [cratedb-retention](https://github.com/crate-workbench/cratedb-retention) program, where both table aliases are used, and where an OBJECT column gets used for storing and querying for tags, similar to the reproducible example outlined below.

### Steps to Reproduce

```sql
SET error_on_unknown_object_key=false;

DROP TABLE IF EXISTS testdrive.bar;

CREATE TABLE testdrive.bar (
    "foo_id" INTEGER,
    "tags" OBJECT(DYNAMIC)
);
INSERT INTO testdrive.bar VALUES (1, '{"foo": "abc"}'), (2, '{"somethingelse": "abc"}');
REFRESH TABLE testdrive.bar;

WITH foo AS (SELECT 1 AS id)
SELECT *
FROM
  foo
  JOIN
  testdrive.bar AS T
ON
  foo.id = T.foo_id
WHERE
  T.tags['unknown'] IS NOT NULL
;
```

### Actual Result

When not using `SET error_on_unknown_object_key=false;`:
```
IndexOutOfBoundsException[Index: 1 Size: 1]
```

When using `SET error_on_unknown_object_key=false;`:
```
SQLParseException[Couldn't create execution plan from logical plan because of: Couldn't find tags['unknown'] in SourceSymbols{inputs={tags=INPUT(2), id=INPUT(0), foo_id=INPUT(1)}, nonDeterministicFunctions={}}:
Filter[(NOT (tags['unknown'] IS NULL))]
  └ HashJoin[(id = foo_id)]
    ├ Rename[id] AS foo
    │  └ Eval[1 AS id]
    │    └ TableFunction[empty_row | [] | true]
    └ Rename[foo_id, tags] AS t
      └ Collect[testdrive.bar | [foo_id, tags] | true]]
```

When amending the SQL statement's WHERE constraint to `T.tags['foo'] IS NOT NULL`, i.e. when using a known OBJECT key, the query works, and yields a correct single-record result.

### Expected Result

The query should work, and yield zero results.

**Comment by amotl** [comment] 2023-07-05 21:12
The query actually does work, when **not** using table aliases, like:
```sql
WITH foo AS (SELECT 1 AS id)
SELECT *
FROM
  foo
  JOIN
  testdrive.bar
ON
  foo.id = bar.foo_id
WHERE
  bar.tags['unknown'] IS NOT NULL
;
```
In this case, the query yields zero results, as expected.

Also, when not using `SET error_on_unknown_object_key=false;` on this query, it yields an error as expected.
```
ColumnUnknownException[Column tags['unknown'] unknown]
```

**Comment by jeeminso** [comment] 2023-07-08 00:06
Thanks for reporting @amotl, I will handle the two exceptions separately, since `IndexOutOfBoundsException` case is tied to existing behaviour (which could lead to a breaking change).

**Comment by jeeminso** [comment] 2023-07-26 18:05
This bug should be resolved by the two linked PRs, confirmed locally with the latest master that it either throws `ColumnUnknownException` or returns nothing, closing.

**Closed by jeeminso** 2023-07-26 18:05 UTC
Labels: bug
