### ISSUE TITLE
Bulk update query return wrong json

### ISSUE THREAD

**Issue by gemozlobin2** [crate/crate#6359] opened 2017-10-05 13:00 UTC
**CrateDB version**:
2.1.5

**JVM version**:
OpenJDK Runtime Environment (build 1.8.0_131-8u131-b11-1~bpo8+1-b11)
OpenJDK 64-Bit Server VM (build 25.131-b11, mixed mode)

**OS version / environment description**:
Debian 8
cluster with 24 nodes is split into 3 zones

**Problem description**:
I do bulk update query and receive json with all rowcount = -2, but fields in table was updated. I think it's bug. If i remove part of "where" condition i'll get right json.

**Steps to reproduce**:

```sql
CREATE TABLE IF NOT EXISTS "test_update" (
   "f1" LONG,
   "f2" LONG,
   "f3" LONG,
   PRIMARY KEY ("f1")
)
CLUSTERED BY ("f1") INTO 48 SHARDS
WITH (
   "blocks.metadata" = false,
   "blocks.read" = false,
   "blocks.read_only" = false,
   "blocks.write" = false,
   column_policy = 'strict',
   "mapping.total_fields.limit" = 1000,
   number_of_replicas = '0-all',
   "recovery.initial_shards" = 'quorum',
   refresh_interval = 1000,
   "routing.allocation.enable" = 'all',
   "routing.allocation.total_shards_per_node" = -1,
   "translog.durability" = 'REQUEST',
   "translog.flush_threshold_size" = 536870912,
   "translog.sync_interval" = 5000,
   "unassigned.node_left.delayed_timeout" = 60000,
   "warmer.enabled" = true,
   "write.wait_for_active_shards" = '0'
);

INSERT INTO "test_update"
VALUES(1,1,1), (2,1,1);

SELECT * FROM  test_update;
f1	f2	f3
1	1	1	
2	1	1

$ curl -sS -H 'Content-Type: application/json' -X POST '127.0.0.1:4200/_sql?pretty' -d '{"stmt": "UPDATE test_update SET f3 = 7 WHERE f1 = ? AND f2 > 0", "bulk_args": [[1],[2]]}'
{
  "cols" : [ ],
  "duration" : 6873.3564,
  "results" : [
    {
      "rowcount" : -2
    },
    {
      "rowcount" : -2
    }
  ]
}

SELECT * FROM  test_update;
f1	f2	f3
1	1	7	
2	1	7

$ curl -sS -H 'Content-Type: application/json' -X POST '127.0.0.1:4200/_sql?pretty' -d '{"stmt": "UPDATE test_update SET f3 = 8 WHERE f1 = ?", "bulk_args": [[1],[2]]}'
{
  "cols" : [ ],
  "duration" : 4895.2246,
  "results" : [
    {
      "rowcount" : 1
    },
    {
      "rowcount" : 1
    }
  ]
}

SELECT * FROM  test_update;
f1	f2	f3
1	1	8	
2	1	8
```

**Comment by mikethebeer** [comment] 2017-10-06 13:32
@gemozlobin2 is it possible that you send us the log-output that happend during the update?

Another thing that you could probably look at is the `"write.wait_for_active_shards" = '0'` index setting. Is there a reason why you set this to zero? I would rather increase it to `1` (primary shards only) at least or go with the standard that is set to `all` (at least if insert speed has no prio). https://crate.io/docs/crate/reference/en/latest/sql/reference/create_table.html#write-wait-for-active-shards

**Comment by joemoe** [comment] 2017-10-11 11:59
@gemozlobin2 can you provide answers to @mikethebeer s questions?
otherwise I would close that issue as we can't reproduce it.

**Comment by gemozlobin2** [comment] 2017-10-11 12:09
>@gemozlobin2 is it possible that you paste us the log-output that happend during the update?

No, it's what crate answer to bulk request.
>Another thing that you could probably look at is the "write.wait_for_active_shards" = '0' index setting. 

I change it from all to 0 and it repeated.

I was testing it on one node cluster and it's not reproduce, but on 24 nodes cluster it's repeated (

**Comment by jodok** [comment] 2017-10-16 08:13
@gemozlobin2 your feedback would be appreciated. without further input we can't continue to work on that issue. thx!

**Comment by gemozlobin2** [comment] 2017-10-17 13:45
@mikethebeer 
For query
`$ curl -sS -H 'Content-Type: application/json' -X POST '127.0.0.1:4200/_sql?pretty' -d '{"stmt": "UPDATE test_update SET f3 = 7 WHERE f1 = ? AND f2 > 0", "bulk_args": [[1],[2]]}'`
```
[2017-10-17T16:27:26,258][DEBUG][i.c.a.s.SQLOperations    ] method=parse stmtName= query=UPDATE test_update SET f3 = 7 WHERE f1 = ? AND f2 > 0 paramTypes=[]
[2017-10-17T16:27:26,273][DEBUG][i.c.a.s.SQLOperations    ] method=bind portalName= statementName= params=[1]
[2017-10-17T16:27:27,137][DEBUG][i.c.a.s.SQLOperations    ] method=execute portalName= maxRows=0
[2017-10-17T16:27:27,137][DEBUG][i.c.a.s.SQLOperations    ] method=bind portalName= statementName= params=[2]
[2017-10-17T16:27:27,154][DEBUG][i.c.a.s.SQLOperations    ] method=execute portalName= maxRows=0
[2017-10-17T16:27:27,154][DEBUG][i.c.a.s.SQLOperations    ] method=describe type=P portalOrStatement=
[2017-10-17T16:27:27,156][DEBUG][i.c.a.s.SQLOperations    ] method=sync portal=name: , type: BulkPortal
[2017-10-17T16:27:27,431][DEBUG][i.c.e.t.TransportExecutor] Created NodeOperationTrees from Plan: [NodeOperationTree{nodeOperations=[NodeOp{ phase{id=0/collect, nodes=[cmsnheI1Qyilzlth3icEBw], dist=BROADCAST}, downstreamNodes=[_response], downstreamPhase=1, downstreamInputId=0}], leaf=MergePhase{executionPhaseId=1, name=mergeOnHandler, projections=[io.crate.planner.projection.MergeCountProjection@71ee0bff], outputTypes=[long], jobId=2d7507b2-dc33-4057-a721-86827864855f, numUpstreams=1, nodeOperations=[9Wr9ESMFRCu3v82zhXtA-w], inputTypes=[long], orderBy=null}}, NodeOperationTree{nodeOperations=[NodeOp{ phase{id=2/collect, nodes=[lBGab6jcTDuOe6FJjKS9AQ], dist=BROADCAST}, downstreamNodes=[_response], downstreamPhase=3, downstreamInputId=0}], leaf=MergePhase{executionPhaseId=3, name=mergeOnHandler, projections=[io.crate.planner.projection.MergeCountProjection@71ee0bff], outputTypes=[long], jobId=2d7507b2-dc33-4057-a721-86827864855f, numUpstreams=1, nodeOperations=[9Wr9ESMFRCu3v82zhXtA-w], inputTypes=[long], orderBy=null}}]
```

Curl query return -2 for all rows but data has been updated

May be need another logs?

**Comment by mikethebeer** [comment] 2017-10-18 08:33
@gemozlobin2 thanks for printing the logs. I just noticed that Error-Messages on bulk requests/updates are not passed to the client on purpose to save performance. This is not the case if on single requests.
Could you try out the same statements on single `args` instead of passing `bulk_args`. Probably we see an error-message there that caused the `-2` row-count.

**Comment by gemozlobin2** [comment] 2017-10-18 09:05
If single query returned error, it would be simple and I wouldn't report a bug.
`curl -sS -H 'Content-Type: application/json' -X POST '127.0.0.1:4200/_sql?pretty' -d '{"stmt": "UPDATE test_update SET f3 = 18 WHERE f1 = ? AND f2 > 0", "args": [1]}'`
```
[2017-10-18T11:45:04,377][DEBUG][i.c.a.s.SQLOperations    ] method=parse stmtName= query=UPDATE test_update SET f3 = 18 WHERE f1 = ? AND f2 > 0 paramTypes=[]
[2017-10-18T11:45:04,378][DEBUG][i.c.a.s.SQLOperations    ] method=bind portalName= statementName= params=[1]
[2017-10-18T11:45:04,378][DEBUG][i.c.a.s.SQLOperations    ] method=describe type=P portalOrStatement=
[2017-10-18T11:45:04,379][DEBUG][i.c.a.s.SQLOperations    ] method=execute portalName= maxRows=0
[2017-10-18T11:45:04,379][DEBUG][i.c.a.s.SQLOperations    ] method=sync portal=name: , type: SimplePortal
[2017-10-18T11:45:04,380][DEBUG][i.c.e.t.TransportExecutor] Created NodeOperationTrees from Plan: [NodeOperationTree{nodeOperations=[NodeOp{ phase{id=0/collect, nodes=[cmsnheI1Qyilzlth3icEBw],dist=BROADCAST}, downstreamNodes=[_response], downstreamPhase=1, downstreamInputId=0}], leaf=MergePhase{executionPhaseId=1, name=mergeOnHandler,projections=[io.crate.planner.projection.MergeCountProjection@71ee0bff], outputTypes=[long], jobId=5c249b05-8fb4-4b9c-8477-8b4b8aefbf8b, numUpstreams=1, nodeOperations=[9Wr9ESMFRCu3v82zhXtA-w], inputTypes=[long], orderBy=null}}]
```
```
{
  "cols" : [ ],
  "rows" : [
    [ ]
  ],
  "rowcount" : 1,
  "duration" : 8326.78
}
```

May be it depends on the settings of the cluster? Are you need any additional info?

**Comment by mikethebeer** [comment] 2017-10-18 13:29
@gemozlobin2 I forgot to mention, pls look on Errors on all Crate nodes. This is only the log of the handler node. The error could happen on another node.

Just to narrow down the error possiblities: Could you make a bulk request with a bulk-size > 2 ? It could be that a bug in the `rowcount` summation (`-1 + -1 = -2`) occurs.

**Comment by mikethebeer** [comment] 2017-10-23 07:15
@gemozlobin2 have you been able to check the logs on the other nodes?

**Comment by joemoe** [comment] 2017-10-31 09:23
@gemozlobin2 i'll close this issue, when this is still an issue to you, feel free to reopen it any time.

**Closed by joemoe** 2017-10-31 09:23 UTC
