### ISSUE TITLE
Path Hierarchy Tokenizer / Query

### ISSUE THREAD

**Issue by burnes** [crate/crate#4834] opened 2017-02-02 16:55 UTC
**CrateDB version**: 1.0.2

**JVM version**: 8

**OS version / environment description**: Lovely Crate Cluster

**Problem description**:

The match query `/200000/1` returns multiple results. In my opinion exactly one result should be returned. Is there a bug or am I doing something wrong (The documentation is not very verbose about that).

**Steps to reproduce**:

```sql
CREATE ANALYZER path_hierarchy_analyzer (
	TOKENIZER path_hierarchy
);

CREATE TABLE test (
	hash_path STRING GENERATED ALWAYS AS date_format('/%f/%S/%i/%H/%d/%m/%Y', "ts") INDEX USING FULLTEXT WITH (
		analyzer = 'path_hierarchy_analyzer'
	),
	ts TIMESTAMP
);

INSERT INTO test (ts) VALUES ('2016-01-01T12:00:00.000');
INSERT INTO test (ts) VALUES ('2016-01-01T12:00:00.200');
INSERT INTO test (ts) VALUES ('2016-01-01T12:00:01.000');
INSERT INTO test (ts) VALUES ('2016-01-01T12:00:01.200');

SELECT hash_path, date_format(ts) FROM test WHERE match(hash_path, '/200000') LIMIT 100;
SELECT hash_path, date_format(ts) FROM test WHERE match(hash_path, '/200000/01') LIMIT 100;
```

**Comment by mikethebeer** [comment] 2017-02-04 00:30
@burnes thanks for reporting. We take a :eyes: at

**Comment by chaudum** [comment] 2017-02-07 12:25
the problem is that you perform a weighted query, you can see that the 2nd - unexpected - match also matches but with a very low score.

```
cr>  SELECT _score, hash_path, date_format(ts) FROM test WHERE match(hash_path, '/200000/01');
+------------+-----------------------------+-----------------------------+
|     _score | hash_path                   | date_format(ts)             |
+------------+-----------------------------+-----------------------------+
| 0.09001608 | /200000/00/00/12/01/01/2016 | 2016-01-01T12:00:00.200000Z |
| 0.4339554  | /200000/01/00/12/01/01/2016 | 2016-01-01T12:00:01.200000Z |
+------------+-----------------------------+-----------------------------+
 2 rows in set (0.004 sec)
```

what you probably want is an exact query on the produced terms by the path_hierarchy tokenizer.
you can do a simple term query with matches exact terms.

```
cr> SELECT hash_path, date_format(ts) FROM test WHERE hash_path = '/200000/01'
+-----------------------------+-----------------------------+
| hash_path                   | date_format(ts)             |
+-----------------------------+-----------------------------+
| /200000/01/00/12/01/01/2016 | 2016-01-01T12:00:01.200000Z |
+-----------------------------+-----------------------------+
SELECT 1 row in set (0.003 sec)
```

**Comment by joemoe** [comment] 2017-02-23 16:28
@burnes did @chaudum answer your question? can i close the issue?

**Comment by chaudum** [comment] 2017-02-23 16:42
yes, exact query on produced term solved the problem.

**Closed by chaudum** 2017-02-23 16:42 UTC
Labels: question
