### ISSUE TITLE
Select with Limit clause is slower than without

### ISSUE THREAD

**Issue by mkleen** [crate/crate#11289] opened 2021-04-20 08:25 UTC
**CrateDB version**:
4.5

**Environment description**:
Linux Debian Stretch

**Problem description**:

A `select * from users` query is faster than `select * from users limit 100000`  on a table containing 100 001 rows.

**Steps to reproduce**:

Table schema user:

| Name  | Type          | 
|----------|:---------
| id |  lInteger |
| firstname |  text   | 
| lastname | text | 
| year_of_birth | Integer | 
| active | text | 

Insert 100001 rows of user into doc.user.
Measure time on queries `select * from users`  and `select * from users limit 100000`.

Based on this [discussion](https://community.crate.io/t/sql-without-limit-unoptimized-doc-schema-performance-different-compared-to-other-schemas/601/9 ).

**Comment by mfussenegger** [comment] 2021-04-20 08:53
Duplicate of https://github.com/crate/crate/issues/11285

**Closed by mfussenegger** 2021-04-20 08:53 UTC
Labels: triage
