### ISSUE TITLE
Possible to collect Cluster Load metrics when running on Windows?

### ISSUE THREAD

**Issue by dsmithson** [crate/crate#6486] opened 2017-11-07 00:25 UTC
**CrateDB version**: 
     2.1.8
**JVM version**:
     Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
     Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)

**OS version / environment description**:
     Windows Server 2016, viewing Crate web page using Chrome

**Problem description**:

When running CrateDB on Windows Server (2016), I notice that the cluster load graphs don't show any data (see screenshot).  I don't think Windows has the same kind of counters as Linux, but would it be possible to show some kind of metric information when running on Windows?

![crateclusterloadonwindows](https://user-images.githubusercontent.com/334865/32470773-28f8ee0e-c317-11e7-81aa-092443e51f95.jpg)

**Comment by joemoe** [comment] 2017-11-07 07:47
hi @dsmithson, the problem is that at the moment we are using sigar under the hood, but we are currently working on replacing that. i can tell you more in a couple of weeks. at the moment there is no way to get that running.

**Comment by dsmithson** [comment] 2017-11-07 17:42
No worries, thanks for the info @joemoe

**Comment by mfussenegger** [comment] 2020-07-07 09:13
We currently have no plans to extend this for windows, so I'm closing this for now.

Contributions would still be welcome

**Closed by mfussenegger** 2020-07-07 09:13 UTC
Labels: feature: diagnostics, platform: windows
