### ISSUE TITLE
Alter table table_name modify/drop column ?

### ISSUE THREAD

**Issue by wking1986** [crate/crate#4398] opened 2016-11-08 06:25 UTC
Hi Guys：
   'alter table tweets add column column_name type' is well，but how do modify/drop column?

**Comment by celaus** [comment] 2016-11-08 08:58
Hi @wking1986 - currently this is not available 😕 but if you are up for a challenge we are looking for contributors 😄

**Comment by wking1986** [comment] 2016-11-08 09:28
O(∩_∩)O~，OK，I am honored to be one of you!

**Comment by wking1986** [comment] 2016-11-08 09:29
@celaus  How automatically clean up expiration doc tables？

**Comment by celaus** [comment] 2016-11-08 09:34
you could use a cron job that issues a curl request periodically: https://crate.io/docs/reference/en/latest/protocols/http.html

**Comment by wking1986** [comment] 2016-11-08 10:28
Whether to consider this function into crate-admin ui?

**Comment by celaus** [comment] 2016-11-08 10:39
well, the admin UI is a client side application and therefore won't be able to schedule things periodically, and it's too specialized a feature to go into the core ;)

**Comment by celaus** [comment] 2016-11-09 14:39
@wking1986 I am closing this issue now, it would be great if you could ask further questions on https://stackoverflow.com/tags/crate so other users with similar problems are able to find answers as well! We will still answer there :)

**Closed by celaus** 2016-11-09 14:39 UTC
Labels: question

**Comment by SneakyMax** [comment] 2017-11-19 19:51
Since this issue was closed, does that mean this is "no plans to implement"?

**Comment by taliaga** [comment] 2018-05-04 15:48
It's just a duplicate of #4457
