### ISSUE TITLE
Bulk updates and NPE

### ISSUE THREAD

**Issue by bputt** [crate/crate#4484] opened 2016-11-24 02:36 UTC
**CrateDB version**: 0.56.3

**JVM version**: 1.8.0_92-b14

**OS version / environment description**: Centos 7

**Problem description**:
When sending bulk updates via the Crate HTTP API, the API would hang and not return any response. The following message shows up in the logs:

```
[WARN ][action.bulk ] ShardUpsert Item [someNumber] failed: Failure{id=UUID, message=NullPointerException[null], versionConflict=false}
```

**Steps to reproduce**:
Updating 5 STRING columns and sending 1k bulk_args

```
POST /_sql
{
    "stmt": "UPDATE table SET col1 = ?, col2 = ?, col3 = ?, col4 = ?.... WHERE id = ?",
    "bulk_args": [ [someVal, anotherVal, .....], [...], [...] ]
}
```

Bulk Settings:

```
threadpool.bulk.type: fixed
threadpool.bulk.queue_size: 500
threadpool.bulk.processors: 8
```

**Comment by celaus** [comment] 2016-11-24 09:24
Hi, thanks for reporting, can you please also attach a table schema so we can reproduce it properly :) 
Did you also try with 0.56.4? 

Cheers, Claus

**Comment by matriv** [comment] 2016-11-24 16:08
@bputt Some more info regarding the data of the table and the data of the bulk_args will also be useful.

**Comment by bputt** [comment] 2016-11-28 03:31
The cluster size is slightly smaller than your test cluster and I'll look into providing the schema in the next week or so(the number of columns is < 30 and they consist of string, long, integer, array. No field contains more than 255 characters).

After reducing the bulk insert from 1k to 250, I had no issues.

I have not tested it with 0.56.4 yet.

**Comment by matriv** [comment] 2017-01-05 18:22
@bputt I'm closing the issue now. Feel free to reopen if you experience it again.

**Comment by bputt** [comment] 2017-02-09 20:51
@matriv While I'm not getting an NPE any more, however, the HTTP API still hangs.

This message appears in the logs ```Received response for a request that has timed out```

Crate version is 1.0.2

**Comment by matriv** [comment] 2017-02-10 08:29
Hello @bputt,

The error you get seems to be a client timeout, have you checked if your update is actually executed after that and your data is updated? You could also use stats.enabled = true see reference [here](https://crate.io/docs/reference/configuration.html#collecting-stats) and check how much time was spent for the update in sys.jobs_log table.

It would also be very helpful to provide the schema for your table.

**Comment by bputt** [comment] 2017-02-10 20:08
6 Node Cluster (8cpu x 64 gb / node)

Table schema

```
CREATE TABLE table (
    a STRING PRIMARY KEY,
    b LONG PRIMARY KEY,
    c INTEGER,
    d INTEGER,
    e INTEGER,
    f STRING,
    g INTEGER,
    h INTEGER,
    i LONG,
    j INTEGER,
    k INTEGER,
    l LONG,
    m INTEGER,
    n INTEGER,
    o STRING,
    p STRING,
    q STRING,
    r STRING,
    s STRING,
    t STRING,
    u array(object as (
        a STRING,
        b STRING INDEX OFF
    )),
    v array(object as (
        a STRING,
        b STRING,
        c LONG,
        d LONG,
        e INTEGER,
        f INTEGER,
        g INTEGER
    ))
) CLUSTERED INTO 5 SHARDS
WITH (number_of_replicas = 3)
```

**Comment by mfussenegger** [comment] 2017-02-13 15:50
We've a fix for this (https://github.com/crate/crate/pull/4895) which will be in the next release (1.0.4).

Note that this fixes the *getting stuck*, the statement itself will still fail if the bulk_size is bigger than what can be handeld (thread_pool size/queue size). I've also added a card to our backlog to improve this in the future so that we can handle a bigger bulk-size without having to increase the threadpool queue size.

We're still looking into https://github.com/crate/crate/issues/4885 which is in the same area.

**Closed by mfussenegger** 2017-02-13 15:50 UTC
Labels: feedback_needed
