### ISSUE TITLE
Table isn't suddenly accepting new data because of bug

### ISSUE THREAD

**Issue by rjbaat** [crate/crate#12092] opened 2022-02-01 13:40 UTC
### CrateDB version

4.6.7

### CrateDB setup information

I have a 3 node cluster with 3 gb memory and 2gb heap size setup.

### Steps to Reproduce

I can't reproduce it, I did made a new table with the query `SHOW CREATE TABLE` and made a new table and directly new data is showing up. So it looks like the old table got corrupt or something. 

### Expected Result

When I add new data to a staging cluster it is working, but on the identical production cluster it is not. 
I has been accepting data until 23:59 last night. After that it is giving me the following error:

```
[2022-02-01 06:36:51] [CRATE] Error inserting for vehicle v77!
[2022-02-01 06:36:51] { message: 'MapperParsingException[Failed to parse mapping: Mapping definition for [date_field] has unsupported parameters:  [fields : {keyword={ignore_above=256, type=keyword}}]]',
  code: 4000 }```
```

### Actual Result

Even when not adding the specific field in the insert the table won't accept the new data.

**Comment by BaurzhanSakhariev** [comment] 2022-02-01 14:08
Hi @rjbaat, thanks for the report.

Could you please provide details, such as full CREATE statement? 

>I has been accepting data until 23:59 last night. After that it is giving me the following error

is it only about production cluster? I.e. does staging cluster accept data after 23.59 without any errors?

**Comment by proddata** [comment] 2022-02-01 14:45
> I have a 3 node cluster with 2 gb memory and 2gb heap size setup.

Generally speaking the heap should be between 25-50% of node memory

Can you provide an example query that fails?

```sql
SELECT * FROM sys.jobs_log
WHERE error IS NOT null AND classification['type'] = 'INSERT' limit 100;
```

--- 

Generally speaking the bug report feature is only intended for reproducible bug reports.
For questions about the usage of CrateDB I would like to refer you to https://community.crate.io/

**Comment by rjbaat** [comment] 2022-02-01 14:53
@BaurzhanSakhariev it was indeed only production. Not on the staging cluster. 

@proddata sorry I was mistake its a 3 node cluster with each 3 gb data and heap set on 2gb. maybe that's still a bit to less, so I will increase this when I am able to find a window to restart the cluster. 

The query you mentioned gives me no result.

**Comment by BaurzhanSakhariev** [comment] 2022-02-01 14:59
Let me clarify the scenario, you created table, say `t1`,  then run `SHOW CREATE TABLE t1` and used output to create another table `t2` and inserts into `t2` doesn't work after 23:59? Please share output of the `SHOW CREATE TABLE`

**Comment by rjbaat** [comment] 2022-02-01 15:06
Sorry I will explain a bit better. I had table `t1` and it was accepting data until 23:59. After I could add any new data because of the error: 
```
[2022-02-01 06:36:51] [CRATE] Error inserting for vehicle v77!
[2022-02-01 06:36:51] { message: 'MapperParsingException[Failed to parse mapping: Mapping definition for [date_field] has unsupported parameters:  [fields : {keyword={ignore_above=256, type=keyword}}]]',
  code: 4000 }
```

Then I made `t2` with indeed the `SHOW CREATE TABLE` and tried to insert in that table the same way. That was working directly. So a clean table is working and accepting data.

**Comment by BaurzhanSakhariev** [comment] 2022-02-01 15:17
OK, thanks for the clarification. Please share `CREATE TABLE` statement for `t1` (if you used `crash` you have it in the history) and output of the `SHOW CREATE TABLE t1 `.

**Comment by rjbaat** [comment] 2022-02-01 15:36
@BaurzhanSakhariev Unfortunately I can't send the full create table statement at this point, but I do have an interesting part that I noticed just now. 

In `t1` an object field in the table looks like this:

```
"raw_meta_data" OBJECT(DYNAMIC) AS (
    "date_field" TEXT INDEX USING FULLTEXT,
    ...
```

But in `t2` this looks like this:

```
"raw_meta_data" OBJECT(DYNAMIC) AS (
    "date_field" TEXT INDEX USING FULLTEXT WITH (
       analyzer = 'standard'
    ),
...
```

I think that field is miss configured as `TEXT` and gets a unix timestamp inserted. Not sure why the new table has the extra param `analyzer = 'standard'` added. Maybe that's done on create because of a new crate version?

**Comment by rjbaat** [comment] 2022-02-03 10:01
Maybe the table was indeed upgraded, but when I run your query I get: 

```
version['created'] | version['upgraded']
-- | --
vecore_trip_data_new | 4.6.7 | NULL

```
Anyway the table responded differently on a certain insert where the mentioned field was inserted in the new version 4.6.7 of crate. On the new table `t2` with the analyser spec it was going good. Either way the table schema needed a change on our end, because the field was a timestamp and not a text field. So we changed the object from DYNAMIC to STRICT and set the field to a TIMESTAMP field and it looks good now. I think the object schema got auto extended where we didn't want that to happen anyway. 

Thnx for the quick responses!

**Comment by proddata** [comment] 2022-02-03 10:07
It's not totally clear how this could happen (if not done manually), as an `OBJECT(DYNAMIC)` should never map to a `FULLTEXT` indexed field, but rather map all text input as `TEXT` with a plain index.

Be aware that you can also predefine mappings for `OBJECT(DYNAMIC)` on table creation and add mappings by using `ALTER TABLE ADD COLUMN`

```sql
"raw_meta_data" OBJECT(DYNAMIC) AS (
    "date_field" TIMESTAMP,
    ...)
```

---

I will close this for now, as there is not enough information to reproduce this and classify it as bug.

**Closed by proddata** 2022-02-03 10:07 UTC
Labels: needs more info
