### ISSUE TITLE
Load Values in Crate-Admin 

### ISSUE THREAD

**Issue by githubmui** [crate/crate#4494] opened 2016-11-24 22:47 UTC
Hi,
in Crate-Admin value "Load1", "Load5" and "Load15" stay on -1 on Windows machines. 
(Crate 0.48.0)

**Comment by mikethebeer** [comment] 2016-11-29 09:25
@githubmui thanks for reporting. We are looking into this. The problem is that the Sigar library for Windows is not exposing "load" data 😢 However, we have added this to our product backlog.

**Comment by mfussenegger** [comment] 2018-02-07 20:40
Closing this as a duplicate of https://github.com/crate/crate/issues/6486

**Closed by mfussenegger** 2018-02-07 20:40 UTC
Labels: enhancement
