### ISSUE TITLE
array funtion unsupport count length

### ISSUE THREAD

**Issue by foreachsky** [crate/crate#4411] opened 2016-11-10 08:52 UTC
hi, i check all the Array Functions
i can find the function for count array length

is that unsupport?

**Comment by celaus** [comment] 2016-11-10 08:53
Hi, yes we currently don't have a scalar function for array length ... but we welcome contributions 😃

**Comment by diyism** [comment] 2017-08-25 09:18
Duplicate of #882 since Jun 16, 2014,  Sql: Allow array counting https://github.com/crate/crate/issues/882

**Comment by mfussenegger** [comment] 2018-02-07 20:50
Closing as duplicate of https://github.com/crate/crate/issues/882

**Closed by mfussenegger** 2018-02-07 20:50 UTC
Labels: enhancement, question
