### ISSUE TITLE
CDN timeouts with downloading CrateDB 

### ISSUE THREAD

**Issue by karynzv** [crate/crate#15369] opened 2024-01-16 19:03 UTC
## Problem
When trying to download CrateDB, sometimes the process times out and on other occassions, it successfully completes. The timeouts are getting more frequent recently.

Users are reporting:
> The issue manifests itself at random times but lately it started occurring more often, on Friday the 12th of January 2024 we had issues where we were unable to re-deploy crate on some of our internal environments due to the outages.

### Download Script
```bash
curl -sS https://cdn.crate.io/downloads/deb/DEB-GPG-KEY-crate | sudo apt-key add -
while [[ $(fuser /var/lib/dpkg/lock /var/lib/apt/lists/lock) ]]; do sleep 1; done
sudo add-apt-repository "deb [arch=amd64] https://cdn.crate.io/downloads/debian/stable/ default main"
apt-get -o DPkg::lock::Timeout=120 update -y
apt-get o Dpkg::Options::="force-confdef" -o Dpkg::Options::="-force-confold" install -y crate
```
### Result
```
Err:1 https://cdn.crate.io/downloads/debian/stable default/main amd64 crate amd64 5.5.2
Connection failed 
E: Failed to fetch [https://cdn.crate.io/downloads/debian/stable/pool/main/crate_5.5.2_amd64.deb]
Connection failed
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```

**Comment by karynzv** [comment] 2024-01-16 19:03
Not sure if this is the right way to report this issue, please let me know.

**Comment by amotl** [comment] 2024-01-17 09:29
Hi, and thanks for reporting. We talked about migrating off Fastly, and using [Bunny CDN](https://bunny.net/) instead the other day. I think we agreed that we do not need to employ Fastly any longer.

/cc @WalBeh, @msbt

**Comment by msbt** [comment] 2024-01-18 13:04
@amotl even though we talked about it, we're far from sunsetting Fastly. However, since the cdn is independent from the website and all other properties/redirects, we could start migrating that when bandwidth is available, since this will be one of the major blockers to actually move away from there (because of the build pipelines and everything that comes with it), wdyt? 

Do we have any logs on the webserver to see why the d/l failed? @karynzv do you maybe have timestamps of failed events?

**Comment by karynzv** [comment] 2024-01-19 15:58
Hi Matthias,

We tried a couple of times, but the one that failed was on January 16th, around 17h15 CET, then, 15 minutes later, it worked again.
Thanks!

**Comment by msbt** [comment] 2024-01-20 09:28
Thanks @karynzv! @WalBeh @amotl can you check the logs if anything happend around that time?

**Comment by hammerhead** [comment] 2024-01-24 07:49
There is currently a file inconsistency in the Debian/Ubuntu repository. The issue is reproducible from EC2 instances in the eu-central-1 (Frankfurt) region:

```
ubuntu@ip-172-31-26-115:~$ sudo add-apt-repository "deb https://cdn.crate.io/downloads/debian/stable/ default main"
Repository: 'deb https://cdn.crate.io/downloads/debian/stable/ default main'
Description:
Archive for codename: default components: main
More info: https://cdn.crate.io/downloads/debian/stable/
Adding repository.
Press [ENTER] to continue or Ctrl-c to cancel.
Adding deb entry to /etc/apt/sources.list.d/archive_uri-https_cdn_crate_io_downloads_debian_stable_-jammy.list
Adding disabled deb-src entry to /etc/apt/sources.list.d/archive_uri-https_cdn_crate_io_downloads_debian_stable_-jammy.list
Hit:1 http://eu-central-1.ec2.archive.ubuntu.com/ubuntu jammy InRelease
Get:2 http://eu-central-1.ec2.archive.ubuntu.com/ubuntu jammy-updates InRelease [119 kB]            
Get:3 http://eu-central-1.ec2.archive.ubuntu.com/ubuntu jammy-backports InRelease [109 kB]          
Get:4 http://security.ubuntu.com/ubuntu jammy-security InRelease [110 kB]                           
Get:5 https://cdn.crate.io/downloads/debian/stable default InRelease [3289 B]   
Get:6 http://eu-central-1.ec2.archive.ubuntu.com/ubuntu jammy/universe amd64 Packages [14.1 MB]
Get:7 http://eu-central-1.ec2.archive.ubuntu.com/ubuntu jammy/universe Translation-en [5652 kB]
Get:8 https://cdn.crate.io/downloads/debian/stable default/main amd64 Packages [815 B]
Err:8 https://cdn.crate.io/downloads/debian/stable default/main amd64 Packages
  File has unexpected size (920 != 815). Mirror sync in progress? [IP: 146.75.117.169 443]
  Hashes of expected file:
   - Filesize:815 [weak]
   - SHA512:971d7f2e53c95c1efb2880fcf59e60ab59e8d3e8ed75bd3bd9bec24fd8d8c8fe27cf9f294aaa372a0fa55c8ebd69eb08ee01084681b934819f55bac3a2c30459
   - SHA256:87c5a6df7201339d5314ca3c11053dfeb35d0016337fc29d82b1b4cbdacf83dd
   - SHA1:dd4273ca71f4b43efbaa71143f8484fb3d1ae2e5 [weak]
   - MD5Sum:abb3aed434e347d989252a7060547283 [weak]
  Release file created at: Fri, 22 Dec 2023 13:14:36 +0000
Get:9 http://eu-central-1.ec2.archive.ubuntu.com/ubuntu jammy/universe amd64 c-n-f Metadata [286 kB]
Get:10 http://eu-central-1.ec2.archive.ubuntu.com/ubuntu jammy/multiverse amd64 Packages [217 kB]
Get:11 http://eu-central-1.ec2.archive.ubuntu.com/ubuntu jammy/multiverse Translation-en [112 kB]
Get:12 http://eu-central-1.ec2.archive.ubuntu.com/ubuntu jammy/multiverse amd64 c-n-f Metadata [8372 B]
Get:13 http://eu-central-1.ec2.archive.ubuntu.com/ubuntu jammy-updates/main amd64 Packages [1283 kB]
Get:14 http://eu-central-1.ec2.archive.ubuntu.com/ubuntu jammy-updates/main Translation-en [263 kB]
Get:15 http://eu-central-1.ec2.archive.ubuntu.com/ubuntu jammy-updates/restricted amd64 Packages [1285 kB]
Get:16 http://eu-central-1.ec2.archive.ubuntu.com/ubuntu jammy-updates/restricted Translation-en [209 kB]
Get:17 http://eu-central-1.ec2.archive.ubuntu.com/ubuntu jammy-updates/universe amd64 Packages [1033 kB]
Get:18 http://eu-central-1.ec2.archive.ubuntu.com/ubuntu jammy-updates/universe Translation-en [232 kB]
Get:19 http://eu-central-1.ec2.archive.ubuntu.com/ubuntu jammy-updates/universe amd64 c-n-f Metadata [22.1 kB]
Get:20 http://eu-central-1.ec2.archive.ubuntu.com/ubuntu jammy-updates/multiverse amd64 Packages [42.1 kB]
Get:21 http://eu-central-1.ec2.archive.ubuntu.com/ubuntu jammy-updates/multiverse Translation-en [10.1 kB]
Get:22 http://eu-central-1.ec2.archive.ubuntu.com/ubuntu jammy-updates/multiverse amd64 c-n-f Metadata [472 B]
Get:23 http://eu-central-1.ec2.archive.ubuntu.com/ubuntu jammy-backports/main amd64 Packages [41.7 kB]
Get:24 http://eu-central-1.ec2.archive.ubuntu.com/ubuntu jammy-backports/main Translation-en [10.5 kB]
Get:25 http://eu-central-1.ec2.archive.ubuntu.com/ubuntu jammy-backports/main amd64 c-n-f Metadata [388 B]
Get:26 http://eu-central-1.ec2.archive.ubuntu.com/ubuntu jammy-backports/restricted amd64 c-n-f Metadata [116 B]
Get:27 http://eu-central-1.ec2.archive.ubuntu.com/ubuntu jammy-backports/universe amd64 Packages [24.2 kB]
Get:28 http://eu-central-1.ec2.archive.ubuntu.com/ubuntu jammy-backports/universe Translation-en [16.5 kB]
Get:29 http://eu-central-1.ec2.archive.ubuntu.com/ubuntu jammy-backports/universe amd64 c-n-f Metadata [644 B]
Get:30 http://eu-central-1.ec2.archive.ubuntu.com/ubuntu jammy-backports/multiverse amd64 c-n-f Metadata [116 B]
Get:31 http://security.ubuntu.com/ubuntu jammy-security/main amd64 Packages [1067 kB]
Get:32 http://security.ubuntu.com/ubuntu jammy-security/main Translation-en [202 kB]
Get:33 http://security.ubuntu.com/ubuntu jammy-security/restricted amd64 Packages [1260 kB]
Get:34 http://security.ubuntu.com/ubuntu jammy-security/restricted Translation-en [206 kB]
Get:35 http://security.ubuntu.com/ubuntu jammy-security/universe amd64 Packages [832 kB]
Get:36 http://security.ubuntu.com/ubuntu jammy-security/universe Translation-en [158 kB]
Get:37 http://security.ubuntu.com/ubuntu jammy-security/universe amd64 c-n-f Metadata [16.8 kB]
Get:38 http://security.ubuntu.com/ubuntu jammy-security/multiverse amd64 Packages [37.1 kB]
Get:39 http://security.ubuntu.com/ubuntu jammy-security/multiverse Translation-en [7476 B]
Get:40 http://security.ubuntu.com/ubuntu jammy-security/multiverse amd64 c-n-f Metadata [260 B]
Fetched 29.0 MB in 5s (6287 kB/s)                          
Reading package lists... Done
W: https://cdn.crate.io/downloads/debian/stable/dists/default/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.
E: Failed to fetch https://cdn.crate.io/downloads/debian/stable/dists/default/main/binary-amd64/Packages.gz  File has unexpected size (920 != 815). Mirror sync in progress? [IP: 146.75.117.169 443]
   Hashes of expected file:
    - Filesize:815 [weak]
    - SHA512:971d7f2e53c95c1efb2880fcf59e60ab59e8d3e8ed75bd3bd9bec24fd8d8c8fe27cf9f294aaa372a0fa55c8ebd69eb08ee01084681b934819f55bac3a2c30459
    - SHA256:87c5a6df7201339d5314ca3c11053dfeb35d0016337fc29d82b1b4cbdacf83dd
    - SHA1:dd4273ca71f4b43efbaa71143f8484fb3d1ae2e5 [weak]
    - MD5Sum:abb3aed434e347d989252a7060547283 [weak]
   Release file created at: Fri, 22 Dec 2023 13:14:36 +0000
E: Some index files failed to download. They have been ignored, or old ones used instead.
```

The issue was reported yesterday by a customer and is reproducible today, so it does not appear to be a temporary sync issue.

**Comment by mfussenegger** [comment] 2024-06-17 15:27
Closing this here - if it is still an issue this should be tracked elsewhere.

**Closed by mfussenegger** 2024-06-17 15:27 UTC
