### ISSUE TITLE
Compatibility with Cube.js

### ISSUE THREAD

**Issue by robd003** [crate/crate#12356] opened 2022-04-19 04:53 UTC
### CrateDB version

4.7.1

### CrateDB setup information

Postgres compatibility issue, breaks across single node or multi-node clusters

### Steps to Reproduce

Run Crate
Run Cube.js
Try to connect Cube.js to Crate using the Postgres driver ( https://github.com/brianc/node-postgres )

### Expected Result

Ability to connect and load databases from Crate

### Actual Result

Error from Cube.js:

```
Error while loading DB schema
error: line 1:10: missing {'TO', '='} at 'ZONE' at Parser.parseErrorMessage (/cubejs/node_modules/pg-protocol/src/parser.ts:369:69) at Parser.handlePacket (/cubejs/node_modules/pg-protocol/src/parser.ts:188:21) at Parser.parse (/cubejs/node_modules/pg-protocol/src/parser.ts:103:30) at Socket.<anonymous> (/cubejs/node_modules/pg-protocol/src/index.ts:7:48) at Socket.emit (node:events:526:28) at addChunk (node:internal/streams/readable:315:12) at readableAddChunk (node:internal/streams/readable:289:9) at Socket.Readable.push (node:internal/streams/readable:228:10) at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
```

It looks like this is in relation to calling this command upon connecting to Crate:

```
SET statement_timeout TO 30
```

**Comment by proddata** [comment] 2022-04-19 09:25
Hi @robd003 

I'd say this is more a feature request and not a bug report.
The error you reported looks like a Cube.js is trying to run something like:

```sql
SET TIME ZONE 'Europe/Rome'
```

while CrateDB only supports

```sql
SET <configuration_parameter> TO <value>
SET <configuration_parameter> = <value>
```

right now.

---

Also setting a timezone is not yet supported.


relates to https://github.com/crate/crate/issues/7196 and https://github.com/crate/crate/issues/10037

**Comment by robd003** [comment] 2022-04-19 17:25
I'm submitting a patch to Cube.js so there will be a "Crate" driver without these calls. However it'd be awesome to get "SET TIME ZONE" to be supported or even just as a null op.

**Comment by proddata** [comment] 2022-04-19 18:56
I created a feature request for the no-op #12363 and would close this issue for now.

**Closed by proddata** 2022-04-19 18:56 UTC
Labels: triage
