### ISSUE TITLE
Performance Regression in outer join benchmark

### ISSUE THREAD

**Issue by mkleen** [crate/crate#15210] opened 2023-12-18 10:53 UTC
We have a performance regression on the query:

```
select e.name as employee, o.name as office from employees e left join offices o on e.office_id = e.id limit 50000
```

See regression [here](https://tools.cr8.net/grafana/d/E80m4pn7z/cratedb-benchmarks?orgId=1&var-spec_file=outer-joins.toml&var-statement=select%20e.name%20as%20employee,%20o.name%20as%20office%20from%20employees%20e%20full%20join%20offices%20o%20on%20e.office_id%20%3D%20e.id%20limit%2050000&var-statement=SELECT%0A%20%20%20%20film.film_id%20AS%20FID,%0A%20%20%20%20film.title%20AS%20title,%0A%20%20%20%20film.description%20AS%20description,%0A%20%20%20%20category.name%20AS%20category,%0A%20%20%20%20film.rental_rate%20AS%20price,%0A%20%20%20%20film.length%20AS%20length,%0A%20%20%20%20film.rating%20AS%20rating%0AFROM%20%0A%20%20%20%20category%20%0A%20%20%20%20LEFT%20JOIN%20film_category%20ON%20category.category_id%20%3D%20film_category.category_id%20%0A%20%20%20%20LEFT%20JOIN%20film%20ON%20film_category.film_id%20%3D%20film.film_id%0A%20%20%20%20JOIN%20film_actor%20ON%20film.film_id%20%3D%20film_actor.film_id%0A%20%20%20%20JOIN%20actor%20ON%20film_actor.actor_id%20%3D%20actor.actor_id;%0A&var-statement=select%20e.name%20as%20employee,%20o.name%20as%20office%20from%20employees%20e%20left%20join%20offices%20o%20on%20e.office_id%20%3D%20e.id%20limit%2050000&var-statement=select%20e.name%20as%20employee,%20o.name%20as%20office%20from%20employees%20e%20right%20join%20offices%20o%20on%20e.office_id%20%3D%20e.id%20limit%2050000&var-concurrency=1&viewPanel=4).

**Comment by jeeminso** [comment] 2023-12-22 04:13
Tried git bisect and `https://github.com/crate/crate/pull/14911` is found to be the cause. Will double check and proceed.

**Comment by BaurzhanSakhariev** [comment] 2023-12-22 06:24
> Tried git bisect and #14911 is found to be the cause. Will double check and proceed.

This change is related only to inserts. Also, the first high spike happens on 01.11.2023 and linked PR was merged on 18.10.2023, and there were some points without regression between those dates.

**Comment by jeeminso** [comment] 2023-12-24 21:52
There is another regression caught by the same benchmark caused by https://github.com/crate/crate/commit/44172b21d00c5c612ade656fb68233425ddac957 cc @mkleen :

```

Starting Crate process
CrateDB launching:
    PID: 573376
    Logs: /home/minsoojee/crate/crate/app/target/crate-5.6.0-2023-12-24-21-38-f9f1612/logs/cr8-crate-run404136670.log
    Data: /tmp/tmpm3wupu13 (removed on stop)

Psql      : 127.0.0.1:5432
Http      : 127.0.0.1:4200
Transport : 127.0.0.1:4300
Cluster ready to process requests


# run-spec
==========

# Running setUp
1 requests [00:00, 10.10 requests/s]
2 requests [00:00,  8.72 requests/s]
1 requests [00:00,  9.67 requests/s]
1 requests [00:00, 22.21 requests/s]
1 requests [00:00, 119.08 requests/s]
2 requests [00:00, 68.35 requests/s]
1 requests [00:00, 88.10 requests/s]
# Running benchmark

## Running Query:
   Statement:
     select e.name as employee, o.name as office from employees e left join offices o on e.office_id = e.id limit 50000
   Concurrency: 1
   Iterations: 100
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 100/100 [00:05<00:00, 17.96 requests/s]
Runtime (in ms):
    mean:    36.564 ± 3.226
    min/max: 30.660 → 179.500
Percentile:
    50:   32.424 ± 16.458 (stdev)
    95:   50.385
    99.9: 179.500
# Running tearDown

```

```

Starting Crate process
CrateDB launching:
    PID: 569385
    Logs: /home/minsoojee/crate/crate/app/target/crate-5.6.0-2023-12-24-21-18-44172b2/logs/cr8-crate-run853484368.log
    Data: /tmp/tmp9yg5_2bw (removed on stop)

Psql      : 127.0.0.1:5432
Http      : 127.0.0.1:4200
Transport : 127.0.0.1:4300
Cluster ready to process requests


# run-spec
==========

# Running setUp
1 requests [00:00, 11.57 requests/s]
2 requests [00:00,  7.97 requests/s]
1 requests [00:00,  9.10 requests/s]
1 requests [00:00, 19.01 requests/s]
1 requests [00:00, 122.87 requests/s]
2 requests [00:00, 65.09 requests/s]
1 requests [00:00, 81.03 requests/s]
# Running benchmark

## Running Query:
   Statement:
     select e.name as employee, o.name as office from employees e left join offices o on e.office_id = e.id limit 50000
   Concurrency: 1
   Iterations: 100
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 100/100 [00:27<00:00,  3.57 requests/s]
Runtime (in ms):
    mean:    260.509 ± 7.108
    min/max: 248.027 → 581.436
Percentile:
    50:   253.266 ± 36.266 (stdev)
    95:   272.217
    99.9: 581.436
# Running tearDown

```

**Comment by jeeminso** [comment] 2023-12-24 21:54
Regarding the original regression identified by the max value, so far I have no luck reproducing the `good` behaviour. The max value never turned out to be less than 100 ms locally. The good and bad values were closer and for `99.5` and `95` the situation was even reversed.

**Comment by BaurzhanSakhariev** [comment] 2023-12-25 12:23
regarding first regression - looks like https://github.com/crate/crate/commit/df3d28ed7bd2d466a8ce13e8be427fe89acefcb6 is the only relevant to joins commit between 25.10-01.11

**Comment by jeeminso** [comment] 2024-01-02 20:11
Thanks a lot @BaurzhanSakhariev . Currently I am working on another issue, I will unassign myself for now.

**Comment by BaurzhanSakhariev** [comment] 2024-01-05 11:24
> update: done more investigations, I think we now have an extra fetch which causes the degradation. 

This is most likely related to https://github.com/crate/crate/pull/15227#discussion_r1433977031. ==> related to 
> There is another regression caught by the same benchmark caused by https://github.com/crate/crate/commit/44172b21d00c5c612ade656fb68233425ddac957

**Comment by jeeminso** [comment] 2024-01-07 20:56
> > update: done more investigations, I think we now have an extra fetch which causes the degradation.
> 
> This is most likely related to [#15227 (comment)](https://github.com/crate/crate/pull/15227#discussion_r1433977031). ==> related to
> 
> > There is another regression caught by the same benchmark caused by [44172b2](https://github.com/crate/crate/commit/44172b21d00c5c612ade656fb68233425ddac957)

Ah I just realized that you were pointing at the folded comment...

**Comment by jeeminso** [comment] 2024-01-08 20:50
update: locally https://github.com/crate/crate/commit/df3d28ed7bd2d466a8ce13e8be427fe89acefcb6 does not seem to be the cause:

`df3d28`:
```
## Running Query:
   Statement:
     select e.name as employee, o.name as office from employees e left join offices o on e.office_id = e.id limit 50000
   Concurrency: 1
   Iterations: 250
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 250/250 [00:13<00:00, 18.10 requests/s]
Runtime (in ms):
    mean:    36.283 ± 0.775
    min/max: 32.001 → 115.004
Percentile:
    50:   34.315 ± 6.253 (stdev)
    95:   42.616
    99.9: 115.004
```
`a3fec13` (previous commit):
```
## Running Query:
   Statement:
     select e.name as employee, o.name as office from employees e left join offices o on e.office_id = e.id limit 50000
   Concurrency: 1
   Iterations: 250
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 250/250 [00:13<00:00, 18.56 requests/s]
Runtime (in ms):
    mean:    34.778 ± 0.788
    min/max: 30.728 → 112.965
Percentile:
    50:   32.735 ± 6.354 (stdev)
    95:   39.960
    99.9: 112.965
```

**Comment by BaurzhanSakhariev** [comment] 2024-01-11 12:39
dev-cluster
https://tools.cr8.net/grafana/d/-8PNA2vnz/cratedb-dev-cluster-benchmarks?orgId=1&var-spec_file=outer-joins.toml&var-statement=select%20e.name%20as%20employee,%20o.name%20as%20office%20from%20employees%20e%20full%20join%20offices%20o%20on%20e.office_id%20%3D%20e.id%20limit%2050000&var-concurrency=1&from=now-6M&to=now

caught by crate-alerts https://github.com/crate/crate-alerts/issues/608,slghtly higher from the end of August

**Comment by jeeminso** [comment] 2024-02-14 17:58
> dev-cluster https://tools.cr8.net/grafana/d/-8PNA2vnz/cratedb-dev-cluster-benchmarks?orgId=1&var-spec_file=outer-joins.toml&var-statement=select%20e.name%20as%20employee,%20o.name%20as%20office%20from%20employees%20e%20full%20join%20offices%20o%20on%20e.office_id%20%3D%20e.id%20limit%2050000&var-concurrency=1&from=now-6M&to=now
> 
> caught by crate-alerts [crate/crate-alerts#608](https://github.com/crate/crate-alerts/issues/608), mean got slightly higher from the end of August

Between Aug 30th - Aug 31st there is an increase over 10% but I double these commits would affect join performance:
```
8acb044a7c Introduce ReferenceAssert to make Reference assertions composable
ee4adb63ee Move line parsing out of FileReadingIterator
```

**Closed** 2024-07-01 09:17 UTC
