### ISSUE TITLE
crate 2.3.3 does not work with metabase

### ISSUE THREAD

**Issue by on99** [crate/crate#6976] opened 2018-02-27 15:28 UTC
**CrateDB version**: 2.3.3

**JVM version**: docker

**OS version / environment description**: docker

**Problem description**:

Metabase failed to sync table of crate 2.3.3.

```
02-27 23:22:29 ERROR sync.util :: Error syncing fields for Table 150 'sys.summits': ERROR: SQLParseException: Cannot cast constraint_name to type [undefined_table, undefined_set, undefined_array]
("driver.crate$add_table_pks.invokeStatic(crate.clj:79)"
 "driver.crate$add_table_pks.invoke(crate.clj:77)"
 "driver.crate$describe_table.invokeStatic(crate.clj:94)"
 "driver.crate$describe_table.invoke(crate.clj:89)"
 "driver$fn__25511$G__25367__25520.invoke(driver.clj:51)"
 "sync.fetch_metadata$fn__35668$table_metadata__35673$fn__35674.invoke(fetch_metadata.clj:18)"
 "sync.fetch_metadata$fn__35668$table_metadata__35673.invoke(fetch_metadata.clj:15)"
 "sync.sync_metadata.fields$fn__36229$db_metadata__36234$fn__36235.invoke(fields.clj:294)"
 "sync.sync_metadata.fields$fn__36229$db_metadata__36234.invoke(fields.clj:290)"
 "sync.sync_metadata.fields$fn__36257$sync_fields_for_table_BANG___36266$fn__36269$fn__36270.invoke(fields.clj:307)"
 "sync.util$do_with_error_handling.invokeStatic(util.clj:124)"
 "sync.util$do_with_error_handling.invoke(util.clj:119)"
 "sync.sync_metadata.fields$fn__36257$sync_fields_for_table_BANG___36266$fn__36269.invoke(fields.clj:306)"
 "sync.sync_metadata.fields$fn__36257$sync_fields_for_table_BANG___36266.invoke(fields.clj:301)"
 "sync.sync_metadata.fields$fn__36295$sync_fields_BANG___36300$fn__36301.invoke(fields.clj:318)"
 "sync.sync_metadata.fields$fn__36295$sync_fields_BANG___36300.invoke(fields.clj:314)"
 "sync.sync_metadata$fn__36864$sync_db_metadata_BANG___36869$fn__36870$fn__36871.invoke(sync_metadata.clj:28)"
 "sync.util$do_with_error_handling.invokeStatic(util.clj:124)"
 "sync.util$do_with_error_handling.invoke(util.clj:119)"
 "sync.util$do_with_error_handling.invokeStatic(util.clj:122)"
 "sync.util$do_with_error_handling.invoke(util.clj:119)"
 "driver$fn__25602.invokeStatic(driver.clj:226)"
 "driver$fn__25602.invoke(driver.clj:226)"
 "driver$fn__25526$G__25357__25535.invoke(driver.clj:51)"
 "sync.util$sync_in_context$fn__34128.invoke(util.clj:115)"
 "sync.util$with_db_logging_disabled$fn__34125.invoke(util.clj:106)"
 "sync.util$with_start_and_finish_logging$fn__34120.invoke(util.clj:92)"
 "sync.util$with_sync_events$fn__34117.invoke(util.clj:75)"
 "sync.util$with_duplicate_ops_prevented$fn__34108.invoke(util.clj:54)"
 "sync.util$do_sync_operation.invokeStatic(util.clj:142)"
 "sync.util$do_sync_operation.invoke(util.clj:139)"
 "sync.sync_metadata$fn__36864$sync_db_metadata_BANG___36869$fn__36870.invoke(sync_metadata.clj:23)"
 "sync.sync_metadata$fn__36864$sync_db_metadata_BANG___36869.invoke(sync_metadata.clj:20)"
 "api.database$fn__37519$fn__37520$fn__37521.invoke(database.clj:505)")

02-27 23:22:29 ERROR sync.util :: Error syncing fields for Table 151 'sys.snapshots': ERROR: SQLParseException: Cannot cast constraint_name to type [undefined_table, undefined_set, undefined_array]
("driver.crate$add_table_pks.invokeStatic(crate.clj:79)"
 "driver.crate$add_table_pks.invoke(crate.clj:77)"
 "driver.crate$describe_table.invokeStatic(crate.clj:94)"
 "driver.crate$describe_table.invoke(crate.clj:89)"
 "driver$fn__25511$G__25367__25520.invoke(driver.clj:51)"
 "sync.fetch_metadata$fn__35668$table_metadata__35673$fn__35674.invoke(fetch_metadata.clj:18)"
 "sync.fetch_metadata$fn__35668$table_metadata__35673.invoke(fetch_metadata.clj:15)"
 "sync.sync_metadata.fields$fn__36229$db_metadata__36234$fn__36235.invoke(fields.clj:294)"
 "sync.sync_metadata.fields$fn__36229$db_metadata__36234.invoke(fields.clj:290)"
 "sync.sync_metadata.fields$fn__36257$sync_fields_for_table_BANG___36266$fn__36269$fn__36270.invoke(fields.clj:307)"
 "sync.util$do_with_error_handling.invokeStatic(util.clj:124)"
 "sync.util$do_with_error_handling.invoke(util.clj:119)"
 "sync.sync_metadata.fields$fn__36257$sync_fields_for_table_BANG___36266$fn__36269.invoke(fields.clj:306)"
 "sync.sync_metadata.fields$fn__36257$sync_fields_for_table_BANG___36266.invoke(fields.clj:301)"
 "sync.sync_metadata.fields$fn__36295$sync_fields_BANG___36300$fn__36301.invoke(fields.clj:318)"
 "sync.sync_metadata.fields$fn__36295$sync_fields_BANG___36300.invoke(fields.clj:314)"
 "sync.sync_metadata$fn__36864$sync_db_metadata_BANG___36869$fn__36870$fn__36871.invoke(sync_metadata.clj:28)"
 "sync.util$do_with_error_handling.invokeStatic(util.clj:124)"
 "sync.util$do_with_error_handling.invoke(util.clj:119)"
 "sync.util$do_with_error_handling.invokeStatic(util.clj:122)"
 "sync.util$do_with_error_handling.invoke(util.clj:119)"
 "driver$fn__25602.invokeStatic(driver.clj:226)"
 "driver$fn__25602.invoke(driver.clj:226)"
 "driver$fn__25526$G__25357__25535.invoke(driver.clj:51)"
 "sync.util$sync_in_context$fn__34128.invoke(util.clj:115)"
 "sync.util$with_db_logging_disabled$fn__34125.invoke(util.clj:106)"
 "sync.util$with_start_and_finish_logging$fn__34120.invoke(util.clj:92)"
 "sync.util$with_sync_events$fn__34117.invoke(util.clj:75)"
 "sync.util$with_duplicate_ops_prevented$fn__34108.invoke(util.clj:54)"
 "sync.util$do_sync_operation.invokeStatic(util.clj:142)"
 "sync.util$do_sync_operation.invoke(util.clj:139)"
 "sync.sync_metadata$fn__36864$sync_db_metadata_BANG___36869$fn__36870.invoke(sync_metadata.clj:23)"
 "sync.sync_metadata$fn__36864$sync_db_metadata_BANG___36869.invoke(sync_metadata.clj:20)"
 "api.database$fn__37519$fn__37520$fn__37521.invoke(database.clj:505)")

02-27 23:22:29 INFO sync.util :: FINISHED: Sync metadata for crate Database 4 'test-crate-2.3.3' (1 s)
```

**Steps to reproduce**:

It's easy to reproduce, even without a user-defined table in crate, system table is enough to reproduce.

```bash
$ docker pull crate
$ docker pull metabase/metabase
$ docker run -d -p 4200:4200 -p 4300:4300 -p 5432:5432 crate --name crate -Cnetwork.host=_site_
$ docker run -d -p 3000:3000 -v ~/.metabase:/metabase-data -e "MB_DB_FILE=/metabase-data/metabase.db" --name metabase metabase/metabase
$ docker logs -f metabase
```

Add a crate database in metabase admin panel, and every time click `Sync database schema now` button from the admin panel, you can see the error log from console.

**Comment by on99** [comment] 2018-02-27 15:29
Please noted that metabase is OK with crate 2.2.5.

**Comment by mikethebeer** [comment] 2018-03-05 09:20
Thanks for notifying us. We will try to investigate the issue and report back to you if we have a proper fix for it.

**Comment by on99** [comment] 2018-03-12 08:23
@mikethebeer Thank you for help!

**Comment by mfussenegger** [comment] 2018-03-12 12:07
Judging from the error message this might be related to https://github.com/crate/crate-jdbc/issues/255

**Comment by on99** [comment] 2018-03-12 13:41
@mfussenegger Cool, seems like it is the case. Maybe metabase should update crate-jdbc once you have a fix, it takes time.

**Comment by BlankRain** [comment] 2018-03-13 06:33
@on99  metabase is okay with crate.

**Comment by on99** [comment] 2018-03-13 08:22
@BlankRain Really? I cannot use metabase with crate 2.3.3, the reproduce steps are above, can you give it a shot?

**Comment by BlankRain** [comment] 2018-03-14 06:44
@on99   It's okay when querying questions.  Unfortunately, it log errors when  syncing databases. 
It doesn't matter too much...

**Comment by on99** [comment] 2018-03-14 09:29
@BlankRain Cool, but it requires we have the data model in metabase in advance, and data model cannot be updated.

**Comment by BlankRain** [comment] 2018-03-16 13:42
@on99  next hot fix release will fix it..
 see at https://github.com/crate/crate-jdbc/issues/255 .

**Comment by on99** [comment] 2018-03-23 15:08
@mfussenegger @mikethebeer Can you send a pull request to metabase to upgrade crate driver jdbc version?

**Comment by mikethebeer** [comment] 2018-03-26 08:08
@on99 I did some investigation on the Metabase support and it seems that the jdbc version bump alone does not fix the data model issues we have on the current version of Metabase. The problem is that we are not in sync with the feature set of Metabase. A lot of tests (see https://github.com/metabase/metabase/issues/4290) are failing and it is useless to just make a PR with a version bump that does not fix the data model generation at all.

Since the traction on Metabase is really low the CrateDB support in Metabase is more or less low-priority for us. I know on the first sight this sounds not really satisfying, however we try to renew the support for Metabase in the future.

**Comment by on99** [comment] 2018-03-27 01:49
@mikethebeer 
Thanks for your investigation! It's good, I can keep using crate 2.2.5, not upgrading to >= 2.3.0 until the issue is fixed XD (can you please drop a note here if the issue is resolved?)

**Comment by mikethebeer** [comment] 2018-03-27 07:32
@on99 sure. we will keep this issue open and inform you if we know more insights.

**Comment by on99** [comment] 2018-04-13 03:47
@mikethebeer I filed an issue https://github.com/metabase/metabase/issues/7192 in metabase and they fixed it, but they failed to get tests run against crate in docker, I am wondering if you can help them out so metabase can work better with crate.

**Comment by chaudum** [comment] 2018-04-13 07:00
hi @on99 unfortunately we only have the capacity to support a very few third party applications properly. Furthermore we do not have a good Clojure developer at hand at the moment, who could take over the Metabase integration. However, we are looking for someone already.
If there are any good Clojure programmers reading this, please get in contact with us!

**Comment by on99** [comment] 2018-04-13 10:14
@chaudum Glad to hear that, thank you! XD

**Comment by mfussenegger** [comment] 2020-07-07 09:02
Closing this as it is probably outdated. Looks like CrateDB support in Metabase has moved to a separate community maintained plugin https://github.com/metabase/crate-driver

**Closed by mfussenegger** 2020-07-07 09:02 UTC
Labels: feature: integration
