### ISSUE TITLE
Data too large, data for [collect: 0] 

### ISSUE THREAD

**Issue by Samuman** [crate/crate#3130] opened 2015-12-29 18:08 UTC
Hi Folks.

Im trying to understand whats happening here.

Using following command:
    SELECT id, max(timestamp), min(active) FROM data
    GROUP BY id HAVING min(active) = 1 and max(timestamp) < 1451235532

Maybe after 30-60mins of runtime this command starts failing with:
ProgrammingError: SQLActionException[[query] Data too large, data for [collect: 0] would be larger than limit of [2570007347/2.3gb]]

Im throwing more memory to heap but in the end I always hit the same wall. Data size seems to hit the breaker sooner or later.

Table size is currently 40 megs so I can't understand why this query is painful to process.

Im using 0.52.4 but I tried also with 0.54.1 but I didn't make any difference. Is this working as expected ?

**Comment by mfussenegger** [comment] 2015-12-29 21:33
This seems a bit odd, especially if the table is so small. How many records are there if it has only 40 mb?

Can you also post the schema of your table?
And how much memory did you give to Crate as heap size?

**Comment by Samuman** [comment] 2015-12-30 15:53
**Details:**
Total Records: 40,237
Size: 30.8 MB

**Created with:**
create table data (
  id string primary key,
  timestamp string primary key,
  name string,
  description string,
  price int,
  region string,
  city string,
  active int) with (number_of_replicas = '0-1');

Heap size was set to 3g by environmental variable. I also raised breaker limits but it didn't make any difference compared to default except that limit was higher.

This line is from crate.log:
[2015-12-30 15:47:23,093][WARN ][indices.breaker          ] [Rex Mundi] [QUERY] New used memory 2571702120 [2.3gb] for data of [collect: 0] would be larger than configured breaker: 2570007347 [2.3gb], breaking

**Comment by chaudum** [comment] 2016-01-07 13:45
This is very strange indeed.
I've created 40k sampledata and the query also works with 256mb HEAP and subsecond query time (using 0.54.1).
can you paste the output of `crash --sysinfo`?

**Comment by Samuman** [comment] 2016-01-09 12:30
Thanks for looking into this.

I managed to overcome the problem by adding second node to the cluster and restarting existing master. Christian did you try this with a one node only?

I'm now on 0.52.4, is this command supported?
usage: crash_standalone [-h] [-v] [--history HISTORY] [-c COMMAND]
                        [--hosts [HOST [HOST ...]]] [--format FORMAT]
                        [--version]
crash_standalone: error: unrecognized arguments: --sysinfo

crate-1:~/crate-0.52.4/bin$ ./crash --version
0.14.3

Linux crate-1 3.19.0-33-generic #38~14.04.1-Ubuntu SMP Fri Nov 6 18:17:28 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux. Instance is running with 1vCPU and 4gb ram.

I've been running with two nodes now maybe a week, I only had outage once where collect started to fail with size of 5-6gb. After restart everything went back to green. Luckily this time there was a stack trace that is hopefully linked to this issue:

```
[2016-01-06 09:40:18,092][WARN ][indices.breaker          ] [Zero-G] [QUERY] New used memory 5781224532 [5.3gb] for data of [collect: 0] would be larger than configured breaker: 2570007347 [2.3gb], breaking                   [1527/1527]
[2016-01-06 09:40:28,679][WARN ][indices.breaker          ] [Zero-G] [QUERY] New used memory 5781224591 [5.3gb] for data of [distributing collect: 0] would be larger than configured breaker: 2570007347 [2.3gb], breaking
[2016-01-06 09:40:29,124][WARN ][indices.breaker          ] [Zero-G] [QUERY] New used memory 5781224532 [5.3gb] for data of [collect: 0] would be larger than configured breaker: 2570007347 [2.3gb], breaking
[2016-01-06 09:40:39,885][WARN ][indices.breaker          ] [Zero-G] [QUERY] New used memory 5781224611 [5.3gb] for data of [distributing collect: 0] would be larger than configured breaker: 2570007347 [2.3gb], breaking
[2016-01-06 09:40:40,316][WARN ][indices.breaker          ] [Zero-G] [QUERY] New used memory 5781224598 [5.3gb] for data of [localMerge: 1] would be larger than configured breaker: 2570007347 [2.3gb], breaking
Jan 06, 2016 9:40:40 AM com.google.common.util.concurrent.ExecutionList executeListener
SEVERE: RuntimeException while executing runnable com.google.common.util.concurrent.Futures$6@33b20de6 with executor INSTANCE
org.elasticsearch.common.breaker.CircuitBreakingException: [QUERY] Data too large, data for [localMerge: 1] would be larger than limit of [2570007347/2.3gb]
        at org.elasticsearch.common.breaker.ChildMemoryCircuitBreaker.circuitBreak(ChildMemoryCircuitBreaker.java:97)
        at org.elasticsearch.common.breaker.ChildMemoryCircuitBreaker.addEstimateBytesAndMaybeBreak(ChildMemoryCircuitBreaker.java:148)
        at io.crate.breaker.RamAccountingContext.flush(RamAccountingContext.java:86)
        at io.crate.breaker.RamAccountingContext.addBytes(RamAccountingContext.java:70)
        at io.crate.operation.projectors.GroupingProjector$SingleKeyGrouper.setNextRow(GroupingProjector.java:197)
        at io.crate.operation.projectors.GroupingProjector.setNextRow(GroupingProjector.java:103)
        at io.crate.operation.merge.IteratorPageDownstream.processBuckets(IteratorPageDownstream.java:95)
        at io.crate.operation.merge.IteratorPageDownstream.access$200(IteratorPageDownstream.java:50)
        at io.crate.operation.merge.IteratorPageDownstream$1.onSuccess(IteratorPageDownstream.java:119)
        at io.crate.operation.merge.IteratorPageDownstream$1.onSuccess(IteratorPageDownstream.java:115)
        at io.crate.core.MultiFutureCallback.countdown(MultiFutureCallback.java:65)
        at io.crate.core.MultiFutureCallback.onSuccess(MultiFutureCallback.java:52)
        at com.google.common.util.concurrent.Futures$6.run(Futures.java:1319)
        at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:457)
        at com.google.common.util.concurrent.ExecutionList.executeListener(ExecutionList.java:156)
        at com.google.common.util.concurrent.ExecutionList.execute(ExecutionList.java:145)
        at com.google.common.util.concurrent.AbstractFuture.set(AbstractFuture.java:185)
        at com.google.common.util.concurrent.SettableFuture.set(SettableFuture.java:53)
        at io.crate.jobs.PageDownstreamContext.setBucket(PageDownstreamContext.java:136)
        at io.crate.executor.transport.ExecutionPhasesTask$DirectResponseListener.onResponse(ExecutionPhasesTask.java:256)
        at io.crate.executor.transport.ExecutionPhasesTask$DirectResponseListener.onResponse(ExecutionPhasesTask.java:237)
        at io.crate.executor.transport.DefaultTransportResponseHandler.handleResponse(DefaultTransportResponseHandler.java:57)
        at org.elasticsearch.transport.netty.MessageChannelHandler.handleResponse(MessageChannelHandler.java:163)
        at org.elasticsearch.transport.netty.MessageChannelHandler.messageReceived(MessageChannelHandler.java:132)
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296)
        at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:462)
        at org.jboss.netty.handler.codec.frame.FrameDecoder.callDecode(FrameDecoder.java:443)
        at org.jboss.netty.handler.codec.frame.FrameDecoder.messageReceived(FrameDecoder.java:310)
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268)
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255)
        at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
        at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
        at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
        at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
        at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)

[2016-01-06 09:40:50,970][WARN ][indices.breaker          ] [Zero-G] [QUERY] New used memory 5783510572 [5.3gb] for data of [distributing collect: 0] would be larger than configured breaker: 2570007347 [2.3gb], breaking
[2016-01-06 09:41:02,125][WARN ][indices.breaker          ] [Zero-G] [QUERY] New used memory 5783510585 [5.3gb] for data of [distributing collect: 0] would be larger than configured breaker: 2570007347 [2.3gb], breaking
[2016-01-06 09:41:13,254][WARN ][indices.breaker          ] [Zero-G] [QUERY] New used memory 5783510585 [5.3gb] for data of [distributing collect: 0] would be larger than configured breaker: 2570007347 [2.3gb], breaking
[2016-01-06 09:41:13,563][WARN ][indices.breaker          ] [Zero-G] [QUERY] New used memory 5783510572 [5.3gb] for data of [localMerge: 1] would be larger than configured breaker: 2570007347 [2.3gb], breaking
Jan 06, 2016 9:41:13 AM com.google.common.util.concurrent.ExecutionList executeListener
... This goes on the same way for a long time ...
```

**Comment by chaudum** [comment] 2016-01-11 07:29
The crash command is only supported in `crate>=0.54.0` with `crash>=0.15.0`
Unfortunately the stacktrace does not really show anything, it's just the default of a circuit breaker aborting an execution.
I've been testing on my local machine, single node. I can try with a Ubuntu 14.4 installation. Did you install Crate via ppa or using the tarball?

**Comment by Samuman** [comment] 2016-01-12 17:00
Ok, I have been using tarball for install.

**Comment by chaudum** [comment] 2016-01-14 09:33
hi @Samuman 
I still was not able to reproduce your issue. however, I've seen that you're using a STRING type for your timestamp column. you should use the [TIMESTAMP](https://crate.io/docs/reference/sql/data_types.html#timestamp) type instead. grouping and global aggregations on string values are not as fast as on other types. you are also using a LONG to compare with the STRING column in your query.

**Comment by mfussenegger** [comment] 2016-01-15 18:57
Would it be possible for you to provide us with a heap memory dump? (Which you can create using jmap or something like [visualvm](https://visualvm.java.net/))

It would be best if you take the dump after you executed your query but before it run into the circuit breaker exception.
And in order to keep the dump size small you can set the heap size to something like 64 MB. That should be enough to run the query on 40k records.

**Comment by Samuman** [comment] 2016-01-20 19:14
Hello, sorry for long delay. Table size has grown from ~40k close to a million rows already since this thread started. I tried to drop one of the nodes and it appears to be still happening. In my environment this is quite easy to reproduce.

Would it be ok to set up a quick VC so I could show you how its happening ?

**Comment by chaudum** [comment] 2016-01-22 08:33
hi @Samuman 
sure, let's do a video call. please contact me christian.haudum@crate.io so we can schedule the call.

**Comment by chaudum** [comment] 2016-02-01 07:07
@Samuman you can also join our hipchat support channel https://www.hipchat.com/g7Pc2CYwi

**Comment by chaudum** [comment] 2016-02-10 07:07
As we have discussed earlier, this problem is caused only under high utilisation of the node and the circuit breaker reacts correctly (break instead of running into a possible OOM exception) and adding additional heap memory solves the issue.
So I think it is ok to close the issue now.

**Closed by chaudum** 2016-02-10 07:07 UTC
