### ISSUE TITLE
ProcessClusterEventTimeoutException

### ISSUE THREAD

**Issue by zhangyatao123456** [crate/crate#11576] opened 2021-07-18 07:22 UTC
**CrateDB version**:
4.2.1

**Environment description**:

**Problem description**:

**Steps to reproduce**:

今天创建表和删除表的时候,抛出了一个异常,不知道这个异常怎么回事,现在在测试环境上没有出现这个问题!
简表语句:
```sql
CREATE TABLE IF NOT EXISTS "s_1"."d_1554" (
   "__rowid__" TEXT,
   "_4f90fc8c5ace4649bdeb0e561b225746" TEXT,
   "_b7ad7964078e41c5b55ea445182d35e3" TEXT,
   "_4e73215a049c4b8692eae994611e86be" TIMESTAMP WITH TIME ZONE,
   "_d2b7c4c6df034413ab4b7a53c0cfb0f8" TIMESTAMP WITH TIME ZONE,
   "_afea8874e3324a849557f2be04e9f4a5" TEXT,
   "_69f8c7c4bdaf40f8b58b579518876010" TEXT,
   "_cf98b6fe737d48f8bb0b2629e00091a5" TEXT,
   "_785aaa225cd44128bba5f1f536e78a87" TEXT,
   "_76d9367d695041a2aa7b1c4dcb5492b0" TEXT,
   "_09141088107346df93e8fa3dab2b3c99" TEXT,
   "_da3f0b5f12c54504b87119e6a7cfb6d8" DOUBLE PRECISION,
   "_ae2dd836563648609d77ca333f1e8fe7" TIMESTAMP WITH TIME ZONE,
   "_19552713e5234d5bb13f7c278f4b543b" TEXT,
   "_1f0495509f624a83ac5087088a2a81b7" TEXT,
   "_06090c1802af436891473173a9e7e249" TEXT,
   "_5c67a2470a33424585f8d5fe68be7d20" TEXT,
   "_79e51a8db3934d8dbc27e5a82b02115f" TEXT,
   "_51b141f64791409ab9ec60f5cf6976e1" TEXT,
   "_9446d65868fb4fdf9d9e33cd2b4c55ba" TEXT,
   "_21a8ee61e2114963b7900103a23f7dd8" TEXT,
   "_0d8ce534a7f541f8a034ee3b384fe27b" TEXT,
   "_1eea19ceb3064f9188229d4b1da91c5c" TEXT,
   "_e079ac91ebd04a048926bb2a52ac1aa0" TEXT,
   "_dc231ba7fd98490aafbc15b8f8adc3cb" TEXT,
   "_3054e9f0e95b4bdc8a17b779a9bf8b52" DOUBLE PRECISION,
   "_11d95703ef8a4ab49c298587c0be92e1" TEXT,
   "_e67885e2812c40ee9d0b2d3345064604" TEXT,
   "_7a3845d06ba148188844d505d96dc0ed" TEXT,
   "_39c6855649394b59bf6f84bbfa751872" TEXT,
   "codes" ARRAY(OBJECT(DYNAMIC)),
   "words" ARRAY(OBJECT(DYNAMIC)),
   "topics" ARRAY(OBJECT(DYNAMIC)),
   "sentiments" ARRAY(OBJECT(DYNAMIC)),
   "batch_id" TEXT,
   "item_index" INTEGER,
   "create_time" TIMESTAMP WITH TIME ZONE,
   "modify_time" TIMESTAMP WITH TIME ZONE,
   PRIMARY KEY ("__rowid__")
)
CLUSTERED BY ("__rowid__") INTO 10 SHARDS
WITH (
   "allocation.max_retries" = 5,
   "blocks.metadata" = false,
   "blocks.read" = false,
   "blocks.read_only" = false,
   "blocks.read_only_allow_delete" = false,
   "blocks.write" = false,
   codec = 'default',
   column_policy = 'strict',
   "mapping.total_fields.limit" = 1000,
   max_ngram_diff = 1,
   max_shingle_diff = 3,
   number_of_replicas = '1',
   refresh_interval = 1000,
   "routing.allocation.enable" = 'all',
   "routing.allocation.total_shards_per_node" = -1,
   "store.type" = 'fs',
   "translog.durability" = 'REQUEST',
   "translog.flush_threshold_size" = 536870912,
   "translog.sync_interval" = 5000,
   "unassigned.node_left.delayed_timeout" = 60000,
   "write.wait_for_active_shards" = '0'
)
```

异常信息:
![Uploading 企业微信截图_16263374305085.png…]()

在线等:

**Comment by mfussenegger** [comment] 2021-07-19 07:48
A `ProcessClusterEventTimeoutException` error can occur when a statement that needs to modify the cluster state takes too long.

Root cause is probably an overloaded cluster. Do you've metrics available that give more insights into the load?

**Comment by zhangyatao123456** [comment] 2021-07-29 08:10
看着负载也不高啊！我现在把ack改成了 90s，现在修改表的时候还是超时！老兄你说的集群过载是指每台机器负载呢！还是说cratedb数据过多呢！能详细说一下吗！

> 一个`ProcessClusterEventTimeoutException`当需要修改群集状态的语句耗时过长，可能会发生错误。
> 
> 根本原因可能是集群过载。您是否有可以更深入地了解负载的指标？

**Comment by mfussenegger** [comment] 2021-07-29 14:44
Are there any warnings or errors in the log files - or could you share them with us? 
How many tables are in the cluster?
How many shards are in the cluster?

If processing a cluster state change takes 30 seconds, without having a high load it could point to an overallocation of shards / or tables - leading to a huge cluster state.

**Comment by zhangyatao123456** [comment] 2021-07-30 05:25
现在从日志上看没什么问题！
集群规模5个节点
集群中有每个节点上有 6555个分片！
总分区数 12270个
现在有3633个表
现在把 org.elasticsearch.action.support.master.MasterNodeRequest 这个类的ack时间改成了 1.5分钟了！测试下来还是有问题啊！

**Comment by mfussenegger** [comment] 2021-08-02 08:23
12270 shards in a 5 node cluster is too much. Is it possible to reduce the amount? You should try to stay below 1000 shards per node.


Increasing the timeout for MasterNodeRequest is not recommended, as it will affect overall cluster stability negatively.

**Comment by zhangyatao123456** [comment] 2021-08-02 11:21
创建的表太多是不是也会影响， MasterNodeReques请求时间！今天测试了一下insert的时候并没有什么影响！就是修改表结构的时候会有这个超时问题！除了修改shards变小还有什么好的建议吗？

**Comment by jayeff** [comment] 2021-08-02 14:04
Hi @zhangyatao123456,

we suggest to keep the number of shards below 1000 per node. With >6500 per node you clearly exceed this suggested upper limit and you likely will run into different performance and reliability issues unless addressed.

Probably a mixture of increasing your node count and reducing the number of shards would remedy this problem.

Please refer to the [sharding and partitioning guide](https://community.crate.io/t/sharding-and-partitioning-guide-for-time-series-data/737) in out community for some general guidelines regarding sizing of your cluster.

**Comment by zhangyatao123456** [comment] 2021-08-03 01:49
Hi @jayeff
好的我把每台机器的分片降低到 1000一下，在试试看看还有没有这样的问题！非常感谢你的回答！

**Comment by jayeff** [comment] 2021-08-03 12:49
Happy to help. 

Closing this issue for now. Please re-open if you have further questions or post them on https://community.crate.io

**Closed by jayeff** 2021-08-03 12:49 UTC
Labels: support

**Comment by zhangyatao123456** [comment] 2021-08-05 02:24
现在修改分区的时候出现这个
ALTER TABLE s_56.d_695_codes SET (number_of_shards = 1);
ERROR: IllegalStateException: index s_56.d_695_codes must have all shards allocated on the same node to shrink index
出现了这个问题不知道问什么啊！

**Comment by zhangyatao123456** [comment] 2021-08-05 02:30
现在修改分区的时候出现这个
ALTER TABLE s_56.d_695_codes SET (number_of_shards = 1);
ERROR: IllegalStateException: index s_56.d_695_codes must have all shards allocated on the same node to shrink index
出现了这个问题不知道问什么啊！

**Comment by jayeff** [comment] 2021-08-05 07:55
How to decreasing the number of shards is described here: https://crate.io/docs/crate/reference/en/4.6/general/ddl/alter-table.html#decreasing-the-number-of-shards

It's not simple as you first need to allocate all shards on a single node.

A potentially easier alternative could be to to create a secondary table with the lower number of shards and copy the table from the old table to the new table:
`INSERT INTO new_table (columns) (SELECT columns FROM old_table)`
https://crate.io/docs/crate/reference/en/4.6/general/dml.html#inserting-data-by-query
