### ISSUE TITLE
Failed to open output when running COPY TO

### ISSUE THREAD

**Issue by nocturnaltortoise** [crate/crate#6357] opened 2017-10-05 08:54 UTC
CrateDB Version: 2.17

JVM: OpenJDK 1.8.0_131

OS: Ubuntu 16.04.3 LTS Linux 4.4.38-std-1 x86_64

## Problem description:
When attempting to copy a table to JSON, some of the files are created, and one fails, giving this error. 
```SQLActionException[NotSerializableExceptionWrapper: unhandled_server_exception: Failed to open output: '/mnt/data/crate-copies/table_name_2_.json (No such file or directory)']```
If the command is reran, sometimes the same file fails, sometimes a different file fails. Our setup is a three node cluster, all running the same version of cratedb and ubuntu. The table we are attempting to copy has 2.3 million records in it, so it's not expected to be very quick, but other much smaller tables also get the same error. The COPY TO command has been ran on this table before, and succeeded without error, although I think this was before we switched from 2.0.7 to 2.1.7. 

## Steps to reproduce:
```COPY table_name TO DIRECTORY '/mnt/data/crate-copies';```
Where the table_name is any table.

**Comment by andreidan** [comment] 2017-10-09 10:48
@nocturnaltortoise thanks for reporting. Can you please provide the table structure of one of the tables you are reproducing this issue with? (the output of `show create table ... `)

**Comment by joemoe** [comment] 2017-10-11 12:05
@nocturnaltortoise do you have input on @andreidan s question?

**Comment by nocturnaltortoise** [comment] 2017-10-11 14:36
Sorry for the late response. 
The table I was trying to copy JSON from had this output from the ```SHOW CREATE TABLE``` command:

```
CREATE TABLE IF NOT EXISTS "armada"."energy_meter_readings" (
   "energy_exported" FLOAT,
   "energy_exported_cumulative" FLOAT,
   "energy_imported_cumulative" FLOAT,
   "estimated" BOOLEAN,
   "export_reading" BOOLEAN,
   "fit_reading" BOOLEAN,
   "meter_uuid" STRING,
   "timestamp" TIMESTAMP,
   PRIMARY KEY ("timestamp", "meter_uuid")
)
CLUSTERED INTO 4 SHARDS
WITH (
   "blocks.metadata" = false,
   "blocks.read" = false,
   "blocks.read_only" = false,
   "blocks.write" = false,
   column_policy = 'dynamic',
   "mapping.total_fields.limit" = 1000,
   number_of_replicas = '0-1',
   "recovery.initial_shards" = 'quorum',
   refresh_interval = 1000,
   "routing.allocation.enable" = 'all',
   "routing.allocation.total_shards_per_node" = -1,
   "translog.durability" = 'REQUEST',
   "translog.flush_threshold_size" = 536870912,
   "translog.sync_interval" = 5000,
   "unassigned.node_left.delayed_timeout" = 60000,
   "warmer.enabled" = true,
   "write.wait_for_active_shards" = 'all'
)
```
I can't see any errors in /var/log/crate/crate.log

**Comment by seut** [comment] 2017-10-13 09:50
@nocturnaltortoise We still can't reproduce your issue. Can you please double check that this is not a filesystem issue (eg NFS)?
Otherwise we'd really need to see you logs, as the full stacktrace of this error should appear there and hopefully will help to identify the root cause. You could also send me your logs to sebastian@crate.io.

**Comment by nocturnaltortoise** [comment] 2017-10-13 10:36
I'm not quite sure what kind of filesystem issue you mean. I can't see why it would be a filesystem issue now, as the command used to work, and I've tried different directories. The command seems to manage to write some of the JSON files to the specified directory, and then errors. I can send you the log file but there's nothing in there except for ```[WARN ][o.e.d.r.RestController   ] Content type detection for rest requests is deprecated. Specify the content type using the [Content-Type] header.``` I set logger.action.level to TRACE but that doesn't seem to have made any difference. I'm not sure if this is relevant or a different issue, but creating repositories doesn't seem to work either.

**Comment by nocturnaltortoise** [comment] 2017-10-13 10:47
Possibly of importance is that this worked fine in Crate 2.0.7. Also, the drive that I am trying to copy JSON to is a network drive (NBD).

**Comment by seut** [comment] 2017-10-16 09:36
@nocturnaltortoise Thanks for the log, as you already said, they won't show any related information.
Can you please rerun this statement using `crash -v`?
Using the verbose mode, crash will print the full stacktrace.
Also can you please double check that the user crate is running as can successfully write to that directory?
Are there any other files being successfully created/written inside this directory (because you mentioned that it is not always failing on the same file)? 
Thanks a lot.

**Comment by nocturnaltortoise** [comment] 2017-10-16 10:36
Full stack trace from crash -v is: 
```
SQLActionException[NotSerializableExceptionWrapper: unhandled_server_exception: Failed to open output: '/mnt/data/crate-copies/devices_3_.json (No such file or directory)']

SQLActionException: INTERNAL_SERVER_ERROR 5000 NotSerializableExceptionWrapper: unhandled_server_exception: Failed to open output: '/mnt/data/crate-copies/devices_3_.json (No such file or directory)'
       at io.crate.operation.projectors.FileWriterCountCollector.initWriter(FileWriterCountCollector.java:162)
       at io.crate.operation.projectors.FileWriterCountCollector.<init>(FileWriterCountCollector.java:108)
       at io.crate.operation.projectors.FileWriterProjector.apply(FileWriterProjector.java:78)
       at io.crate.operation.projectors.FileWriterProjector.apply(FileWriterProjector.java:34)
       at io.crate.operation.projectors.ProjectingBatchConsumer.accept(ProjectingBatchConsumer.java:98)
       at io.crate.operation.collect.BatchIteratorCollectorBridge$SyncBatchItCollector.doCollect(BatchIteratorCollectorBridge.java:63)
       at io.crate.operation.collect.collectors.CompositeCollector.doCollect(CompositeCollector.java:61)
       at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:569)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
       at java.lang.Thread.run(Thread.java:748)
```
The directory I'm trying to copy to is owned by the crate user, and crate manages to write one or sometimes a few of the json files.

**Comment by seut** [comment] 2017-10-16 12:56
@nocturnaltortoise thx, unfortunately still won't give us any hint what's going wrong.
could you maybe create the files upfront so we can see if we maybe get a more meaningful error then?

**Comment by nocturnaltortoise** [comment] 2017-10-16 13:00
There are already old files from the last time it ran successfully in the directory.

**Comment by seut** [comment] 2017-10-17 10:02
@nocturnaltortoise what file system are you using on your NBD devices?

**Comment by nocturnaltortoise** [comment] 2017-10-17 10:51
ext4

**Comment by seut** [comment] 2017-10-17 12:20
@nocturnaltortoise ok thanks, still trying to reproduce without any success (no errors at all). so each node has it's own NDB fs mounted?

**Comment by nocturnaltortoise** [comment] 2017-10-17 12:41
Yeah, the crate data, snapshot repositories and the directory I was trying to copy data to is also on the same NBD drive. Crate itself is running on a different NBD drive, on the same machine.

**Comment by nocturnaltortoise** [comment] 2017-10-17 13:19
Ahh, we have three machines with separate NBD drives, i.e. they're not sharing. That would explain why I can't create a repository, so you've solved my other issue #6402. Do all the hosts need to be able to read/write to the directory to be able to run COPY TO on one node?

**Comment by seut** [comment] 2017-10-17 13:22
@nocturnaltortoise Yes, all nodes containing at least 1 primary shard of the related table will start writing to that directory.

**Comment by seut** [comment] 2017-10-17 13:32
@nocturnaltortoise Afaik your issue was just about that not all related nodes could access the path used inside you `COPY TO` statement. We will improve our documentation about this requirement asap.
I'm closing this issue now as solved, feel free to open it otherwise.

**Closed by seut** 2017-10-17 13:32 UTC
Labels: feedback_needed
