### ISSUE TITLE
S3 snapshot corrupting large table index

### ISSUE THREAD

**Issue by metase** [crate/crate#9199] opened 2019-10-01 11:03 UTC
**CrateDB version**: 4.0.3

**Environment description**:

**Problem description**:
On a large table (123m rows) s3 snapshot (presumably) causes corruption of said index. This works fine when snapshotting to local file system. The table was recreated to the latest version according to documentation (from cluster failed checks)

**Steps to reproduce**:
run an s3 snapshot on a large table or snapshot the entire system

**Comment by mfussenegger** [comment] 2019-10-01 15:23
We're frequently running s3 snapshots on large tables and haven't seen it cause corruption of an index. We'll need more information to be able to debug this (logs, etc..)

**Comment by mfussenegger** [comment] 2019-10-02 08:21
Some more questions

1) Did this heal itself by recovering from replicas?
2) What state is the cluster in now?
3) Does this deterministically happen each time you attempt to take a snapshot?
4) Were there any other log entries - maybe also in the kernel log related to disk failures or something like that?

**Comment by metase** [comment] 2019-10-02 13:32
1. Yes (after removing corrupted files from directory)
2. Green
3. Only on S3 snapshots
4. No other events that I can see

**Comment by mfussenegger** [comment] 2019-10-07 08:22
Does this also happen on smaller tables, or only on the large one?

Did any nodes drop out of the cluster while you were taking the snapshot?

**Comment by mfussenegger** [comment] 2019-10-17 12:50
Unfortunately we're not able to reproduce this. Have you tried to reproduce this on a fresh installation?

**Comment by metase** [comment] 2019-10-17 14:09
Just. Brand new machine, copied directly from drive (not via adding a node) and upgraded to 4.0.6. Same effect (slightly different set up this time RAID1, but everything else is the same)

**Comment by mfussenegger** [comment] 2019-10-17 14:19
Can you elaborate on what you mean with "copied directly from drive"? 

Copying the data folder on the fs level using `cp` or a similar operation is **not** safe and cause the index corruption.

**Comment by metase** [comment] 2019-10-17 14:36
as in stopped the node and copied the directory with data and bins over to a new server (lift and shift)

**Comment by metase** [comment] 2019-11-02 23:00
so i exported the data to json files and now reimported it to a separate crate installation (4.0.7) and the index corrupted error message appeared again and snapshot was once again only partial. Is there any requirements on disk space or available ram? I can't think of anything else now

**Comment by mfussenegger** [comment] 2019-11-04 14:47
Are you using Amazon S3 or are you by chance using a different S3 provider like [minio](https://min.io)?

We've been able to re-produce this using minio and will investigate further to find the root cause + come up with a fix.

**Comment by metase** [comment] 2019-11-04 15:10
Hiya, no I'm using Amazon S3.

**Comment by mfussenegger** [comment] 2019-11-05 09:41
We finally found the issue and have a [fix](https://github.com/crate/crate/pull/9318) pending which will be released with 4.0.8

**Closed by mfussenegger** 2019-11-05 09:41 UTC
