### ISSUE TITLE
Dropping Performance until Crate is restarted

### ISSUE THREAD

**Issue by slym45** [crate/crate#6069] opened 2017-08-03 08:55 UTC
**CrateDB version**:
crate.noarch                            2.0.6-1                        @crate
crate-release.noarch                    7.0-1                          installed

**JVM version**:
openjdk version "1.8.0_131"
OpenJDK Runtime Environment (build 1.8.0_131-b12)
OpenJDK 64-Bit Server VM (build 25.131-b12, mixed mode)

**OS version / environment description**:
8 CentOS 7 VM's each 8 cores and 500 GB disk, tried 40, 48, 64 GB RAM with heap sizes of 20, 24, 29 GB
Linux 3.10.0-514.26.2.el7.x86_64 #1 SMP Tue Jul 4 15:04:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
Maybe relevant crate config options:
bootstrap.memory_lock : true
gateway.expected_nodes: 8
discovery.zen.minimum_master_nodes: 5
discovery.zen.ping:
  unicast.hosts: (8x)
psql.enabled: true
psql.port: 5432

**Problem description**: 

1. it has nothing to do with access method (postgre wire protocol and crate-pdo both affected).
2. it has nothing to do with on duplicate key update clause in SQL commands,
3. it has nothing to do with primary key (re-created table without primary key),
4. it has nothing to do with number of shards or partition size (when performance went bad, switched to new blank identical table and performance was still bad)
5. when we restart crate-nodes performance is good again
6. when we disable crate insert's for e.g. 10 hours and re-enable crate inserts, performance is still bad.

using crate-pdo we seem to have 100% correct data (full data compare postgresql <-> crate), plus, 
there are NO errors when executing statements, and NO errors in any of the nodes logfiles, which is great (unlike postgre wire protocol where we had missing data but thats another thing...)

BUT performance drops real quick, after only 2-4 days and seems to correlate with crate heap size:
e.g. 
when using 20g heap insert performance is bad after 2 days,
when using 24g heap insert performance is bad after 3 days,
when using 29g heap insert performance is bad after 4 days,...

Output of free-m:
              total        used        free      shared  buff/cache   available
Mem:          40076       21823       11300           9        6952       17644
Swap:          3071           0        3071

Output of ps aux | grep crate (I am including this because of GC switches):
/bin/java -Xms20g -Xmx20g -Djava.awt.headless=true -XX:+UseParNewGC -XX:+UseConcMarkSweepGC -XX:CMSInitiatingOccupancyFraction=75 -XX:+UseCMSInitiatingOccupancyOnly -XX:+DisableExplicitGC -Dfile.encoding=UTF-8 -Djna.nosys=true -Dlog4j.shutdownHookEnabled=false -Dlog4j2.disable.jmx=true -Dlog4j.skipJansi=true -cp /opt/crate/lib/crate-app-2.0.6.jar:/opt/crate/lib/* io.crate.bootstrap.CrateDB -Epath.home=/opt/crate -Epath.home=/opt/crate -Epath.conf=/etc/crate -Epath.logs=/var/log/crate

There is only 1 log entry on all nodes:
[2017-08-03T07:36:41,199][WARN ][i.c.o.c.s.RamAccountingQueue] Memory limit for breaker [jobs_log] was exceeded. Queue [RamAccountingQueue[70bd58c4-718a-4621-abae-2d4dd36b8142]] is cleared.

**Steps to reproduce**:

(Our Test-Cluster hold 714 million total records in lots of test tables and 3 custom schemas,
new table stats after 24 hours test: 736 configured shards (1472 started shards), 5.8 million records, 2.2 gb, replicas = 1)

Create table.
Initial INSERT performance is roughly 20 ms per row in our current test setup.
Run 60 INSERT's per second for 24 hours.
INSERT performance is now 100 ms per row.
Stop insert. Wait 10 hours (just in case GC can not keep up or whatever). Restart insert.
INSERT performance is still at 100 ms per row.
Stop insert. Reboot all crate nodes. Restart insert.
INSERT performance is back to 20 ms per row.

Also see attached CPU usage graph of one node (not master, although I tried to keep INSERT's per second at a constant rate, CPU usage more than doubled!)
![image](https://user-images.githubusercontent.com/30687198/28913707-4699404a-7839-11e7-9266-26511f7a0b4e.png)

Schema:

CREATE TABLE IF NOT EXISTS "doc"."test_table_v21" (
   "col_15" LONG,
   "col_16" SHORT,
   "str_2" STRING,
   "day" BYTE,
   "dif_0" INTEGER,
   "dif_1" INTEGER,
   "dif_10" INTEGER,
   "dif_11" INTEGER,
   "dif_12" INTEGER,
   "dif_13" INTEGER,
   "dif_14" INTEGER,
   "dif_15" INTEGER,
   "dif_16" INTEGER,
   "dif_17" INTEGER,
   "dif_18" INTEGER,
   "dif_19" INTEGER,
   "dif_2" INTEGER,
   "dif_20" INTEGER,
   "dif_21" INTEGER,
   "dif_22" INTEGER,
   "dif_23" INTEGER,
   "dif_3" INTEGER,
   "dif_4" INTEGER,
   "dif_5" INTEGER,
   "dif_6" INTEGER,
   "dif_7" INTEGER,
   "dif_8" INTEGER,
   "dif_9" INTEGER,
   "dif_sum" LONG GENERATED ALWAYS AS ((((((((((((((((((((((("dif_0" + "dif_1") + "dif_2") + "dif_3") + "dif_4") + "dif_5") + "dif_6") + "dif_7") + "dif_8") + "dif_9") + "dif_10") + "dif_11") + "dif_12") + "dif_13") + "dif_14") + "dif_15") + "dif_16") + "dif_17") + "dif_18") + "dif_19") + "dif_20") + "dif_21") + "dif_22") + "dif_23"),
   "col_14" LONG,
   "col_13" INTEGER,
   "col_12" LONG,
   "has_1" BOOLEAN,
   "has_2" BOOLEAN,
   "has_3" BOOLEAN,
   "has_4" BOOLEAN,
   "has_5" BOOLEAN,
   "str_3" STRING,
   "has_6" BOOLEAN,
   "col_4" BYTE,
   "month" BYTE,
   "has_7" BOOLEAN,
   "col_1" LONG,
   "col_3" BYTE,
   "year" SHORT,
   "yearmonth" LONG GENERATED ALWAYS AS (("year" * 100) + "month"),
)
CLUSTERED INTO 8 SHARDS
PARTITIONED BY ("yearmonth")
WITH (
   "blocks.metadata" = false,
   "blocks.read" = false,
   "blocks.read_only" = false,
   "blocks.write" = false,
   column_policy = 'strict',
   number_of_replicas = '1',
   "recovery.initial_shards" = 'quorum',
   refresh_interval = 1000,
   "routing.allocation.enable" = 'all',
   "routing.allocation.total_shards_per_node" = -1,
   "translog.durability" = 'REQUEST',
   "translog.flush_threshold_size" = 536870912,
   "translog.sync_interval" = 5000,
   "unassigned.node_left.delayed_timeout" = 60000,
   "warmer.enabled" = true,
   "write.wait_for_active_shards" = 'all'
)

Might be related to #6053 as well...

**Comment by seut** [comment] 2017-08-04 14:18
@slym45 thanks for reporting, we're investigating this issue, but we cannot reproduce it yet.
If possible, can you maybe try out the latest 2.1 release (2.1.0 atm) to see if it behaves the same? We've done some improvements there related to inserts, so it could be that these are already fixing it.

**Comment by seut** [comment] 2017-08-04 15:50
@slym45 I've just recognized that you've enabled the `stats.enabled` (I've saw that the related CircuitBreaker kicks in). is it maybe possible to disable it and see how it behaves? could be that this is the root cause...

**Comment by seut** [comment] 2017-08-11 11:32
@slym45 We've found a memory leak happening on single inserts. See https://github.com/crate/crate/commit/392572f8d7c5861fee178066c4aa1d73968c076c.
This will be released with the next hotfix release.
If it won't fix this issue, feel free to re-open it.
Thanks for reporting.

**Closed by seut** 2017-08-11 11:32 UTC
