### ISSUE TITLE
order by random() no longer working

### ISSUE THREAD

**Issue by Samuman** [crate/crate#2537] opened 2015-09-08 17:40 UTC
Hey all

"SELECT id FROM my_tbl ORDER BY random() limit 1" used to work fine until I upgraded from 0.47.8 to 0.50.5. Now Im getting following error:

Error!
SQLActionException[Cannot sort by: random() - not part of source symbols]

Is there any alternate way to query random row from table?

Thanks.

**Comment by mfelsche** [comment] 2015-09-08 19:15
thanks for reporting this bug.
i can confirm that the bug does not appear on 0.51.2, maybe you can switch to that version in the meanwhile.

**Comment by mfelsche** [comment] 2015-09-08 19:25
we already have a fix for this bug in our 0.50 branch that will be released with the next 0.50 stable release.

**Comment by mfussenegger** [comment] 2015-09-08 19:28
Just curious, why do you want to sort on random()? This is pretty inefficient. Would be interesting to hear your use-case. 

As Crate doesn't have a natural order (since the data is distributed, you usually get the results in a different order anyway if they're not sorted).

**Comment by Samuman** [comment] 2015-09-09 14:55
Thanks for you response!

Happy to hear that this is fixed.

mfussenegger, if you are really curious:
My project relies on generating new data from existing data that I'm storing. In short term from a single entity you can expand as far as you can handle the amount of data. Since I'm running with limited amount of capacitity, instead of logical approach I wanted more "lets see what happens" approach and start generating content by using any random piece of data on my table. It gives a nice mix.

I tried to select single result from my table but It turns out that its returning constantly same row, not always but often, which is a problem in my use case.

**Comment by mfussenegger** [comment] 2015-10-08 21:54
Closing this as it has been fixed in the 0.50.7 release

**Closed by mfussenegger** 2015-10-08 21:54 UTC
