### ISSUE TITLE
jdbc batch insert error

### ISSUE THREAD

**Issue by cmdares** [crate/crate#7547] opened 2018-07-28 15:41 UTC
table1（id integer），use jdbc execute batch method to insert data，error！
According to my test .The problem is the  field type int.

**Comment by mfussenegger** [comment] 2018-07-28 18:58
Could you please provide some more information?

1) Which version of CrateDB are you using
2) Which version of crate-jdbc are you using
3) Can you provide a sample snippet that triggers the error
4) What is the exact error message?

**Comment by chaudum** [comment] 2018-07-28 20:49
Duplicate of https://github.com/crate/crate-jdbc/issues/284

**Comment by cmdares** [comment] 2018-07-31 15:47
After testing:
3.0.3 release error.
3.1 snapshot ok.

**Comment by chaudum** [comment] 2018-07-31 19:05
@cmdares please provide answers to *all* questions. otherwise we will not be able to provide any help!

**Closed** 2018-08-07 19:38 UTC
Labels: needs feedback
