### ISSUE TITLE
INSERTs sometimes fail with ProcessClusterEventTimeoutException

### ISSUE THREAD

**Issue by rps-v** [crate/crate#6054] opened 2017-08-01 07:30 UTC
**CrateDB version**:
2.0.6

**JVM version**:
openjdk version "1.8.0_131"
OpenJDK Runtime Environment (build 1.8.0_131-8u131-b11-0ubuntu1.16.04.2-b11)
OpenJDK 64-Bit Server VM (build 25.131-b11, mixed mode)

**OS version / environment description**:
Ubuntu 16.04.2 LTS (GNU/Linux 4.4.0-47-generic x86_64)

**Problem description**:

INSERT statements start failing with an exception :

`SQLActionException[ProcessClusterEventTimeoutException: failed to process cluster event (bulk-create-indices) within 30s]`

**Steps to reproduce**:

Maybe related to this exception (during SNAPSHOT) :

`SQLActionException[EsRejectedExecutionException: rejected execution of org.elasticsearch.transport.TcpTransport$RequestHandler@21cc981c on EsThreadPoolExecutor[search, queue capacity = 1000, org.elasticsearch.common.util.concurrent.EsThreadPoolExecutor@4831bd74[Running, pool size = 4, active threads = 4, queued tasks = 1000, completed tasks = 12363269]]]`

This happens on our production cluster of 5 nodes (3 master nodes with 8 core CPU & 64GB RAM, 2 data nodes with 2 core CPU & 8GB RAM).

**Use case**:

**Feature description**:

**Comment by mxm** [comment] 2017-08-02 12:01
Hi @rps-v! Thanks for reporting. 

Could you provide more information about the load of your cluster, e.g. CPU/Memory usage of the nodes? Which nodes handle the incoming requests?

You mentioned that you have 3 master nodes with 8 cores/ 64 GB RAM but only 2 cores / 8 GB Ram for your data nodes. For more efficient execution, you should actually reverse this and give more resources to the data nodes. The dedicated master nodes don't need to have a lot of ram, a few GB are more than enough.

The two exceptions don't seem to be related:

1) Exception: Are you using partitioned tables? This could explain this exception because new partitions will be created on inserts when necessary. However, the underlying issue should be a lack of computing resources.

2) Exception: Your data node can't handle requests in a timely manner. The `search` queue is full which is typically used for normal `Select` statements. This should not be related to snapshotting since it is a simple read operation which is allowed during snapshots. Again, it is probably that the node is too busy with the snapshots and fails to process incoming requests.

If possible, could you provide the following?

- table schema
- configuration files
- logs

Please excuse all the questions but we need more information to find out the root cause of this problem.

**Comment by rps-v** [comment] 2017-08-02 12:31
By master nodes I actually meant data nodes that can also be master (sorry for that 😖).

The load on the cluster is relatively low (~0.6, usually < 1). During snapshots it's between 1 - 2.

All our apps are hosted on one of the 8 core machines and talk to the local Crate node via HTTP. Could this be the source of the exceptions maybe (as the requests are not spread out on the cluster) ?

For the 1st exception, yes, it happens on a partitioned table.

For schema, configuration files and logs can I have an email address, as they are sensitive files ?

Thank you !

**Comment by mxm** [comment] 2017-08-02 13:30
>By master nodes I actually meant data nodes that can also be master (sorry for that 😖).

Ah ok :) 

By cluster load, you probably mean the average load in the cluster. Are there any differences among the nodes?

>All our apps are hosted on one of the 8 core machines and talk to the local Crate node via HTTP. Could this be the source of the exceptions maybe (as the requests are not spread out on the cluster) ?

Not necessarily because queries are distributed and the exceptions indicate that 1) the master is overloaded or 2) the search queue is full which is different from the request queue.

Please email me at schema, config, and logs to max@crate.io. Could you also include the queries you are executing? Thanks.

**Comment by mikethebeer** [comment] 2017-08-04 12:23
@rps-v thanks for sending the logs.
What I immediately see is that you run into a "high disk watermark" (running out of disk space) on node `s3`. This causes a re-routing of shards on other nodes. If the table contains a lot of shards this could lead into some timeouts when continously ingest data. So please ensure that you add more disk space to this node to narrow down the issue (probably its caused because of this).

Can you describe why you do a partitioning by `vehicle_id` and `timestamp`? I have the feeling this combination produces a lot of partitions which then produces a huge amount of shards (since there are 6 shards per partition defined).

This warning messages like 👇  seem to indicate that you are working on an outdated index (table) that has been created before CrateDB 2.0. Although this messages are warnings and not critical it's still strange that those messages occur. We will try to check this.

```
[2017-08-03T02:08:29,478][WARN ][o.e.d.i.m.StringFieldMapper$TypeParser] The [string] field is deprecated, please use [text] or [keyword] instead on [device_sn]
[2017-08-03T02:08:29,479][WARN ][o.e.d.i.m.TypeParsers    ] Expected a boolean for property [index] but got [not_analyzed]
```

**Comment by rps-v** [comment] 2017-08-04 13:03
@mikethebeer thank you for helping us 👍 

Regarding the "high disk watermark", we have 2 folders defined in the config for `path.data` on 2 separate disks. The node ran out of storage space (on folder 1) and we added a second drive (folder 2). Does Crate not use the path with most storage space (in the Admin UI the disk usage seems fine - i.e has lots of space left, also no warnings are reported there) ? If not, how can we move everything on the bigger drive ?

The reasoning was to have a partition for each `vehicle_id` per `month` (computed from the timestamp), as this would presumably increase performance of the queries that we run for reporting (analytics) - because it would query partitions with much less data than if we would have partitioned just on the `vehicle_id` or `month` alone. Was this a wrong choice ? What can we do to improve this ? Do we need to migrate our existing data to a new table that is partitioned differently ?

As for the deprecated warnings, we tried an upgrade to 2.0.4 which failed (see #5923) but then restored everything from a snapshot (made on 1.1.3). Been getting those ever since AFAIK.

**Comment by mikethebeer** [comment] 2017-08-04 13:46
@rps-v did you run `OPTIMIZE TABLE table_ident WITH (upgrade_segments=true);` (this could take some time 🕐 to execute) after upgrading and restoring of the snapshot? This needs to be done a single time when upgrading indices to CrateDB v2.0. This will upgrade the Lucene Segments.

If you define a 2nd data path that points to another disk this should be fine. AFAIK Crate automatically shuffles/routes the shards from one path to another if one disk is full - however a node restart is necessary. So this should be fine then 👍 .

Regarding the partitioning I understand your concept behind it. However, your setup really depends on how many records are stored in each shard/partition. You only gain a performance boost if these shards contain a lot of records. It can get worse if this is not the case and you end up with a lot of shards consuming too many ressources. How many shards does your table have currently?

**Comment by rps-v** [comment] 2017-08-04 13:58
@mikethebeer If I remember correctly, we did run the `OPTIMIZE` queries because there was a warning regrading them in the Admin UI (and also in the 2.0 upgrade notes). Is there a way to find out if it was actually executed (maybe some version query) ? If we run it now, will it solve the deprecation warnings ?

Yes, the node was restarted after the disk and config change.

Currently that table has around 22 milion records, 4GB size, 3800 configured shards, 11400 started shards, 2 replicas.

**Comment by mikethebeer** [comment] 2017-08-04 14:42
@rps-v You can run the `OPTIMIZE` again to ensure that it has been executed.

This is way **too much shards** configured for this cluster. This could definiately be a root cause of the issues you have with the ingest and might be also for the snapshot restore. Going for a montly-only partition is more than enough and should create far less shards. I recommend a change of the schema here because 22 mio. records is not that much. You don't need to be afraid that your queries getting slow here.
In this case you need to create a new table with the schema change and import the data again. [COPY TO](https://crate.io/docs/crate/reference/en/latest/sql/reference/copy_to.html) and [COPY FROM](https://crate.io/docs/crate/reference/en/latest/sql/reference/copy_from.html) will help you to do this quite fast by storing the data temporarly on the file system.

**Comment by rps-v** [comment] 2017-08-04 15:10
@mikethebeer @seut Thanks for the awesome help guys, you deserve a 🍺 !

We will try the suggested schema change to a month-only partition and report back. 🤞

**Comment by rps-v** [comment] 2017-08-10 07:02
@mikethebeer @seut 

We changed the schema, as suggested, and got a 2x performance increase with the shard count being 40 now, from 3000. So far no more `ProcessClusterEventTimeoutException` 👍

However it was not a smooth process, as the old tables refused to be renamed and threw an exception (see below). We had to drop them and rename the new ones - which thankfully worked.
Also, SNAPSHOTs still have PARTIAL state even with way fewer shards. Will try and investigate more if NFS related.

```sql
alter table "some_data" rename to "some_data_old";
```
```
SQLActionException: INTERNAL_SERVER_ERROR 5000 MultiException in io.crate.executor.transport.ChainableActions$Result.addResultAndError(ChainableActions.java:118)
	at io.crate.executor.transport.ChainableActions$Result.addResultAndError(ChainableActions.java:118)
	at java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:822)
	at java.util.concurrent.CompletableFuture.uniHandleStage(CompletableFuture.java:834)
	at java.util.concurrent.CompletableFuture.handle(CompletableFuture.java:2155)
	at io.crate.executor.transport.ChainableActions.rollbackOnErrors(ChainableActions.java:90)
	at io.crate.executor.transport.ChainableActions.lambda$run$1(ChainableActions.java:59)
	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:952)
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:926)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962)
	at io.crate.action.FutureActionListener.onResponse(FutureActionListener.java:45)
	at org.elasticsearch.action.support.TransportAction$1.onResponse(TransportAction.java:91)
	at org.elasticsearch.action.support.TransportAction$1.onResponse(TransportAction.java:87)
	at org.elasticsearch.action.support.TransportAction$ResponseFilterChain.proceed(TransportAction.java:224)
	at org.elasticsearch.action.ingest.IngestActionFilter.apply(IngestActionFilter.java:89)
	at org.elasticsearch.action.support.TransportAction$ResponseFilterChain.proceed(TransportAction.java:222)
	at org.elasticsearch.action.support.TransportAction$FilteredActionListener.onResponse(TransportAction.java:249)
	at org.elasticsearch.action.support.TransportAction$FilteredActionListener.onResponse(TransportAction.java:235)
	at org.elasticsearch.action.support.master.TransportMasterNodeAction$AsyncSingleAction$2.onResponse(TransportMasterNodeAction.java:152)
	at org.elasticsearch.action.support.master.TransportMasterNodeAction$AsyncSingleAction$2.onResponse(TransportMasterNodeAction.java:149)
	at org.elasticsearch.action.admin.indices.open.TransportOpenIndexAction$1.onResponse(TransportOpenIndexAction.java:93)
	at org.elasticsearch.action.admin.indices.open.TransportOpenIndexAction$1.onResponse(TransportOpenIndexAction.java:89)
	at org.elasticsearch.cluster.AckedClusterStateUpdateTask.onAllNodesAcked(AckedClusterStateUpdateTask.java:64)
	at org.elasticsearch.cluster.service.ClusterService$SafeAckedClusterStateTaskListener.onAllNodesAcked(ClusterService.java:874)
	at org.elasticsearch.cluster.service.ClusterService.runTasksForExecutor(ClusterService.java:630)
	at org.elasticsearch.cluster.service.ClusterService$UpdateTask.run(ClusterService.java:915)
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:458)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:238)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:201)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by mikethebeer** [comment] 2017-08-10 07:20
@rps-v really 🆒  thanks for the info. Okay, so this new exception popping up on the `alter table rename` could be a bug on our side. This is a quite new feature of CrateDB and probably a bit flaky when executing against an index with a huge amount of shards.

Would you mind of creating a separate issue including the `alter table` problem that includes the stacktrace and the table info (amount of shards, records,...). This would help us to split non-related issues.

**Comment by seut** [comment] 2017-08-10 07:27
@rps-v @mikethebeer fyi: we already working on making `rename` more resilience (see https://github.com/crate/crate/pull/6098), but I'll check if we can improve the error/stacktrace to get better details on what went wrong.

**Comment by rps-v** [comment] 2017-08-10 07:47
@mikethebeer @seut 

Created separate issue for clarity, see #6099

**Comment by mikethebeer** [comment] 2017-08-10 07:53
@rps-v thanks a lot. Will close this issue now since `ProcessClusterEventTimeoutException` does not occur anymore because the amount of shards has been reduced.

**Closed by mikethebeer** 2017-08-10 07:53 UTC
