### ISSUE TITLE
'Create new JDBC connection' freezes after some connections are created

### ISSUE THREAD

**Issue by shm-dmitry** [crate/crate#9635] opened 2020-02-07 15:56 UTC
**CrateDB version**: 4.0.11

**Problem description**:
I found that method DriverManager::getConnection freezed after some connections to CrateDB are allready created.
Stack trace after freeze:
```
java.net.SocketInputStream.socketRead0(java.io.FileDescriptor, byte[], int, int, int) line: not available [native method]	
java.net.SocketInputStream.socketRead(java.io.FileDescriptor, byte[], int, int, int) line: 115	
java.net.SocketInputStream.read(byte[], int, int, int) line: 168	
java.net.SocketInputStream.read(byte[], int, int) line: 140	
io.crate.shade.org.postgresql.core.VisibleBufferedInputStream.readMore(int) line: 140	
io.crate.shade.org.postgresql.core.VisibleBufferedInputStream.ensureBytes(int) line: 109	
io.crate.shade.org.postgresql.core.VisibleBufferedInputStream.read() line: 67	
io.crate.shade.org.postgresql.core.PGStream.receiveChar() line: 306	
io.crate.shade.org.postgresql.core.v3.ConnectionFactoryImpl.enableSSL(io.crate.shade.org.postgresql.core.PGStream, io.crate.shade.org.postgresql.jdbc.SslMode, java.util.Properties, int) line: 401	
io.crate.shade.org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(java.lang.String, java.lang.String, java.util.Properties, javax.net.SocketFactory, io.crate.shade.org.postgresql.util.HostSpec, io.crate.shade.org.postgresql.jdbc.SslMode) line: 94	
io.crate.shade.org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(io.crate.shade.org.postgresql.util.HostSpec[], java.lang.String, java.lang.String, java.util.Properties) line: 192	
io.crate.shade.org.postgresql.core.ConnectionFactory.openConnection(io.crate.shade.org.postgresql.util.HostSpec[], java.lang.String, java.lang.String, java.util.Properties) line: 49	
io.crate.shade.org.postgresql.jdbc.PgConnection.<init>(io.crate.shade.org.postgresql.util.HostSpec[], java.lang.String, java.lang.String, java.util.Properties, java.lang.String) line: 206	
io.crate.shade.org.postgresql.Driver.makeConnection(java.lang.String, java.util.Properties) line: 442	
io.crate.client.jdbc.CrateDriver(io.crate.shade.org.postgresql.Driver).connect(java.lang.String, java.util.Properties) line: 244	
io.crate.client.jdbc.CrateDriver.connect(java.lang.String, java.util.Properties) line: 65	
java.sql.DriverManager.getConnection(java.lang.String, java.util.Properties, java.lang.Class<?>) line: 677	
java.sql.DriverManager.getConnection(java.lang.String, java.util.Properties) line: 189	
```

In tcpdump I see that client connected to server, sended `Ssl request` postgress packet, but no response reseived from server.
![Screenshot_20200207_184403](https://user-images.githubusercontent.com/19342331/74043092-d3e5b900-49d9-11ea-92ab-26da7590893d.png)

This error reproduced allways. 
But from time to time count of successfully created connections is different (from 3-5 to 25-30).

**Steps to reproduce**:

Execute this java-code:
```
	public static void main(String[] args) throws SQLException {
		var prop = new Properties();
		prop.put("user", "crate");
		prop.put("ssl", "false"); // this flag changes nothing

		for (int i = 0; i < 100; i++) {
			System.err.println("Create connection#" + i);
			DriverManager.getConnection("jdbc:crate://HOSTNAME:5432/", prop);
		}
	}
```

Also, I tryed PG driver (ver 42.2.8), the result is similar.

**Comment by marregui** [comment] 2020-02-07 20:07
Hi @shm-dmitry,

I can successfully open 16311 on both (build.gradle dependencies):  

- implementation 'io.crate:crate-jdbc:2.1.7'
- implementation 'org.postgresql:postgresql:42.2.9'

And then I get the same as you. This points at OS limits.

What are you specifically trying to do?. Note that connections need to be closed at some point:

  ```
public Properties loginProperties() {
        Properties props = new Properties();
        props.put("user", "crate");
        props.put("password", "");
        props.put("ssl", false);
        return props;
    }

   public void testConnection() throws SQLException {
        Connection connection = null;
        try {
            connection = DriverManager.getConnection(/* url */, loginProperties());
            if (false == connection.isValid(10)) {
                throw new SQLException(String.format(
                        Locale.ENGLISH,
                        "connection with %s is not valid (tried for %d secs)",
                        this,
                        10));
            }
        } finally {
            if (null != connection) {
                try {
                    if (false == connection.isClosed()) {
                        connection.close();
                    }
                } catch (SQLException e) {
                    e.printStackTrace();
                }
            }
        }
    }
```

Best regards,

**Comment by shm-dmitry** [comment] 2020-02-10 11:17
Hi, @marregui 

Yes, of course, I always close resources, but this problem was discovered when opening several parallel connections.
I checked today - when I close connection - it also reproduces.
`DriverManager.getConnection("jdbc:postgresql://HOST:5432/", prop).close();`

I checked OS limits:

Max open files near limit, but not critical:
```
root@crate00:/home/d.shmyglev# ls /proc/11423/fd/ | wc -l   
3638
root@crate00:/home/d.shmyglev# cat /proc/11423/limits  | grep process
Max processes             4096                 4096                 processes 
```

I checked opened PSQL connections:
```
root@crate00:/home/d.shmyglev# netstat -nap | grep 11423 | grep 5432 | wc -l
1881
```

It was too large.. I found client machines, opened about 900 connections and restart service.
**But on cratedb host this connections was not closed - they become to CLOSE_WAIT status.**
```
root@crate00:/home/d.shmyglev# netstat -nap | grep 11423 | grep CLOSE_WAIT | wc -l
975
```
I waited about 10-20 minutes, but they does not closed.

After it I restart one cratedb node.
Stop command was processed successfully (4 nodes still work).
After starting the whole cluster became inaccessible.
In logs I see wary many errors like:
```
[2020-02-10T11:06:08,435][INFO ][o.e.i.s.GlobalCheckpointSyncAction] [crate01] [logs.trace_activity][13] global checkpoint sync failed
org.elasticsearch.transport.RemoteTransportException: [crate01][10.12.43.43:4300][indices:admin/seq_no/global_checkpoint_sync[p]]
Caused by: org.elasticsearch.action.UnavailableShardsException: [logs.trace_activity][13] Not enough active copies to meet shard count of [ALL] (have 1, needed 2). Timeout: [1m], request: [GlobalCheckpointSyncAction.Request{shardId=[logs.trace
_activity][13], timeout=1m, index='logs.trace_activity', waitForActiveShards=ALL}]
```

I stop all nodes, wait a few seconds, and then start them - after that the cluster came to life.

After full cluster restart this error does not reproduced.

Open connections have become much less.
And no CLOSE_WAIT-connections now found.
```
root@crate00:/home/d.shmyglev# netstat -nap | grep 24327 | wc -l
231
```

**Comment by marregui** [comment] 2020-02-12 08:51
Hi @shm-dmitry 

CLOSE_WAIT -> local end of connection has received a FIN from the other end, however the OS is waiting for the program (at the local end) to  close its connection.

The problem is your program running on the local machine is not closing the socket. It is not a TCP tuning issue. A connection can (and quite correctly) stay in CLOSE_WAIT forever while the program holds the connection open.

Once the local program closes the socket, the OS can send the FIN to the remote end which transitions you to LAST_ACK while you wait for the ACK of the FIN. Once that is received, the connection is finished and drops from the connection table (if your end is in CLOSE_WAIT you do not end up in the TIME_WAIT state).

I cannot reproduce your issue. Do you have a repo with the code checked in so that I can eye ball it?

Best

**Comment by shm-dmitry** [comment] 2020-02-12 11:16
Hi, @marregui 

I see CLOSE_WAIT connections on host with cratedb server.
And OS wait cratedb to close its connection.

At now all works fine, I monitor this situation.

**Closed** 2020-02-12 11:17 UTC
