### ISSUE TITLE
add feature create view

### ISSUE THREAD

**Issue by cmdares** [crate/crate#6908] opened 2018-02-13 16:33 UTC
create or replace view test2 as select * from test1

SQLActionException[SQLParseException: line 1:8: no viable alternative at input '
create view']

**Comment by mfussenegger** [comment] 2018-02-13 19:48
Views are currently not supported and a feature request for them already exists. Closing this as duplicate of https://github.com/crate/crate/issues/4759

**Closed by mfussenegger** 2018-02-13 19:48 UTC
