### ISSUE TITLE
Ordering the records by results of scalar functions throws an exception

### ISSUE THREAD

**Issue by vladcrisan13** [crate/crate#6957] opened 2018-02-23 06:42 UTC
**CrateDB version**: 2.3.2

**JVM version**: {"version": "1.8.0_131", "vm_name": "OpenJDK 64-Bit Server VM", "vm_vendor": "Oracle Corporation", "vm_version": "25.131-b11"}

**OS version / environment description**:  {"name": "Linux", "arch": "amd64", "version": "3.16.0-4-amd64", "available_processors": 4}

**Problem description**:

Ordering the records by results of scalar functions throws an exception when the query includes [at least] a join and the field used in the scalar function:
- belongs to the primary table of the query, not to the joined one
- is not part of the join conditions

*Stacktrace*:

```
SQLActionException[SQLParseException: Couldn't create executionContexts from
NodeOperations: [2=>NodeOp{ phase{id=2/collect, nodes=[l1UKqZLMTAmPb1wwza7VLg, zMvdSFr0QDSDCHTYclem6Q], dist=BROADCAST}, downstreamNodes=[l1UKqZLMTAmPb1wwza7VLg], downstreamPhase=5, downstreamInputId=1}, 6=>NodeOp{ phase{id=6/fetchPhase, nodes=[l1UKqZLMTAmPb1wwza7VLg, zMvdSFr0QDSDCHTYclem6Q]}, downstreamNodes=[], downstreamPhase=2147483647, downstreamInputId=0}, 1=>NodeOp{ phase{id=1/mergeOnHandler, nodes=[l1UKqZLMTAmPb1wwza7VLg], dist=BROADCAST}, downstreamNodes=[l1UKqZLMTAmPb1wwza7VLg], downstreamPhase=5, downstreamInputId=0}, 0=>NodeOp{ phase{id=0/collect, nodes=[l1UKqZLMTAmPb1wwza7VLg, zMvdSFr0QDSDCHTYclem6Q], dist=BROADCAST}, downstreamNodes=[l1UKqZLMTAmPb1wwza7VLg], downstreamPhase=1, downstreamInputId=0}]
Leafs: [NestedLoopPhase{executionPhaseId=5, name=nested-loop, joinType=INNER, joinCondition=IC{4, string} = IC{1, string}, outputTypes=[string, string, string, string], jobId=8ba755b1-9662-40e3-9232-214593789fb6, executionNodes=[l1UKqZLMTAmPb1wwza7VLg]}]
target-sources: [1=>[0], 5=>[1, 2]]
original-error: UnsupportedOperationException: Can't handle Symbol name]
```

**Steps to reproduce**:
I **highlighted** the differences from one query to another and other relevant parts of the queries. Didn't include the actual results to avoid making this description way too long :).

```
cr> create table a (id string primary key, name string not null);
cr> create table b (id string primary key, name string not null, a_id string not null);
cr> insert into a (id, name) values ('a_id_1', 'a_name_1'), ('a_id_2', 'a_name_2');
cr> insert into b (id, name, a_id) values ('b_id_1', 'b_name_1', 'a_id_2'), ('b_id_2', 'b_name_2', 'a_id_1');

cr> select a_.id as a_id, a_.name as a_name, b_.id as b_id, b_.name as b_name **from a a_** inner join b b_ on a_.id = b_.a_id order by **lower(a_.name)** desc limit 10;
SELECT 2 rows in set (0.005 sec)

cr> select a_.id as a_id, a_.name as a_name, b_.id as b_id, b_.name as b_name **from a a_** inner join b b_ on a_.id = b_.a_id order by **lower(b_.name)** desc limit 10;
SELECT 2 rows in set (0.002 sec)

cr> select a_.id as a_id, a_.name as a_name, b_.id as b_id, b_.name as b_name **from b b_** inner join a a_ on a_.id = b_.a_id order by **lower(a_.name)** desc limit 10;
SELECT 2 rows in set (0.003 sec)

cr> select a_.id as a_id, a_.name as a_name, b_.id as b_id, b_.name as b_name **from b b_** inner join a a_ on a_.id = b_.a_id order by **b_.name** desc limit 10;
SELECT 2 rows in set (0.004 sec)

cr> select a_.id as a_id, a_.name as a_name, b_.id as b_id, b_.name as b_name **from b b_** inner join a a_ on a_.id = b_.a_id order by **lower(b_.name)** desc limit 10;
SQLActionException[SQLParseException: Couldn't create executionContexts from
NodeOperations: [2=>NodeOp{ phase{id=2/collect, nodes=[TTBqmqGhRs6oFKmtdN1OHg, l1UKqZLMTAmPb1wwza7VLg], dist=BROADCAST}, downstreamNodes=[l1UKqZLMTAmPb1wwza7VLg], downstreamPhase=5, downstreamInputId=1}, 1=>NodeOp{ phase{id=1/mergeOnHandler, nodes=[l1UKqZLMTAmPb1wwza7VLg], dist=BROADCAST}, downstreamNodes=[l1UKqZLMTAmPb1wwza7VLg], downstreamPhase=5, downstreamInputId=0}, 6=>NodeOp{ phase{id=6/fetchPhase, nodes=[TTBqmqGhRs6oFKmtdN1OHg, l1UKqZLMTAmPb1wwza7VLg]}, downstreamNodes=[], downstreamPhase=2147483647, downstreamInputId=0}, 0=>NodeOp{ phase{id=0/collect, nodes=[TTBqmqGhRs6oFKmtdN1OHg, l1UKqZLMTAmPb1wwza7VLg], dist=BROADCAST}, downstreamNodes=[l1UKqZLMTAmPb1wwza7VLg], downstreamPhase=1, downstreamInputId=0}]
Leafs: [NestedLoopPhase{executionPhaseId=5, name=nested-loop, joinType=INNER, joinCondition=IC{4, string} = IC{1, string}, outputTypes=[string, string, string, string], jobId=2bf3ff9b-a527-4b24-b7b9-6c09f7426160, executionNodes=[l1UKqZLMTAmPb1wwza7VLg]}]
target-sources: [1=>[0], 5=>[1, 2]]
original-error: UnsupportedOperationException: Can't handle Symbol name]

cr> select a_.id as a_id, a_.name as a_name, b_.id as b_id, b_.name as b_name **from b b_** inner join a a_ on **(a_.id = b_.a_id AND b_.name is not null)** order by **lower(b_.name)** desc limit 10;
SELECT 2 rows in set (0.004 sec)

cr> select a_.id as a_id, a_.name as a_name, b_.id as b_id, b_.name as b_name **from b b_** inner join a a_ on **(a_.id = b_.a_id AND b_.name is not null)** order by **lower(b_.name)**;
SELECT 2 rows in set (0.038 sec)

cr> select a_.id as a_id, a_.name as a_name, b_.id as b_id, b_.name as b_name **from b b_** inner join a a_ on **a_.id = b_.a_id** order by **lower(b_.name)**;
SQLActionException[SQLParseException: Couldn't create executionContexts from
NodeOperations: [2=>NodeOp{ phase{id=2/collect, nodes=[l1UKqZLMTAmPb1wwza7VLg, zMvdSFr0QDSDCHTYclem6Q], dist=BROADCAST}, downstreamNodes=[l1UKqZLMTAmPb1wwza7VLg], downstreamPhase=5, downstreamInputId=1}, 6=>NodeOp{ phase{id=6/fetchPhase, nodes=[l1UKqZLMTAmPb1wwza7VLg, zMvdSFr0QDSDCHTYclem6Q]}, downstreamNodes=[], downstreamPhase=2147483647, downstreamInputId=0}, 1=>NodeOp{ phase{id=1/mergeOnHandler, nodes=[l1UKqZLMTAmPb1wwza7VLg], dist=BROADCAST}, downstreamNodes=[l1UKqZLMTAmPb1wwza7VLg], downstreamPhase=5, downstreamInputId=0}, 0=>NodeOp{ phase{id=0/collect, nodes=[l1UKqZLMTAmPb1wwza7VLg, zMvdSFr0QDSDCHTYclem6Q], dist=BROADCAST}, downstreamNodes=[l1UKqZLMTAmPb1wwza7VLg], downstreamPhase=1, downstreamInputId=0}]
Leafs: [NestedLoopPhase{executionPhaseId=5, name=nested-loop, joinType=INNER, joinCondition=IC{4, string} = IC{1, string}, outputTypes=[string, string, string, string], jobId=8ba755b1-9662-40e3-9232-214593789fb6, executionNodes=[l1UKqZLMTAmPb1wwza7VLg]}]
target-sources: [1=>[0], 5=>[1, 2]]
original-error: UnsupportedOperationException: Can't handle Symbol name]
```

**Comment by chaudum** [comment] 2018-02-23 09:45
Hi @vladcrisan13 thanks for reporting. We're going to have a look.

**Comment by chaudum** [comment] 2018-02-28 07:01
Hi @vladcrisan13 
Sorry for not giving any update over the last few days. The problem is a bit tricky to track down. We have some clues already and hope we can provide a fix soon.
Thanks for your patience.

**Comment by mfussenegger** [comment] 2018-03-02 15:39
We've a fix for this (https://github.com/crate/crate/pull/6988) which will be part of the next 2.3 hotfix release.

Thanks again for reporting the issue.

**Closed by mfussenegger** 2018-03-02 15:39 UTC
Labels: bug, v/2.3
