### ISSUE TITLE
Stream exception when joining with subselect

### ISSUE THREAD

**Issue by nocturnaltortoise** [crate/crate#8214] opened 2019-02-08 10:40 UTC
**CrateDB version**: 3.2.2

**Environment description**:

 - JVM version: 1.8.0_171
 - Kernel: Linux 4.15.0-29-generic
 - Distribution: Ubuntu 16.04

**Problem description**:

This query throws an exception, it didn't in Crate 3.0.6, and I can't see anything wrong with the query.
The exception message is this: ```SQLActionException[IllegalStateException: stream has already been operated on or closed]```
```
SELECT s.site_id, operational_state, active_status_codes
    FROM state_log s JOIN (
        SELECT site_id, MAX(timestamp) AS max_timestamp
        FROM state_log GROUP BY site_id
    ) sq ON sq.site_id = s.site_id AND sq.max_timestamp = s.timestamp
```
This is another query that produces the same error:
```
SELECT d1.site_id, energy_cumulative AS energy_cumulative_previous
    FROM data d1 JOIN (
        SELECT site_id, MAX(timestamp) AS max_timestamp
        FROM data
        WHERE timestamp < {}
        GROUP BY site_id
    ) d2 ON
    d1.site_id = d2.site_id AND d1.timestamp = d2.max_timestamp
```
Rewriting these queries to use a subselect with a concat (i.e. no join) works fine, but I'm not sure why this query broke between 3.0.6 and 3.2.2? At the very least a more informative error message would be good.

**Steps to reproduce**:

Here's the schema for one of the tables:
```
CREATE TABLE IF NOT EXISTS "state_log" (
   "active_status_codes" STRING,
   "duration" FLOAT,
   "operational_state" INTEGER,
   "site_id" INTEGER,
   "timestamp" TIMESTAMP,
   PRIMARY KEY ("timestamp", "site_id")
)
CLUSTERED INTO 6 SHARDS
WITH (
   column_policy = 'dynamic',
   number_of_replicas = '0-1',
   "write.wait_for_active_shards" = 'ALL'
)
```

**Comment by mfussenegger** [comment] 2019-02-08 11:23
Thank you for your report.

Could you run the query in [crash](https://github.com/crate/crash) with `verbose` enabled and then post the stacktrace you should get? To enable `verbose` you can launch `crash` with `--verbose` or toggle it on once inside the repl with `\verbose`.

**Comment by nocturnaltortoise** [comment] 2019-02-08 11:35
Here's the full stacktrace from running the first query with --verbose:
```
SQLActionException[IllegalStateException: stream has already been operated upon or closed]

SQLActionException: 500 Internal Server Error 5000 IllegalStateException: stream has already been operated upon or closed
	at java.util.stream.AbstractPipeline.spliterator(AbstractPipeline.java:343)
	at java.util.stream.ReferencePipeline.iterator(ReferencePipeline.java:139)
	at io.crate.data.CollectingBatchIterator.moveToStart(CollectingBatchIterator.java:112)
	at io.crate.data.CloseAssertingBatchIterator.moveToStart(CloseAssertingBatchIterator.java:49)
	at io.crate.data.MappedForwardingBatchIterator.moveToStart(MappedForwardingBatchIterator.java:37)
	at io.crate.execution.engine.join.HashInnerJoinBatchIterator.moveNext(HashInnerJoinBatchIterator.java:152)
	at io.crate.data.MappedForwardingBatchIterator.moveNext(MappedForwardingBatchIterator.java:42)
	at io.crate.data.MappedForwardingBatchIterator.moveNext(MappedForwardingBatchIterator.java:42)
	at io.crate.data.MappedForwardingBatchIterator.moveNext(MappedForwardingBatchIterator.java:42)
	at io.crate.data.LimitingBatchIterator.moveNext(LimitingBatchIterator.java:60)
	at io.crate.data.AsyncOperationBatchIterator.tryProcessBatchFromLoadedSource(AsyncOperationBatchIterator.java:148)
	at io.crate.data.AsyncOperationBatchIterator.uncheckedLoadNextBatch(AsyncOperationBatchIterator.java:129)
	at io.crate.data.AsyncOperationBatchIterator.lambda$uncheckedLoadNextBatch$0(AsyncOperationBatchIterator.java:134)
	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:952)
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:926)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962)
	at io.crate.data.BatchIterators.collect(BatchIterators.java:75)
	at io.crate.data.BatchIterators.lambda$collect$0(BatchIterators.java:79)
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:760)
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:736)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1595)
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:624)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by mfussenegger** [comment] 2019-02-11 10:14
I'm unfortunately not able to reproduce the issue.

Could you also post the output of 

```
explain SELECT s.site_id, operational_state, active_status_codes
    FROM state_log s JOIN (
        SELECT site_id, MAX(timestamp) AS max_timestamp
        FROM state_log GROUP BY site_id
    ) sq ON sq.site_id = s.site_id AND sq.max_timestamp = s.timestamp;
```

And tell us how many records the `state_log` table has?


I assume you're running this on a cluster with multiple nodes?

**Comment by nocturnaltortoise** [comment] 2019-02-11 12:23
The output of the explain statement is:
```
{"QueryThenFetch": {"fetchPhase": {"FETCH": {"executionNodes": ["Qr0Cjs-bTTqp-a7EBKtdsQ"], "fetchRefs": "Ref{state_log._doc['operational_state'], integer}, Ref{state_log._doc['active_status_codes'], string}", "id": 3, "type": "executionPhase"}}, "subPlan": {"Join": {"joinPhase": {"HASH_JOIN": {"distribution": {"distributedByColumn": 0, "type": "BROADCAST"}, "executionNodes": ["Qr0Cjs-bTTqp-a7EBKtdsQ"], "id": 2, "joinType": "INNER", "projections": [{"outputs": "IC{0, long}, IC{1, integer}, IC{2, timestamp}, IC{3, integer}, IC{4, timestamp}", "type": "Eval"}, {"limit": 10000, "offset": 0, "outputs": "IC{0, long}, IC{1, integer}, IC{2, timestamp}, IC{3, integer}, IC{4, timestamp}", "type": "TopN"}, {"fetchSize": 500000, "outputs": "IC{1, integer}, Fetch{IC{0, long}, Ref{state_log._doc['operational_state'], integer}}, Fetch{IC{0, long}, Ref{state_log._doc['active_status_codes'], string}}", "type": "Fetch"}], "type": "executionPhase"}}, "left": {"Collect": {"collectPhase": {"COLLECT": {"distribution": {"distributedByColumn": 0, "type": "SAME_NODE"}, "executionNodes": ["Qr0Cjs-bTTqp-a7EBKtdsQ"], "id": 0, "routing": {"Qr0Cjs-bTTqp-a7EBKtdsQ": {"state_log": [5, 1, 2, 3, 4, 0]}}, "toCollect": "Ref{state_log._fetchid, long}, Ref{state_log.site_id, integer}, Ref{state_log.timestamp, timestamp}", "type": "executionPhase", "where": "true"}}, "type": "executionPlan"}}, "right": {"Collect": {"collectPhase": {"COLLECT": {"distribution": {"distributedByColumn": 0, "type": "SAME_NODE"}, "executionNodes": ["Qr0Cjs-bTTqp-a7EBKtdsQ"], "id": 1, "projections": [{"aggregations": "Aggregation{max, args=[IC{0, timestamp}]}", "keys": "IC{1, integer}", "type": "HashAggregation"}, {"aggregations": "Aggregation{max, args=[IC{1, timestamp}]}", "keys": "IC{0, integer}", "type": "HashAggregation"}], "routing": {"Qr0Cjs-bTTqp-a7EBKtdsQ": {"state_log": [5, 1, 2, 3, 4, 0]}}, "toCollect": "Ref{state_log.timestamp, timestamp}, Ref{state_log.site_id, integer}", "type": "executionPhase", "where": "true"}}, "type": "executionPlan"}}, "type": "executionPlan"}}, "type": "executionPlan"}}
```
The state_log table has 421,715 records. It's a single node cluster.

**Comment by mfussenegger** [comment] 2019-02-12 08:53
I'm still not able to reproduce this issue.

Does the error occurr each time you try to execute the statement or only sometimes?

Would it be possible to send us the data set? I'm using generated data to try to reproduce it - maybe that is why I'm not running into the error.

**Comment by nocturnaltortoise** [comment] 2019-02-12 10:00
It happens every time the query is ran. I can't send you the data unfortunately, but I don't think there's anything unusual about the values. 

I don't know if this is relevant but the data was originally inserted to a multi node cluster, snapshotted and restored onto this single node. As part of that I altered the replica count for these tables to 0. I'm wondering whether that has something to do with it as when I create a seemingly identical table on this crate node and copy the same data in I can't reproduce the error (but it is definitely still happening with the original table).

**Comment by mkleen** [comment] 2019-02-15 15:31
I am also not able to reproduce this issue.

**Comment by mfussenegger** [comment] 2019-02-21 08:42
Thanks to @andreidan we were finally able to track this down and have a fix for it pending (https://github.com/crate/crate/pull/8268) that will be part of the next 3.2 release.

**Closed by mfussenegger** 2019-02-21 08:42 UTC
Labels: bug
