### ISSUE TITLE
"Cluster is not reachable" but still responding

### ISSUE THREAD

**Issue by tellezb** [crate/crate#4859] opened 2017-02-07 23:57 UTC
**Environment**
Crate 1.0.2
Amazon Linux AMI 2016.09.0.20160923 x86_64 HVM GP2
3 AWS t2.micro nodes
crate.yml:

> cluster.name: OE-CRATE
> node.name: v1.0 | us-west-2c | t2.micro | i-1f2ce4c2
> node.zone: us-west-2c
> path.data: /opt/crate/data
> cluster.routing.allocation.awareness.attributes: zone
> cluster.routing.allocation.awareness.force.zone.values: us-west-2a,us-west-2b,us-west-2c
> gateway.expected_nodes: 3
> gateway.recover_after_nodes: 2
> discovery.zen.minimum_master_nodes: 2
> discovery.zen.ping.multicast.enabled: false
> discovery.type: ec2
> column_policy: strict
> psql.enabled: true

**Symptoms**
The following error is showing in each node's Crate logs every few seconds:

> [2017-02-07 22:02:35,751][WARN ][transport ] [v1.0 | us-west-2c | t2.micro | i-1f2ce4c2] Received response for a request that has timed out, sent [3451ms] ago, timed out [426ms] ago, action [crate/sql/sys/nodes], node [{v1.0 | us-west-2c | t2.micro | i-1f2ce4c2}{ilG0SOMZTs2NEn-g4vSPfQ}{172.31.9.215}{172.31.9.215:4300}{info.extended.type=sigar, zone=us-west-2c, http_address=172.31.9.215:4200}], id [3138422]

The error was first for node us-west-2b. After restarting Crate services on 2b the issue seemed to be resolved. After a few hours the same error started showing up again, but for 2c.

I attempted to look at the cluster via the web admin UI. It reports that the "Cluster is not reachable". Regardless, I am still able to run queries against the cluster and **my application is still functioning**.

![image](https://cloud.githubusercontent.com/assets/7115725/22715130/701fc5cc-ed44-11e6-9578-f511557f6b6e.png)

I enabled the jobs log to look for long running jobs...but no queries from my application even show up in the top 100 longest running queries.

`select ended - started, * from sys.jobs_log order by ended - started desc limit 100;`

![image](https://cloud.githubusercontent.com/assets/7115725/22716335/733e2ba8-ed4a-11e6-8ae9-adfb970abe7b.png)

I also used *dmesg* to look for issues and there is nothing that corresponds.

**Comment by chaudum** [comment] 2017-02-08 14:59
hi @tellezb 
It seems like there is a connectivity issue between the zones.

> Received response for a request that has timed out, sent [3451ms] ago, timed out [426ms] ago

would indicate that.

How did you set up your cluster regarding networking? On what network interface do the nodes talk to each other?

The admin ui reports "Cluster is not reachable" whenever the quorum of nodes is not fulfilled, which means that the two other nodes have dropped out of the cluster. However, this does not reflect what you are saying that your application is still functioning. How is your application connected to CrateDB? This can only be the case, if the other two nodes are still connected with each other forming a 2 node cluster (valid, since you've set `discovery.zen.minimum_master_nodes: 2`).

It is actually very hard to tell what

**Comment by tellezb** [comment] 2017-02-08 15:25
I don't think there's an issue with the network setup. This cluster has been setup for nearly a year now and this is the first time we have started seeing this issue. We updated to 1.0.2 a few weeks ago. There have been no architecture changes for months.

We connect to Crate using jdbc (psql protocol). Each node is in a different AWS availability zone

![image](https://cloud.githubusercontent.com/assets/7115725/22742739/b47dcb78-edcc-11e6-8ec5-619b3cc93956.png)

Yes, I have never seen the Admin UI tell me that the "Cluster is not reachable" unless it truly was not (not enough nodes fulfilled).  When it is in this state I can still run queries via the Admin UI against my data.

The cluster is actually in this state again right now. The Admin UI refreshes every 5 seconds or so ... and it **sometimes** seems to be able to connect to the cluster to list my nodes and report the cluster name (notice the screenshot of Admin UI above doesn't show cluster name). Here's is what the node in question looks like when it is in this state (keep in mind it is not always the same node...yesterday morning it was node b, since then it has been c):
![image](https://cloud.githubusercontent.com/assets/7115725/22743324/b84a6db8-edce-11e6-9cfb-3b3197b9e505.png)
And here's what sys.nodes shows for this node:
![image](https://cloud.githubusercontent.com/assets/7115725/22743402/f2902e18-edce-11e6-95d9-0f70c2bb5e82.png)

Let me know how else I can help!

**Comment by mfussenegger** [comment] 2017-02-08 16:13
From which version did you upgrade from?

In 0.56 we added a timeout to queries on sys.nodes:

```
 - Queries on the `sys.nodes` table will now short circuit in case some nodes
   in the cluster are unresponsive. All columns of the unresponsive nodes will
   contain null values except `id` and `name`.
```

This was added to be able to be able to figure out which nodes are unresponsive.

**Comment by tellezb** [comment] 2017-02-08 16:14
We upgraded from 0.56. The query results that I showed above were pulled today (from version 1.0.2).

**Comment by tellezb** [comment] 2017-02-09 19:15
Update: 

Our cluster has run for a couple of days in this state. As of this morning, the unresponsive node _and_ the master node ran out of EC2 cpu credits. This caused the issue to spiral.

I ended up replacing these 2 nodes and performing a restore of all tables in the database. I also increased the Crate heap size from 45% to 48%. A couple of weeks ago we had lowered it from 50% to 45%.

So far the cluster seems to be healthy and has not started showing the symptoms again.

PLEASE let me know how else I can help with this bug. This is a serious issue! I am glad this was not a production cluster!

**Comment by bputt** [comment] 2017-02-09 21:28
May be related to my issue: https://github.com/crate/crate/issues/4484

**Comment by christianbader** [comment] 2017-02-10 09:20
@tellezb It seems that you have too much shards distributed on your nodes. This causes a very high CPU load on each of your nodes and may lead to the ping timeout issue that you discovered. Can you provide us your configured table-schema to see on which column you partition? The more shards you have, the more CPU it cost.

However, if you have monitoring insights about the cluster metrics before and after the cluster update  it would be nice if you could provide this to us to detect a performance regression.

**Comment by tellezb** [comment] 2017-02-10 16:20
@christianbader Our nodes have been running in this configuration for a year now and we've never had CPU credit issues (or even close).

That being said, you prompted me to look at a history of CPU credits for these nodes. And sure enough, 3 days ago when this odd cluster state first started occurring ... one of my nodes had run completely out of credits. +1 to you! I truly think this was the source of the issue.

That being said ... I think there is still a Crate bug that needs addressed. The cluster was not down and was responsive to jdbc queries, yet the Admin UI would tell me the cluster is not reachable and the logs were filled with timeout errors. The cluster should not be able to have so many issues when a single node is having performance issues...a quorum of the nodes were still functioning fine.

Thoughts?

**Comment by mfussenegger** [comment] 2017-02-12 17:44
>  The cluster was not down and was responsive to jdbc queries, yet the Admin UI would tell me the cluster is not reachable and the logs were filled with timeout errors.

I agree that it's not the best thing to fill up the log with errors, but there aren't that many options to inform operations about potential cluster issues.

Without timeouts and these errors/warnings in the admin-ui a node that is "sometimes" not responsive can be really painful to track down. Especially if you have a larger number of nodes.
Besides that, without a timeout queries on `sys.nodes` would end up taking forever until the faulty node either disconnects or finally responses. This would lock up the admin-ui completely and make it very hard to figure out what's wrong unless you've another dedicated monitoring system in place.

**Comment by tellezb** [comment] 2017-02-15 15:06
I'm not worried about the logs. The entries were useful in helping to identify that there was an issue.

When the one node is having CPU issues (or issues of any sort), and the quorum of the nodes is still available:

1. The Admin UI should still be able to list the nodes which are not having CPU issues in the Cluster tab. (see screenshot from original post)
2. The Admin UI should still be able to show the name of the cluster in the header bar. (see screenshot from original post)

Best case scenario, it seems that Crate should be able to evict a node (after N number of failed healthchecks) to prevent the cluster from degrading as a result of a single bad node.

**Comment by mfussenegger** [comment] 2017-02-15 16:58
Oh my I completely missed that, think I started reading by your second reply and not the initial post.

You're right, the admin-ui should behave exactly the way you described it.
We'll look into that.

**Comment by joemoe** [comment] 2017-02-23 16:31
thanks @tellezb for the valueable input. we will add that to our backlog.

**Comment by DLT1412** [comment] 2017-06-29 09:34
Hi,
Please update more information for this issue.
Our production cluster (1.0.5) has this issue and don't have any clues for deal with that. My batch insert failed randomly with error timeout. Some logs and pictures attached.
`[2017-06-29 16:33:26,243][WARN ][transport                ] [Pic de l'Étendard] Received response for a request that has timed out, sent [3824ms] ago, timed out [824ms] ago, action [crate/sql/sys/nodes], node [{Pic de l'Étendard}{dQe9o7g9Qn6zVgHxiRqWUw}{10.60.43.29}{xxx:4300}{info.extended.type=sigar, http_address=xxx:4200}], id [33768302]`
`[2017-06-29 16:33:29,812][WARN ][transport                ] [Pic de l'Étendard] Received response for a request that has timed out, sent [3672ms] ago, timed out [671ms] ago, action [crate/sql/sys/nodes], node [{Pic de l'Étendard}{dQe9o7g9Qn6zVgHxiRqWUw}{xxx}{xxx:4300}{info.extended.type=sigar, http_address=10.60.43.29:4200}], id [33768340]`

<img width="1094" alt="screen shot 2017-06-29 at 4 30 10 pm" src="https://user-images.githubusercontent.com/8294986/27681136-60a06228-5ce8-11e7-8225-83c979d6746c.png">
<img width="1278" alt="screen shot 2017-06-29 at 4 30 45 pm" src="https://user-images.githubusercontent.com/8294986/27681147-66d69cd4-5ce8-11e7-9420-ad086fb4c50f.png">
<img width="1283" alt="screen shot 2017-06-29 at 4 21 14 pm" src="https://user-images.githubusercontent.com/8294986/27681044-0ce362b6-5ce8-11e7-9d3f-f1bc4778b9e8.png">
<img width="1242" alt="screen shot 2017-06-29 at 4 29 48 pm" src="https://user-images.githubusercontent.com/8294986/27681125-56a13f86-5ce8-11e7-9776-22600a83d172.png">

**Comment by mfussenegger** [comment] 2017-06-30 09:58
@DLT1412 

> My batch insert failed randomly with error timeout

The timeout that has been mentioned here is specific to `select ... from
sys.nodes` queries. Any other queries do *not* timeout.

If a insert statement failed than the client should've received a proper error.
Could you post that instead? The messages in the logs *do not* origin from
insert statements.

But the logs do indicate that either the nodes are overloaded, or that there
are network issues.
Do you have some kind of monitoring to fetch JVM metrics like Heap usage & GC
time? This would help to investigate.

**Comment by joemoe** [comment] 2017-07-04 07:05
hi @DLT1412, can you help us out with further information?

**Comment by DLT1412** [comment] 2017-07-06 17:34
It's hard to explain.
My cluster has 3 nodes with 32GB RAM with 24 cores each. Crate version 1.0.5.
We use cratedb to backend for search log user action to support user from multi product.
Each product has about 10 or more table, partition by day. Data load from Hadoop to cratedb. With batch processing, some job will failed if retry many times. Last week, my cluster was low perfomance because reach max limit open_files_descriptor (not reachable and still respond to query, randomly timeout, fixed when increase it).
Too many partition will affect cluster perfomance? 
<img width="422" alt="screen shot 2017-07-07 at 12 13 39 am" src="https://user-images.githubusercontent.com/8294986/27923603-27bb6be4-62a9-11e7-8144-435522d49d2d.png">
As simple drop and create table take ~ 8s to complete.
Logs in master node:
`2017-07-07 00:11:43,471][INFO ][cluster.metadata         ] [Geißstein] [ttq.reason_mapabc] creating index, cause [api], templates [crate_defaults], shards [1]/[1], mappings [default]
[2017-07-07 00:11:53,879][INFO ][cluster.routing.allocation] [Geißstein] Cluster health status changed from [RED] to [YELLOW] (reason: [shards started [[ttq.reason_mapabc][0]] ...]).
[2017-07-07 00:12:00,170][INFO ][cluster.routing.allocation] [Geißstein] Cluster health status changed from [YELLOW] to [GREEN] (reason: [shards started [[ttq.reason_mapabc][0]] ...]).`

Memory on my cluster still free. Option `indices.store.throttle.max_bytes_per_sec` affect this?
Cluster setting: `{"cluster":{"routing":{"allocation":{"include":{"_id":"","_name":"","_host":"","_ip":""},"node_initial_primaries_recoveries":4,"disk":{"threshold_enabled":true,"watermark":{"low":"85%","high":"90%"}},"balance":{"index":0.5,"threshold":1,"shard":0.45,"primary":0.05},"enable":"all","allow_rebalance":"indices_all_active","cluster_concurrent_rebalance":2,"node_concurrent_recoveries":2,"exclude":{"_id":"","_name":"","_host":"","_ip":""},"require":{"_id":"","_name":"","_host":"","_ip":""}}},"graceful_stop":{"force":false,"reallocate":true,"min_availability":"primaries","timeout":"2h"},"info":{"update":{"interval":"30s"}}},"indices":{"breaker":{"fielddata":{"limit":"60%","overhead":1.03},"request":{"limit":"40%","overhead":1},"query":{"limit":"60%","overhead":1.09}},"recovery":{"retry_delay_network":"5s","concurrent_streams":3,"translog_size":"512kb","retry_delay_state_sync":"500ms","internal_action_timeout":"15m","translog_ops":1000,"compress":true,"internal_action_long_timeout":"30m","file_chunk_size":"512kb","activity_timeout":"15m","max_bytes_per_sec":"40mb"},"store":{"throttle":{"type":"merge","max_bytes_per_sec":"20mb"}}},"stats":{"jobs_log_size":10000,"service.interval":"1h","enabled":true,"operations_log_size":10000},"udc":{"initial_delay":"10m","interval":"1d","enabled":true,"url":"https://udc.crate.io"},"discovery":{"zen":{"minimum_master_nodes":2,"publish_timeout":"30s","ping_timeout":"3s"}},"logger":[],"bulk":{"request_timeout":"1m"},"gateway":{"recover_after_nodes":2,"expected_nodes":3,"recover_after_time":"5m"}}`

Query error don't return only 'No more Servers available, exception from last server: Service Unavailable' when failed. Hard to track this. 

How to get Heap usage/GC time of cratedb?

**Comment by joemoe** [comment] 2017-11-16 11:22
hi @DLT1412, sorry this slipped trough. is this still an issue to you?

**Comment by DLT1412** [comment] 2017-11-16 13:42
Found the root cause is too many shards in each node, then running out of heap mem. I think we can close this issue now and have some docs about that. Ref: https://www.elastic.co/blog/how-many-shards-should-i-have-in-my-elasticsearch-cluster

**Closed** 2018-03-12 12:29 UTC
Labels: enhancement
