### ISSUE TITLE
Numeric type values in `WHERE` loses precision/scale

### ISSUE THREAD

**Issue by jeeminso** [crate/crate#16838] opened 2024-10-21 21:26 UTC
### CrateDB version

5.9, master

### Problem description

```
cr> create table t (a numeric(4,2));
inseCREATE OK, 1 row affected (2.305 sec)
cr> insert into t values (1.11);
INSERT OK, 1 row affected (0.159 sec)
cr> select * from t where a = 1.111;
+------+
|    a |
+------+
| 1.11 |  -- 1.111 seems to be implicitly casted to 1.11 and falsely matches
+------+
SELECT 1 row in set (1.171 sec)
```

We can explicitly cast the literal to numeric as a workaround.
```
cr> select * from t where a = 1.111::numeric;
+---+
| a |
+---+
+---+
SELECT 0 rows in set (0.006 sec)
```

### Steps to Reproduce

Please see the problem description.

### Actual Result

The row containing `1.11` returned.

### Expected Result

Nothing returned.

**Comment by matriv** [comment] 2024-10-22 14:41
Probably relates also to: https://github.com/crate/crate/issues/16478

**Comment by henrikingo** [comment] 2024-10-23 17:05
Isn't this actually the low digit version of #16478? The literal we compare against has more precision than the value from the column. What we do in this case is the same as if you insert too large value (too many digits on the left side). The value is just truncated to NUMERIC(4,2). 
So if we stick to the argument in #1, then this behavior is "by design" for now. If you try to store a NUMERIC that has bigger precision or scale than defined in the schema, behavior is unspecified and undocumented.

**Comment by matriv** [comment] 2024-10-24 08:44
> Probably relates also to: [#16478](https://github.com/crate/crate/issues/16478)

This is not true, this issue ^^ is addressed by: https://github.com/crate/crate/pull/16857

**Comment by jeeminso** [comment] 2024-10-28 22:31
> Isn't this actually the low digit version of https://github.com/crate/crate/issues/16478? The literal we compare against has more precision than the value from the column. What we do in this case is the same as if you insert too large value (too many digits on the left side). The value is just truncated to NUMERIC(4,2).

I think you could also compare this behaviour to how `double` is store in `int` column(i.e. `1.1` is truncate to `1`) and comparisions of `double` and `int`(i.e. `1.1` is not truncated to be equal to `1`). In my opinion it needs to be fixed.

**Closed** 2024-11-06 17:01 UTC
Labels: bug
