### ISSUE TITLE
Forward slash in CREATE REPOSITORY secret_key parameter causes exception

### ISSUE THREAD

**Issue by tellezb** [crate/crate#6325] opened 2017-09-25 16:36 UTC
**Environment**:
Crate 1.0.5
Amazon Linux AMI 2016.09.0.20160923 x86_64 HVM GP2
3 AWS c4.large nodes
CrateDB version 1.0.5

**Problem description**:
Attempting to create a new snapshot repository with a forward slash in the secret_key parameter causes an exception.

Example CREATE REPOSITORY script:
`CREATE REPOSITORY repository_name TYPE s3 WITH (
  bucket='bucket-name', 
  base_path='/repository_path', 
  access_key='A_VALID_ACCESS_KEY', 
  secret_key='9SF9+V7ETk/hTQR/9'
);`

Causes the following exception:
> RepositoryException[[] [repository_name] path [repository_path] is not accessible on master node]; nested: RepositoryVerificationException[[repository_name] path [repository_path] is not accessible on master node]; nested: IOException[Unable to upload object repository_path/tests-ZZ_aT5sRTx2JTpIG7kB1vA/master.dat-temp]; nested: AmazonS3Exception[The request signature we calculated does not match the signature you provided. Check your key and signing method. (Service: Amazon S3; Status Code: 403; Error Code: SignatureDoesNotMatch; Request ID: ECA7F4AE5675C4B7)];

**Comment by joemoe** [comment] 2017-09-25 19:27
hi @tellezb, we'll check that.

**Comment by matriv** [comment] 2017-09-26 09:52
@tellezb 

Cannot reproduce the issue. The `/` in the secret_key is definitely not the issue as I've tried with a couple of secret_keys all of them containing `/`.

Are you sure you have the correct `bucket_name`, `base_path`,  `region`, `endpoint` ?

**Comment by tellezb** [comment] 2017-09-26 15:21
@matriv 

Yes, all of the other properties were correct. We generated and used a new secret_key without modifying any other properties and had success. I assumed it was the `/` that caused the issue ... could it have been the `+`? Those were the only 2 special characters in the secret_key.

**Comment by matriv** [comment] 2017-09-26 15:31
@tellezb Tried now again also with `+` and also with a secret key containing both `+` and `/` and still works. Could be the case that the old access key pair was de-activated?

**Comment by matriv** [comment] 2017-09-27 11:34
@tellezb Closing this, since couldn't be reproduced and generating a new Access/Secret key solved the issue.

**Closed by matriv** 2017-09-27 11:34 UTC
