### ISSUE TITLE
asyncpg cannot work with array values on Crate

### ISSUE THREAD

**Issue by robd003** [crate/crate#17053] opened 2024-11-24 11:05 UTC
### CrateDB version

5.9.3

### CrateDB setup information

1 node, 2gb of ram (just for testing)

install the latest asyncpg (currently 0.30.0)

### Problem description

When working with arrays in asyncpg you can insert data, but querying data leads to a crash.

Is CrateDB returning an incorrect message data type for arrays?

### Steps to Reproduce

```python
import asyncio
import asyncpg
from time import sleep

async def main():
    db_config = {
        "user": "crate",
        "password": "",
        "database": "test_arr",
        "host": "crate",
        "port": 5432
    }
    
    conn = await asyncpg.connect(**db_config)
    print("Connected to the database.")
    try:
        await conn.execute("DROP TABLE IF EXISTS test_arr.example_table;")

        # Create the table with CrateDB-compatible types
        await conn.execute("""
            CREATE TABLE test_arr.example_table (
                id INTEGER,
                name TEXT,
                age INTEGER,
                hobbies ARRAY(TEXT),
                pet_name TEXT
            );""")
        print("Table created successfully.")

        await conn.execute("""INSERT INTO test_arr.example_table (id, name, age, hobbies) VALUES (1, 'Alice', 25, ['reading', 'cycling']);""")
        print("First row inserted successfully.")

        await conn.execute("""INSERT INTO test_arr.example_table (id, name, age, hobbies, pet_name) VALUES (2, 'Bob', 30, ['painting', 'hiking'], 'Farrah Pawcett');""")
        print("Second row inserted successfully.")
        
    except Exception as e:
        print(f"A DB modification error occurred: {e}")


    sleep(1);  # wait for Crate to process rows
    try:
        rows = await conn.fetch("SELECT id, name, pet_name, hobbies, age FROM test_arr.example_table;")
        for row in rows:
            print(dict(row))

    except Exception as e:
        print(f"A query error occurred: {e}")

    await conn.close()
    print("Connection closed.")

asyncio.run(main())
```

### Actual Result

```
A query error occurred: line 1:6: extraneous input 'RECURSIVE' expecting {'AUTHORIZATION', 'TO', 'AT', 'DEALLOCATE', 'ILIKE', 'IGNORE', 'RESPECT', 'FETCH', 'NEXT', 'SUBSTRING', 'POSITION', 'TRIM', 'LEADING', 'TRAILING', 'BOTH', 'TIME', 'ZONE', 'YEAR', 'MONTH', 'DAY', 'HOUR', 'MINUTE', 'SECOND', 'MILLISECOND', 'CURRENT_DATE', 'CURRENT_TIME', 'CURRENT_TIMESTAMP', 'CURRENT_SCHEMA', 'INTERVAL', 'OVER', 'WINDOW', 'PARTITION', 'PROMOTE', 'RANGE', 'ROWS', 'PRECEDING', 'FOLLOWING', 'CURRENT', 'ROW', 'WITHOUT', 'BLOB', 'SWAP', 'GC', 'DANGLING', 'ARTIFACTS', 'DECOMMISSION', 'CLUSTER', 'REPOSITORY', 'SNAPSHOT', 'KILL', 'ONLY', 'OPEN', 'CLOSE', 'RENAME', 'REROUTE', 'MOVE', 'SHARD', 'ALLOCATE', 'REPLICA', 'CANCEL', 'RETRY', 'FAILED', 'BOOLEAN', 'BYTE', 'SHORT', 'INTEGER', 'INT', 'LONG', 'FLOAT', 'DOUBLE', 'PRECISION', 'TIMESTAMP', 'IP', 'CHARACTER', 'VARYING', 'STRING', 'GEO_POINT', 'GEO_SHAPE', 'GLOBAL', 'SESSION', 'LOCAL', 'BEGIN', 'START', 'COMMIT', 'WORK', 'TRANSACTION', 'TRANSACTION_ISOLATION', 'CHARACTERISTICS', 'ISOLATION', 'LEVEL', 'SERIALIZABLE', 'REPEATABLE', 'COMMITTED', 'UNCOMMITTED', 'READ', 'WRITE', 'DEFERRABLE', 'REPLACE', 'LANGUAGE', 'ANALYZE', 'VERBOSE', 'DISCARD', 'PLANS', 'SEQUENCES', 'TEMPORARY', 'TEMP', 'CHECK', 'EXPLAIN', 'FORMAT', 'TYPE', 'TEXT', 'GRAPHVIZ', 'LOGICAL', 'DISTRIBUTED', 'SHOW', 'TABLES', 'SCHEMAS', 'CATALOGS', 'COLUMNS', 'PARTITIONS', 'FUNCTIONS', 'MATERIALIZED', 'VIEW', 'OPTIMIZE', 'REFRESH', 'RESTORE', 'ALIAS', 'SYSTEM', 'BERNOULLI', 'TABLESAMPLE', 'VALUES', 'KEY', 'DUPLICATE', 'CONFLICT', 'DO', 'NOTHING', 'COPY', 'CLUSTERED', 'SHARDS', 'OFF', 'FULLTEXT', 'FILTER', 'PLAIN', 'STORAGE', 'RETURNING', 'DYNAMIC', 'STRICT', 'IGNORED', 'ANALYZER', 'EXTENDS', 'TOKENIZER', 'TOKEN_FILTERS', 'CHAR_FILTERS', 'PARTITIONED', 'PREPARE', 'GENERATED', 'ALWAYS', 'ROLE', 'PRIVILEGES', 'SCHEMA', 'RETURN', 'SUMMARY', 'METADATA', 'PUBLICATION', 'SUBSCRIPTION', 'CONNECTION', 'ENABLE', 'DISABLE', 'DECLARE', 'CURSOR', 'ASENSITIVE', 'INSENSITIVE', 'BINARY', 'NO', 'SCROLL', 'HOLD', 'ABSOLUTE', 'FORWARD', 'BACKWARD', 'RELATIVE', 'PRIOR', 'SERVER', 'FOREIGN', 'DATA', 'WRAPPER', 'OPTIONS', 'MAPPING', 'CASCADE', 'RESTRICT', IDENTIFIER, DIGIT_IDENTIFIER, QUOTED_IDENTIFIER, BACKQUOTED_IDENTIFIER}
```

### Expected Result

```js
{'id': 2, 'name': 'Bob', 'pet_name': 'Farrah Pawcett', 'hobbies': ['painting', 'hiking'], 'age': 30}
{'id': 1, 'name': 'Alice', 'pet_name': None, 'hobbies': ['reading', 'cycling'], 'age': 25}
```

**Comment by robd003** [comment] 2024-11-24 11:09
It looks like this is also a problem for INSERTing values into CrateDB too:

```
await conn.execute("""INSERT INTO test_arr.example_table (id, name, age, hobbies, pet_name) VALUES ($1, $2, $3, $4, $5);""", 2, 'Bob', 30, ['painting', 'hiking'], 'Farrah Pawcett')
```

Results in:
A DB modification error occurred: line 1:6: extraneous input 'RECURSIVE' expecting {'AUTHORIZATION', 'TO', 'AT', 'DEALLOCATE', 'ILIKE', 'IGNORE', 'RESPECT', 'FETCH', 'NEXT', 'SUBSTRING', 'POSITION', 'TRIM', 'LEADING', 'TRAILING', 'BOTH', 'TIME', 'ZONE', 'YEAR', 'MONTH', 'DAY', 'HOUR', 'MINUTE', 'SECOND', 'MILLISECOND', 'CURRENT_DATE', 'CURRENT_TIME', 'CURRENT_TIMESTAMP', 'CURRENT_SCHEMA', 'INTERVAL', 'OVER', 'WINDOW', 'PARTITION', 'PROMOTE', 'RANGE', 'ROWS', 'PRECEDING', 'FOLLOWING', 'CURRENT', 'ROW', 'WITHOUT', 'BLOB', 'SWAP', 'GC', 'DANGLING', 'ARTIFACTS', 'DECOMMISSION', 'CLUSTER', 'REPOSITORY', 'SNAPSHOT', 'KILL', 'ONLY', 'OPEN', 'CLOSE', 'RENAME', 'REROUTE', 'MOVE', 'SHARD', 'ALLOCATE', 'REPLICA', 'CANCEL', 'RETRY', 'FAILED', 'BOOLEAN', 'BYTE', 'SHORT', 'INTEGER', 'INT', 'LONG', 'FLOAT', 'DOUBLE', 'PRECISION', 'TIMESTAMP', 'IP', 'CHARACTER', 'VARYING', 'STRING', 'GEO_POINT', 'GEO_SHAPE', 'GLOBAL', 'SESSION', 'LOCAL', 'BEGIN', 'START', 'COMMIT', 'WORK', 'TRANSACTION', 'TRANSACTION_ISOLATION', 'CHARACTERISTICS', 'ISOLATION', 'LEVEL', 'SERIALIZABLE', 'REPEATABLE', 'COMMITTED', 'UNCOMMITTED', 'READ', 'WRITE', 'DEFERRABLE', 'REPLACE', 'LANGUAGE', 'ANALYZE', 'VERBOSE', 'DISCARD', 'PLANS', 'SEQUENCES', 'TEMPORARY', 'TEMP', 'CHECK', 'EXPLAIN', 'FORMAT', 'TYPE', 'TEXT', 'GRAPHVIZ', 'LOGICAL', 'DISTRIBUTED', 'SHOW', 'TABLES', 'SCHEMAS', 'CATALOGS', 'COLUMNS', 'PARTITIONS', 'FUNCTIONS', 'MATERIALIZED', 'VIEW', 'OPTIMIZE', 'REFRESH', 'RESTORE', 'ALIAS', 'SYSTEM', 'BERNOULLI', 'TABLESAMPLE', 'VALUES', 'KEY', 'DUPLICATE', 'CONFLICT', 'DO', 'NOTHING', 'COPY', 'CLUSTERED', 'SHARDS', 'OFF', 'FULLTEXT', 'FILTER', 'PLAIN', 'STORAGE', 'RETURNING', 'DYNAMIC', 'STRICT', 'IGNORED', 'ANALYZER', 'EXTENDS', 'TOKENIZER', 'TOKEN_FILTERS', 'CHAR_FILTERS', 'PARTITIONED', 'PREPARE', 'GENERATED', 'ALWAYS', 'ROLE', 'PRIVILEGES', 'SCHEMA', 'RETURN', 'SUMMARY', 'METADATA', 'PUBLICATION', 'SUBSCRIPTION', 'CONNECTION', 'ENABLE', 'DISABLE', 'DECLARE', 'CURSOR', 'ASENSITIVE', 'INSENSITIVE', 'BINARY', 'NO', 'SCROLL', 'HOLD', 'ABSOLUTE', 'FORWARD', 'BACKWARD', 'RELATIVE', 'PRIOR', 'SERVER', 'FOREIGN', 'DATA', 'WRAPPER', 'OPTIONS', 'MAPPING', 'CASCADE', 'RESTRICT', IDENTIFIER, DIGIT_IDENTIFIER, QUOTED_IDENTIFIER, BACKQUOTED_IDENTIFIER}
A query error occurred: line 1:6: extraneous input 'RECURSIVE' expecting {'AUTHORIZATION', 'TO', 'AT', 'DEALLOCATE', 'ILIKE', 'IGNORE', 'RESPECT', 'FETCH', 'NEXT', 'SUBSTRING', 'POSITION', 'TRIM', 'LEADING', 'TRAILING', 'BOTH', 'TIME', 'ZONE', 'YEAR', 'MONTH', 'DAY', 'HOUR', 'MINUTE', 'SECOND', 'MILLISECOND', 'CURRENT_DATE', 'CURRENT_TIME', 'CURRENT_TIMESTAMP', 'CURRENT_SCHEMA', 'INTERVAL', 'OVER', 'WINDOW', 'PARTITION', 'PROMOTE', 'RANGE', 'ROWS', 'PRECEDING', 'FOLLOWING', 'CURRENT', 'ROW', 'WITHOUT', 'BLOB', 'SWAP', 'GC', 'DANGLING', 'ARTIFACTS', 'DECOMMISSION', 'CLUSTER', 'REPOSITORY', 'SNAPSHOT', 'KILL', 'ONLY', 'OPEN', 'CLOSE', 'RENAME', 'REROUTE', 'MOVE', 'SHARD', 'ALLOCATE', 'REPLICA', 'CANCEL', 'RETRY', 'FAILED', 'BOOLEAN', 'BYTE', 'SHORT', 'INTEGER', 'INT', 'LONG', 'FLOAT', 'DOUBLE', 'PRECISION', 'TIMESTAMP', 'IP', 'CHARACTER', 'VARYING', 'STRING', 'GEO_POINT', 'GEO_SHAPE', 'GLOBAL', 'SESSION', 'LOCAL', 'BEGIN', 'START', 'COMMIT', 'WORK', 'TRANSACTION', 'TRANSACTION_ISOLATION', 'CHARACTERISTICS', 'ISOLATION', 'LEVEL', 'SERIALIZABLE', 'REPEATABLE', 'COMMITTED', 'UNCOMMITTED', 'READ', 'WRITE', 'DEFERRABLE', 'REPLACE', 'LANGUAGE', 'ANALYZE', 'VERBOSE', 'DISCARD', 'PLANS', 'SEQUENCES', 'TEMPORARY', 'TEMP', 'CHECK', 'EXPLAIN', 'FORMAT', 'TYPE', 'TEXT', 'GRAPHVIZ', 'LOGICAL', 'DISTRIBUTED', 'SHOW', 'TABLES', 'SCHEMAS', 'CATALOGS', 'COLUMNS', 'PARTITIONS', 'FUNCTIONS', 'MATERIALIZED', 'VIEW', 'OPTIMIZE', 'REFRESH', 'RESTORE', 'ALIAS', 'SYSTEM', 'BERNOULLI', 'TABLESAMPLE', 'VALUES', 'KEY', 'DUPLICATE', 'CONFLICT', 'DO', 'NOTHING', 'COPY', 'CLUSTERED', 'SHARDS', 'OFF', 'FULLTEXT', 'FILTER', 'PLAIN', 'STORAGE', 'RETURNING', 'DYNAMIC', 'STRICT', 'IGNORED', 'ANALYZER', 'EXTENDS', 'TOKENIZER', 'TOKEN_FILTERS', 'CHAR_FILTERS', 'PARTITIONED', 'PREPARE', 'GENERATED', 'ALWAYS', 'ROLE', 'PRIVILEGES', 'SCHEMA', 'RETURN', 'SUMMARY', 'METADATA', 'PUBLICATION', 'SUBSCRIPTION', 'CONNECTION', 'ENABLE', 'DISABLE', 'DECLARE', 'CURSOR', 'ASENSITIVE', 'INSENSITIVE', 'BINARY', 'NO', 'SCROLL', 'HOLD', 'ABSOLUTE', 'FORWARD', 'BACKWARD', 'RELATIVE', 'PRIOR', 'SERVER', 'FOREIGN', 'DATA', 'WRAPPER', 'OPTIONS', 'MAPPING', 'CASCADE', 'RESTRICT', IDENTIFIER, DIGIT_IDENTIFIER, QUOTED_IDENTIFIER, BACKQUOTED_IDENTIFIER}

**Comment by robd003** [comment] 2024-11-24 11:11
@amotl any ideas on why this isn't working?

**Comment by amotl** [comment] 2024-11-24 11:39
Hi Robert. Thanks a stack for the report. We will look into it, to investigate the root cause. Hopefully, we can come up with an improvement to this obstacle.

Apparently, it is about the `RECURSIVE` clause of the SQL statement, which CrateDB doesn't understand. Do you have any idea whether this has been introduced just recently, for example with asyncpg 0.30.0? Can you downgrade to a previous version in the meanwhile?

**Comment by proddata** [comment] 2024-11-24 20:02
seems like asyncpg creates the following query:


```sql
WITH RECURSIVE typeinfo_tree(
    oid, ns, name, kind, basetype, elemtype, elemdelim,
    range_subtype, attrtypoids, attrnames, depth)
AS (
    SELECT
        ti.oid, ti.ns, ti.name, ti.kind, ti.basetype,
        ti.elemtype, ti.elemdelim, ti.range_subtype,
        ti.attrtypoids, ti.attrnames, 0
    FROM
            (
        SELECT
            t.oid                           AS oid,
            ns.nspname                      AS ns,
            t.typname                       AS name,
            t.typtype                       AS kind,
            (CASE WHEN t.typtype = 'd' THEN
                (WITH RECURSIVE typebases(oid, depth) AS (
                    SELECT
                        t2.typbasetype      AS oid,
                        0                   AS depth
                    FROM
                        pg_type t2
                    WHERE
                        t2.oid = t.oid

                    UNION ALL

                    SELECT
                        t2.typbasetype      AS oid,
                        tb.depth + 1        AS depth
                    FROM
                        pg_type t2,
                        typebases tb
                    WHERE
                       tb.oid = t2.oid
                       AND t2.typbasetype != 0
               ) SELECT oid FROM typebases ORDER BY depth DESC LIMIT 1)

               ELSE NULL
            END)                            AS basetype,
            t.typelem                       AS elemtype,
            elem_t.typdelim                 AS elemdelim,
            COALESCE(
                range_t.rngsubtype,
                multirange_t.rngsubtype)    AS range_subtype,
            (CASE WHEN t.typtype = 'c' THEN
                (SELECT
                    array_agg(ia.atttypid ORDER BY ia.attnum)
                FROM
                    pg_attribute ia
                    INNER JOIN pg_class c
                        ON (ia.attrelid = c.oid)
                WHERE
                    ia.attnum > 0 AND NOT ia.attisdropped
                    AND c.reltype = t.oid)

                ELSE NULL
            END)                            AS attrtypoids,
            (CASE WHEN t.typtype = 'c' THEN
                (SELECT
                    array_agg(ia.attname::text ORDER BY ia.attnum)
                FROM
                    pg_attribute ia
                    INNER JOIN pg_class c
                        ON (ia.attrelid = c.oid)
                WHERE
                    ia.attnum > 0 AND NOT ia.attisdropped
                    AND c.reltype = t.oid)

                ELSE NULL
            END)                            AS attrnames
        FROM
            pg_catalog.pg_type AS t
            INNER JOIN pg_catalog.pg_namespace ns ON (
                ns.oid = t.typnamespace)
            LEFT JOIN pg_type elem_t ON (
                t.typlen = -1 AND
                t.typelem != 0 AND
                t.typelem = elem_t.oid
            )
            LEFT JOIN pg_range range_t ON (
                t.oid = range_t.rngtypid
            )
            LEFT JOIN pg_range multirange_t ON (
                t.oid = multirange_t.rngmultitypid
            )
    )
 AS ti
    WHERE
        ti.oid = any($1::oid[])

    UNION ALL

    SELECT
        ti.oid, ti.ns, ti.name, ti.kind, ti.basetype,
        ti.elemtype, ti.elemdelim, ti.range_subtype,
        ti.attrtypoids, ti.attrnames, tt.depth + 1
    FROM
            (
        SELECT
            t.oid                           AS oid,
            ns.nspname                      AS ns,
            t.typname                       AS name,
            t.typtype                       AS kind,
            (CASE WHEN t.typtype = 'd' THEN
                (WITH RECURSIVE typebases(oid, depth) AS (
                    SELECT
                        t2.typbasetype      AS oid,
                        0                   AS depth
                    FROM
                        pg_type t2
                    WHERE
                        t2.oid = t.oid

                    UNION ALL

                    SELECT
                        t2.typbasetype      AS oid,
                        tb.depth + 1        AS depth
                    FROM
                        pg_type t2,
                        typebases tb
                    WHERE
                       tb.oid = t2.oid
                       AND t2.typbasetype != 0
               ) SELECT oid FROM typebases ORDER BY depth DESC LIMIT 1)

               ELSE NULL
            END)                            AS basetype,
            t.typelem                       AS elemtype,
            elem_t.typdelim                 AS elemdelim,
            COALESCE(
                range_t.rngsubtype,
                multirange_t.rngsubtype)    AS range_subtype,
            (CASE WHEN t.typtype = 'c' THEN
                (SELECT
                    array_agg(ia.atttypid ORDER BY ia.attnum)
                FROM
                    pg_attribute ia
                    INNER JOIN pg_class c
                        ON (ia.attrelid = c.oid)
                WHERE
                    ia.attnum > 0 AND NOT ia.attisdropped
                    AND c.reltype = t.oid)

                ELSE NULL
            END)                            AS attrtypoids,
            (CASE WHEN t.typtype = 'c' THEN
                (SELECT
                    array_agg(ia.attname::text ORDER BY ia.attnum)
                FROM
                    pg_attribute ia
                    INNER JOIN pg_class c
                        ON (ia.attrelid = c.oid)
                WHERE
                    ia.attnum > 0 AND NOT ia.attisdropped
                    AND c.reltype = t.oid)

                ELSE NULL
            END)                            AS attrnames
        FROM
            pg_catalog.pg_type AS t
            INNER JOIN pg_catalog.pg_namespace ns ON (
                ns.oid = t.typnamespace)
            LEFT JOIN pg_type elem_t ON (
                t.typlen = -1 AND
                t.typelem != 0 AND
                t.typelem = elem_t.oid
            )
            LEFT JOIN pg_range range_t ON (
                t.oid = range_t.rngtypid
            )
            LEFT JOIN pg_range multirange_t ON (
                t.oid = multirange_t.rngmultitypid
            )
    )
 ti,
        typeinfo_tree tt
    WHERE
        (tt.elemtype IS NOT NULL AND ti.oid = tt.elemtype)
        OR (tt.attrtypoids IS NOT NULL AND ti.oid = any(tt.attrtypoids))
        OR (tt.range_subtype IS NOT NULL AND ti.oid = tt.range_subtype)
        OR (tt.basetype IS NOT NULL AND ti.oid = tt.basetype)
)

SELECT DISTINCT
    *,
    basetype::regtype::text AS basetype_name,
    elemtype::regtype::text AS elemtype_name,
    range_subtype::regtype::text AS range_subtype_name
FROM
    typeinfo_tree
ORDER BY
    depth DESC
```

**Comment by amotl** [comment] 2024-11-24 23:56
It looks like this is part of asyncpg for three years already.

- https://github.com/MagicStack/asyncpg/pull/851

**Comment by robd003** [comment] 2024-11-25 08:57
I can see a lot of value adding `RECURSIVE` support to Crate. This would let people do graph / hierarchical calculations in addition to fixing this asyncpg issue.

**Comment by mfussenegger** [comment] 2024-11-25 13:12
Added a comment to https://github.com/crate/crate/issues/12544
Closing this here in favour of ^

**Closed by mfussenegger** 2024-11-25 13:12 UTC
Labels: triage
