### ISSUE TITLE
CircuitBreakingException

### ISSUE THREAD

**Issue by justgig8** [crate/crate#6292] opened 2017-09-14 09:46 UTC
**CrateDB version**: 2.0.7

**JVM version**: openjdk version "1.8.0_131"

**OS version / environment description**: Linux version 4.4.0-93-generic (buildd@lgw01-03) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4) )

**Problem description**: Not getting result of query due to following exception. I have 2.4 million records in the table (and table size is ~430MB).

**Exception occurred**: org.elasticsearch.common.breaker.CircuitBreakingException: [parent] Data too large, data for [<http_request>] would be larger than limit of [4485310054/4.1gb]

**Stacktrace**

```
org.elasticsearch.common.breaker.CircuitBreakingException: [parent] Data too large, data for [<http_request>] would be larger than limit of [4485310054/4.1gb]
        at org.elasticsearch.indices.breaker.HierarchyCircuitBreakerService.checkParentLimit(HierarchyCircuitBreakerService.java:211) ~[crate-app-2.0.7.jar:2.0.7]
        at org.elasticsearch.common.breaker.ChildMemoryCircuitBreaker.addEstimateBytesAndMaybeBreak(ChildMemoryCircuitBreaker.java:128) ~[crate-app-2.0.7.jar:2.0.7]
        at org.elasticsearch.http.HttpServer.dispatchRequest(HttpServer.java:110) [crate-app-2.0.7.jar:2.0.7]
        at org.elasticsearch.http.netty3.Netty3HttpServerTransport.dispatchRequest(Netty3HttpServerTransport.java:490) [crate-app-2.0.7.jar:2.0.7]
        at org.elasticsearch.http.netty3.Netty3HttpRequestHandler.messageReceived(Netty3HttpRequestHandler.java:62) [crate-app-2.0.7.jar:2.0.7]
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) [netty-3.10.6.Final.jar:?]
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [netty-3.10.6.Final.jar:?]
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) [netty-3.10.6.Final.jar:?]
        at org.elasticsearch.http.netty3.pipelining.HttpPipeliningHandler.messageReceived(HttpPipeliningHandler.java:85) [crate-app-2.0.7.jar:2.0.7]
        at org.jboss.netty.channel.SimpleChannelHandler.handleUpstream(SimpleChannelHandler.java:88) [netty-3.10.6.Final.jar:?]
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [netty-3.10.6.Final.jar:?]
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) [netty-3.10.6.Final.jar:?]
        at org.jboss.netty.handler.codec.http.HttpChunkAggregator.messageReceived(HttpChunkAggregator.java:145) [netty-3.10.6.Final.jar:?]
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) [netty-3.10.6.Final.jar:?]
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [netty-3.10.6.Final.jar:?]
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) [netty-3.10.6.Final.jar:?]
        at io.crate.http.netty.HttpBlobHandler.messageReceived(HttpBlobHandler.java:119) [crate-app-2.0.7.jar:2.0.7]
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) [netty-3.10.6.Final.jar:?]
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [netty-3.10.6.Final.jar:?]
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) [netty-3.10.6.Final.jar:?]
        at org.jboss.netty.handler.codec.http.HttpContentDecoder.messageReceived(HttpContentDecoder.java:108) [netty-3.10.6.Final.jar:?]
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) [netty-3.10.6.Final.jar:?]
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [netty-3.10.6.Final.jar:?]
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) [netty-3.10.6.Final.jar:?]
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296) [netty-3.10.6.Final.jar:?]
        at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:459) [netty-3.10.6.Final.jar:?]
        at org.jboss.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:536) [netty-3.10.6.Final.jar:?]
        at org.jboss.netty.handler.codec.replay.ReplayingDecoder.messageReceived(ReplayingDecoder.java:435) [netty-3.10.6.Final.jar:?]
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) [netty-3.10.6.Final.jar:?]
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [netty-3.10.6.Final.jar:?]
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) [netty-3.10.6.Final.jar:?]
        at org.elasticsearch.transport.netty3.Netty3OpenChannelsHandler.handleUpstream(Netty3OpenChannelsHandler.java:81) [crate-app-2.0.7.jar:2.0.7]
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [netty-3.10.6.Final.jar:?]
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559) [netty-3.10.6.Final.jar:?]
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268) [netty-3.10.6.Final.jar:?]
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255) [netty-3.10.6.Final.jar:?]
        at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88) [netty-3.10.6.Final.jar:?]
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108) [netty-3.10.6.Final.jar:?]
        at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337) [netty-3.10.6.Final.jar:?]
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89) [netty-3.10.6.Final.jar:?]
        at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178) [netty-3.10.6.Final.jar:?]
        at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108) [netty-3.10.6.Final.jar:?]
        at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42) [netty-3.10.6.Final.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_131]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_131]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
```

**Steps to reproduce**:

**Table schema**

```sql
CREATE TABLE IF NOT EXISTS "doc"."reporting_engagements" (
   "action_id" SHORT,
   "attempt_id" LONG,
   "channel" STRING,
   "channel_id" STRING,
   "created_at" TIMESTAMP,
   "created_on" TIMESTAMP,
   "custom_obj" OBJECT (DYNAMIC) AS (
      "action_id" STRING,
      "ad_id" INTEGER,
      "coupon_code" STRING,
      "coupon_definition_id" INTEGER,
      "type" STRING
   ),
   "customer_id" STRING,
   "day" TIMESTAMP GENERATED ALWAYS AS CAST(EXTRACT('day_of_year' FROM "created_at") AS timestamp),
   "description" STRING,
   "error_message" STRING,
   "expenditure" DOUBLE,
   "ip_address" IP,
   "metric" STRING,
   "product_id" SHORT,
   "revenue" DOUBLE,
   "variation_id" STRING,
   "vendor_id" SHORT,
   "workflow_id" LONG,
   INDEX "xcustomer_id" USING FULLTEXT ("customer_id") WITH (
      analyzer = 'standard'
   ),
   INDEX "xmetric" USING FULLTEXT ("metric") WITH (
      analyzer = 'standard'
   ),
   INDEX "xchannel" USING FULLTEXT ("channel") WITH (
      analyzer = 'standard'
   )
)
CLUSTERED INTO 4 SHARDS
PARTITIONED BY ("day")
WITH (
   "blocks.metadata" = false,
   "blocks.read" = false,
   "blocks.read_only" = false,
   "blocks.write" = false,
   column_policy = 'dynamic',
   "mapping.total_fields.limit" = 1000,
   number_of_replicas = '0-1',
   "recovery.initial_shards" = 'quorum',
   refresh_interval = 1000,
   "routing.allocation.enable" = 'all',
   "routing.allocation.total_shards_per_node" = -1,
   "translog.durability" = 'REQUEST',
   "translog.flush_threshold_size" = 536870912,
   "translog.sync_interval" = 5000,
   "unassigned.node_left.delayed_timeout" = 60000,
   "warmer.enabled" = true,
   "write.wait_for_active_shards" = 'all'
)
```

**Query (pretty complex) being run **

```sql
select workflow_id,action_id,attempt_id,product_id,
MAX('NA') as offer_id,customer_id,channel,email,Mobile,
MAX(case when metric='attempted' then 'Yes' else 'No' end) as attempted,
MIN(case when metric='attempted' then DATE_FORMAT('%Y-%m-%d %H:%i:%s', 'UTC', created_at ) else 'NA' end) 
as attempt_time,
MAX(case when metric='delivered' then 'Yes' else 'No' end) as delivered,
MIN(case when metric='delivered' then DATE_FORMAT('%Y-%m-%d %H:%i:%s', 'UTC', created_at ) else 'NA' end) 
as delivered_time,
MAX(case when metric='opened' then metric_count else 0 end) as last_opened_count,
MIN(case when metric='opened' then DATE_FORMAT('%Y-%m-%d %H:%i:%s', 'UTC', created_at ) else 'NA' end) 
as open_time,
MAX(case when metric='clicked' then metric_count else 0 end) as last_clicked_count,
MIN(case when metric='clicked' then DATE_FORMAT('%Y-%m-%d %H:%i:%s', 'UTC', created_at ) else 'NA' end) 
as click_time ,
MAX(case when metric='spammed' then 'Yes' else 'No' end) as spammed,
MIN(case when metric='spammed' then DATE_FORMAT('%Y-%m-%d %H:%i:%s', 'UTC', created_at ) else 'NA' end) 
as spam_time ,
MAX(case when metric='unsubscribed' then 'Yes' else 'No' end) as unsubscribed,
MIN(case when metric='unsubscribed' then DATE_FORMAT('%Y-%m-%d %H:%i:%s', 'UTC', created_at ) else 'NA' end) 
as unsubscription_time ,
MAX(case when metric in('attemptfailed','deliveryfailed') then 'Yes' else 'No' end) as failed,
MIN(reason)as failure_reason ,
MIN(case when metric in('attemptfailed','deliveryfailed') then DATE_FORMAT('%Y-%m-%d %H:%i:%s', 'UTC', created_at ) else 'NA' end) 
as failure_time ,
MAX(case when metric='converted' then 'Yes' else 'No' end) as converted,
MIN(case when metric='converted' then DATE_FORMAT('%Y-%m-%d %H:%i:%s', 'UTC', created_at ) else 'NA' end) 
as conversion_update_time,Max('NA') as Zone,MAX('NA') as Region,MAX('NA') as Branch,MAX('NA') as State,MAX('NA') as Country,MAX('NA') as Age,MAX('NA')as Gender,
MAX('NA') as IP_ADDRESS, MAX('NA') as latitude, MAX('NA') as longitude,
MAX('NA') as device,MAX('NA') as manufacturer, MAX('NA') as platform,
MAX('NA') as os,MAX('NA') as broswer, MAX('NA') as browser_engine,MAX('NA') as loc_city,
MAX('NA') as loc_state,MAX('NA') as loc_country
from  
(select workflow_id,product_id,attempt_id,action_id,channel,
MAX(case when channel='email' then channel_id else 'NA' end) as email,
MAX(case when channel='sms' then channel_id else 'NA' end) as Mobile, 
MAX(case when customer_id is null or customer_id ='null' then 'NA' else customer_id end) as customer_id,
metric,count(metric) as metric_count,
MAX(case when description is null or description ='null' then 'NA' else description end) as reason,
Max(created_at)as created_at from reporting_engagements where workflow_id=323 
group by workflow_id,action_id,channel,attempt_id,product_id,metric limit 5000000) s 
group by workflow_id,action_id,customer_id,channel,attempt_id,product_id,email,Mobile order by attempt_id limit 5000000);
```

** Sample records **

```
action_id | attempt_id | channel | channel_id | created_at | created_on | custom_obj | customer_id | day | description | error_message | expenditure | ip_address | metric | product_id | revenue | variation_id | vendor_id | workflow_id
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
7 | 852188 | sms | 99396847058 | 1505389201656 | 1505347200000 | {} | 1000057613 | 257 | null | NULL | 1 | 0.0.0.0 | attempted | 2 | 0 | null | 10 | 318
1 | 852195 | email | jeumzken@apxqlk.com | 1505389201696 | 1505347200000 | {} | 1000057614 | 257 | null | NULL | 1 | 0.0.0.0 | attempted | 2 | 0 | null | 9 | 318
7 | 852190 | sms | 99865321216 | 1505389201658 | 1505347200000 | {} | 1000057608 | 257 | null | NULL | 1 | 0.0.0.0 | attempted | 2 | 0 | null | 10 | 318
1 | 852207 | email | qittmekn@jgbnlq.com | 1505389201736 | 1505347200000 | {} | 1000018013 | 257 | null | NULL | 1 | 0.0.0.0 | attempted | 2 | 0 | null | 9 | 318
1 | 852220 | email | surdnddi@cnjdqs.com | 1505389201799 | 1505347200000 | {} | 1000018028 | 257 | null | NULL | 1 | 0.0.0.0 | attempted | 2 | 0 | null | 9 | 318
```

**Comment by justgig8** [comment] 2017-09-14 09:50
Sometimes the query gives proper result and uses the heap size of around 3.8 GB.
But once the query runs successfully, why isn't the heap freed? If I re run the same query 4-5 times sequentially, this exception (CircuitBreakingException) starts coming. Seems to be some issue with the heap not getting freed. 
Why would this be? Or how can I ensure that heap gets freed after each query?

**Comment by joemoe** [comment] 2017-09-14 09:53
hi @justgig8,

the query is really complex.
can't you add more heap than 4.1 GB?
like 8 GB. to see if it than can be rerun several times.
you only have 300 MB of heap left.

**Comment by justgig8** [comment] 2017-09-14 21:40
Once the CircuitBreakingException comes, the heap usage doesn't reduce. Suppose heap used is 5 GB at that time, it remains close to that. May I know why?

**Comment by andreidan** [comment] 2017-09-19 08:54
Hi @justgig8 can you please try to force a GC run after the CircuitBreakingException occurs? Based on local testing I suspect it might be a case of a slow GC rather than a memory leak. 
If the GC doesn't collect much can you please send me a heap dump?

**Comment by joemoe** [comment] 2017-09-21 13:59
hi @justgig8, can you provide us the information.

**Comment by justgig8** [comment] 2017-09-22 07:06
How to take the heap dump when this exception occurs?

And how can I enable a forced GC run?

**Comment by justgig8** [comment] 2017-09-25 11:05
Can I somehow free all heap space if circuit breaking exception occurs? Or can I restart Crate if this happens?

**Comment by andreidan** [comment] 2017-09-25 12:01
@justgig8 I am able to reproduce this problem locally at the moment and it appears to not be a memory leak but a bug in how we track the loaded bytes that trigger the circuit breaker. 
Until we have a fix for this the only option is to restart Crate.

In case you need to at some point get a heap dump you can use visual tools like jconsole or visualvm  or command line utilities like https://docs.oracle.com/javase/8/docs/technotes/guides/troubleshoot/tooldescr006.html
(see GC. class_histogram)

Both the visual tools and the command line tools support triggering a GC run (the jcmd command line tool has GC.run) but you need to make sure the service runs without -XX:+DisableExplicitGC (do NOT enable explicit GC in production, but only when you're testing/debugging issues).

Will notify you when we have a fix for this issue. Thanks for reporting.

**Comment by andreidan** [comment] 2017-09-26 13:32
@justgig8 The issue is fixed with https://github.com/crate/crate/pull/6324 and will be available with the next hotfix release.

**Closed by andreidan** 2017-09-26 13:32 UTC
Labels: bug
