### ISSUE TITLE
Crashed partition causes other partitions after that to be ignored

### ISSUE THREAD

**Issue by jinxmcg** [crate/crate#4125] opened 2016-09-26 18:51 UTC
Hi, 

**The Issue:**
I have Partitions which I cannot delete the rows from and I think they mess up the other queries, as many of them started to return empty results, even on a simple count. Partitions before a specific day work as expected.

![bug](https://cloud.githubusercontent.com/assets/4436121/18847367/4682dca0-842a-11e6-83c7-7081cc8b61fb.jpg)

`select count(*) from slog where day=1474588800000 limit 100;
`which clearly has 143435364 records returns 0

and any delete

```
delete from slog where day= 1474588800000; 
returns ok but the partition does not disapear

```

```
delete from slog where day= -61788528000000; 
returns ok but the partition does not disapear
```

**All queries return OK no errors, cluster status is OK, but data is missing, it is acting like those partitions are ignored when queried.**

Important: I have 30 partitions before these and they work and return data when queried and they can be deleted, but after a specific day no partition or data can be deleted or queried, though the insert work as you see in the picture, and the total records increasing and new partitions being generated for new records inserted.

**The setup:**
I have the following setup: 10 x servers with Centos 6.5 and Crate version 0.54.9 with a big table of 6bn records with the following structure:

```
 CREATE TABLE slog (
   usertime TIMESTAMP,
   uIP IP,
   user STRING,
   day as date_trunc('day', usertime),
   hour as date_trunc('hour', usertime)
 ) CLUSTERED BY (uid) INTO 20 shards
 PARTITIONED BY (day)
 WITH (number_of_replicas = 0);
//i do not need replicas for the data
```

The data I insert with 
`COPY log FROM /logs/logfile`
logfile is a json generated file. I use this way rather the classic insert as I centralize logs from many servers using syslog-ng into files which are then "COPY log FROM logfile" and have pretty sweet insert performance and I do not need to parse the records.

**I have different hdd partitions for logs and database files on each node**

**Cluster reports everything is OK :)**

_Events that might have triggered this:_
1. The insertion of two wrong records with wrong dates that created the -61788528000000 and 61788528000000 partitions which is clearly the bounds of the date field i guess and these mess up the other partitions after this 2 inserts
2. I remained without space for logs in the logs partition on one node and that node crashed because of that (personally I do not think logs should stop insertion and crash a full cluster and the partitions after that) there was plenty of space in the data partition, inserts that used to take 100ms were hanging in for long time on all the cluster. Fixed the space issue and the restarted cluster status went back to OK with speedy inserts
3. Went over 9bn records and it seems that the heap was almost to the limit on some nodes which again brought down all the cluster. Again, inserts that used to take 100ms were hanging in for long time on all the cluster.  Fixed by deleting 3bn rows (I did not really needed so many days of statistics and decided to clean up). Restarted crate, all back to normal with speedy inserts.

Few days later I noticed that my stats after a specific partition day are 0.

_Sidenote:_ I do not know if the partition day from which all queries return 0 afterwards is in the day of event 2 or 3.

I can provide logs or more info if necessary.
##

**Comment by joemoe** [comment] 2016-09-29 09:55
hey @jinxmcg, thanks for the detailed report we will check this.

**Comment by jinxmcg** [comment] 2016-09-29 14:41
Just an update...I queried delete * from table; because I actually needed to work with the DB. Most of the partitions were deleted except the ones after the partition I was talking about earlier. Then I issued drop table/create table and I could not insert anymore data in the table. and after a cluster restart everything went back to normal.

**Comment by kovrus** [comment] 2016-10-04 14:19
Hi @jinxmcg we have an assumption what might have caused the reported issue, and as well fix for that. Could you please first send us the logs from your nodes at times when the problem has occurred, so we can verify that the assumption is correct and proceed working on it.

**Comment by joemoe** [comment] 2016-10-05 16:54
hi @jinxmcg, are you able to provide us the logs @kovrus asked for? this would really help us.

**Comment by jinxmcg** [comment] 2016-10-10 09:26
hi, 

I could though grep the logs I still have for a specific keywords you are interested in. What should I look for? As you imagine there are a lot of logs...

**Comment by kovrus** [comment] 2016-10-12 08:29
@jinxmcg, it would nice to grep for `org.elasticsearch.action.index` and see, whether you have some exceptions there like index closed, etc.

**Comment by jinxmcg** [comment] 2016-10-25 13:41
@kovrus I grepped logs on the nodes and found no "close" keyword on the same line as `org.elasticsearch.action.index` but i found a lot of:

```
307933: at org.elasticsearch.action.index.TransportIndexAction.shardOperationOnPrimary(TransportIndexAction.java:201)
307939: at org.elasticsearch.action.index.TransportIndexAction.innerExecute(TransportIndexAction.java:136)
307940: at org.elasticsearch.action.index.TransportIndexAction.doExecute(TransportIndexAction.java:114)
307941: at org.elasticsearch.action.index.TransportIndexAction.doExecute(TransportIndexAction.java:63)
307972: at org.elasticsearch.action.index.TransportIndexAction.shardOperationOnPrimary(TransportIndexAction.java:201)
307978: at org.elasticsearch.action.index.TransportIndexAction.innerExecute(TransportIndexAction.java:136)
307979: at org.elasticsearch.action.index.TransportIndexAction.doExecute(TransportIndexAction.java:114)
307980: at org.elasticsearch.action.index.TransportIndexAction.doExecute(TransportIndexAction.java:63)
```

any tips / keywords I might be look for?

**Comment by kovrus** [comment] 2016-11-10 07:45
Hi @jinxmcg, sorry for the late response. The fix for that has been released in `0.56.1`. Would it be possible for you to update your current version to the latest `0.56` stable and see whether the issue still occurs?

**Comment by jinxmcg** [comment] 2016-11-21 11:16
Ok, I updated Crate to 0.56.4
I still have issues with tables not being able to get results from queries after a specific date. Though insert are going fine into those shards.

Should I recreate the table from scratch?

Thanks

**Comment by jinxmcg** [comment] 2016-11-21 12:17
REFRESH TABLE slog PARTITION (day=1479427200000);
SQLActionException[PartitionUnknownException: No partition for table 'doc.slog' with ident '04732d1n74q34dpi60o30c1g' exists]

for a partition that returns 0 though it has rows

**Comment by celaus** [comment] 2016-11-21 12:27
@jinxmcg It looks like something is really broken :/ Re-creating the table is definitely your best option :) This time the originally mentioned partition bug should be gone though :)

**Comment by jinxmcg** [comment] 2016-11-23 21:44
Update:

1. I dumped the needed partitions as backup;
2. Updated Crate software
3. Dropped the table, created table from scratch. 
4. Copy from backup into table.
5. Resumed inserting in DB using COPY FROM.
5. Bug reappeared

I agree my JSON used to COPY FROM might not be all well formatted, but it should not break the database table, right?

So, no results when querying a partition that I see it exists. Get error when trying to refresh that partition or any that is created afterwards. 

`SELECT partition_ident, "values", number_of_shards FROM information_schema.table_partitions WHERE schema_name = 'doc' AND table_name = 'slogs' ORDER BY partition_ident limit 100;`

returns all partitions

`
	
	04130			{"day":0}			20	
	04732d1m6sp38d1o60o30c1g		{"day":1467244800000}		20	
	04732d1m6sq32dpm60o30c1g		{"day":1467417600000}		20	
	04732d1n6gsj6d1k60o30c1g		{"day":1474934400000}		20	
	04732d1n6sojgc1o60o30c1g		{"day":1477180800000}		20	
	04732d1n6sp3cdpi60o30c1g		{"day":1477267200000}		20	
	04732d1n6srjgd9m60o30c1g		{"day":1477785600000}		20	
	04732d1n6ss3echg60o30c1g		{"day":1477872000000}		20	
	04732d1n70o38d1o60o30c1g		{"day":1478044800000}		20	
	04732d1n70sj0e1o60o30c1g		{"day":1478908800000}		20	
	04732d1n70sjid9i60o30c1g		{"day":1478995200000}		20	
	04732d1n74o3gc9m60o30c1g		{"day":1479081600000}		20	
	04732d1n74ojce1g60o30c1g		{"day":1479168000000}		20	
	04732d1n74p3ad1k60o30c1g		{"day":1479254400000}		20	
	04732d1n74pj8c1o60o30c1g		{"day":1479340800000}		20	
	04732d1n74q34dpi60o30c1g		{"day":1479427200000}		20	
	04732d1n74qj2cpm60o30c1g		{"day":1479513600000}		20	
	04732d1n74r30c1g60o30c1g		{"day":1479600000000}		20	
	04732d1n74r3gdhk60o30c1g		{"day":1479686400000}		20	
	04732d1n74rjecho60o30c1g		{"day":1479772800000}		20	
	04732d1n74s3ae9i60o30c1g		{"day":1479859200000}		20	
	0483adpi70p32e1g6gs30c1g60o0		{"day":572821804800000}		20	
	0493ccpl6krj2e1h64o30e1g60o30c0		{"day":63557181100800000}		20

`
note the firsts and the last two partitions (might be there from malformed date)
but also that partition 1479859200000 exists.

`refresh table slogs PARTITION (day=1479859200000);` 
returns
`SQLActionException[PartitionUnknownException: No partition for table 'doc.slogs' with ident '04732d1n74s3ae9i60o30c1g' exists]
`
any idea what I should do next?

**Comment by kovrus** [comment] 2016-11-28 11:02
Hi @jinxmcg, it seems that initial fix does not really fix the problem.
We can kind of reproduce the partition creation from malformed dates, but the behaviour of the refresh, delete, etc. has not been reproduced yet.
Would it be possible somehow to obtain the dataset you inserting into the cluster? So we can reproduce the issue on our side.

**Comment by jinxmcg** [comment] 2016-12-06 08:12
Hi,

I dropped everything and disabled auto column creation (dynamic=>strict) - because of malformed json new columns were appearing too. I do not have the broken inserted data as is real time and it was sent directly to Crate otherwise I would happily share it with you moreover I would pinpoint directly the issue.

For the last week seems stable, no more broken partitions for now. I will keep you posted and comeback with conclusions.

Chris

**Comment by joemoe** [comment] 2016-12-22 14:47
hi @jinxmcg,

i'm closing this issue now. if you recognize anything new feel free to reopen it again.

**Closed by joemoe** 2016-12-22 14:47 UTC
Labels: feedback_needed
