### ISSUE TITLE
Percentile NPE

### ISSUE THREAD

**Issue by bputt** [crate/crate#4606] opened 2016-12-15 21:33 UTC
**CrateDB version**: 1.0.1

**JVM version**: 1.8

**OS version / environment description**: Centos 7

**Problem description**:

When executing a percentile query, sometimes I would get the results, but other times I would get an NPE.

```
SQLActionException: INTERNAL_SERVER_ERROR 5000 NullPointerException in io.crate.types.DataTypes.fromStream(DataTypes.java:182)
```

```
SELECT PERCENTILE(someColumn, 0.95) FROM someTable;
```

**Steps to reproduce**:

Running the SQL statement above via the Crate UI (console) and hitting execute. Sometimes the query would succeed, sometimes it would not.

**Comment by seut** [comment] 2016-12-16 15:42
We're not able to reproduce this issue. 
Could it be that you're running nodes with different versions in the same cluster? Do you changed the cluster (size, settings, etc) somehow while running into the NPE compared to a successful query?

**Comment by bputt** [comment] 2016-12-16 16:24
It appears one node in our cluster is throwing the error. It's the same version as all of the other nodes 1.0.1.

The log ouputs:

```
[ERROR][io.crate.types.DataTypes] 5120 is missing in TYPE_REGISTRY
java.lang.NullPointerException
at io.crate.types.DataTypes.fromStream(DataTypes.java:182)
...
```

**Comment by seut** [comment] 2016-12-19 10:46
can you please provide us the output of `select version, os_info from sys.nodes;` ?
also the complete stacktrace would be helpful.
what client are you using?
thanks a lot.

**Comment by bputt** [comment] 2016-12-19 15:35
We're using the crate HTTP endpoint to execute queries at the moment.

JVM Version: 1.8.0_92
VM Version: 25.92-b14

All nodes say Crate 1.0.1

Stacktrace:
```
[ERROR][io.crate.types.DataTypes] 5120 is missing in TYPE_REGISTRY
java.lang.NullPointerException
at io.crate.types.DataTypes.fromStream(DataTypes.java:182)
at io.crate.planner.node.dql.AbstractProjectionsPhase.readFrom(AbstractProjectionsPhase.java:128)
at io.crate.planner.node.dql.RoutedCollectPhase.readFrom(RoutedCollectPhase.java:228)
at io.crate.planner.node.ExecutionPhases.fromStream(ExecutionPhases.java:53)
at io.crate.operation.NodeOperation.readFrom(NodeOperation.java:115)
at io.crate.operation.NodeOperation.<init>(NodeOperation.java:62)
at io.crate.action.job.JobRequest.readFrom(JobRequest.java:71)
at org.elasticsearch.transport.netty.MessageChannelHandler.handleRequest(MessageChannelHandler.java:222)
at org.elasticsearch.transport.netty.MessageChannelHandler.messageReceived(MessageChannelHandler.java:116)
at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268)
at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255)
at org.jboss.netty.channel.socket.nio.NiWorker.read(NioWorker.java:88)
at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
```

**Comment by seut** [comment] 2017-01-02 13:03
Does this issue still occur? If so, does it always occur on the same node?
We still aren't able to reproduce this, maybe you can provide us some more information (steps) to reproduce? 
Also the complete output of this query would be really nice ``select version, os_info from sys.nodes;``

**Comment by bmwmaestoso** [comment] 2017-01-05 22:16
I am also getting the same error but it occurs every time. I created a simple table and everything worked just fine. The table that is failing only has 2k entries and eventually will be > 160M. It has 23 fields, composed of 2 long, 5 timestamp and the rest are string.

I cannot cut/paste from the source system but here is the output from "select version, os_info from sys.nodes". User bputt works in the same place and his info is probably the same. There are 4 entries, I assume for each host in the cluster, that are all the same:
{"version": {"build_snapshot": false, "number": "1.0.1", "build_hash": "227 ...3c4"},
"os_info": {"version": "3.10.0-327.36.3.e17.x86_64", "arch": "amd64", "name": Linux", "jvm": {"vm_name": "OpenJDK 64-Bit Server VM", "version": "1.8.0.111", "vm_version": "25.111-b15", "vm_vendor": "Oracle Corporation"}, "available_processors": 8}}

**Comment by seut** [comment] 2017-01-06 10:22
@bmwmaestoso @bputt thanks for your reply, we could reproduce it now and will have a look.

**Comment by seut** [comment] 2017-01-06 11:41
@bputt @bmwmaestoso we've fixed it by https://github.com/crate/crate/commit/c6f5a8940e6d862061affad36ab2ed7421fd0f83. it will be released with the next 1.0.2 hotfix release. thanks for reporting (and being patient ;-).

**Closed by seut** 2017-01-06 11:41 UTC
Labels: feedback_needed

**Comment by seut** [comment] 2017-01-06 13:08
@bmwmaestoso @bputt forgot to mention: as this bug is class loading issue, you could workaround it by sending a percentile containing statement once to every running node inside the cluster. every node which is handling the client request will load the required class. afterwards a percentile statement should work everywhere.

**Comment by bmwmaestoso** [comment] 2017-01-06 15:52
thanks, i got it working
