### ISSUE TITLE
Unexpected result when comparing `FLOAT` in a partitioned table

### ISSUE THREAD

**Issue by suyZhong** [crate/crate#16705] opened 2024-10-03 08:39 UTC
### CrateDB version

CrateDB 5.9.0-SNAPSHOT built ad6029c

### CrateDB setup information

Manual build following the instructions here: https://github.com/crate/crate/blob/master/devs/docs/basics.rst

### Problem description

Consider the following test case. The third query is unexpected since the second query returns `1.2`, and the negation of the filter expression should thus be evaluated to `FALSE`. Besides, directly select the condition also shows an unexpected `FALSE`. 

### Steps to Reproduce

```sql
DROP TABLE IF EXISTS t0;

CREATE  TABLE  t0(c0 FLOAT, PRIMARY KEY(c0)) PARTITIONED BY (c0);
INSERT INTO t0(c0) VALUES (1.2);
REFRESH TABLE t0;

SELECT * FROM t0; -- 1.2
SELECT * FROM t0 WHERE t0.c0=1.2; -- 1.2
SELECT * FROM t0 WHERE (NOT t0.c0=1.2); -- 1.2 (unexpected)

SELECT t0.c0=1.2 FROM t0; -- FALSE (unexpected)
```

### Actual Result

as mentioned above

### Expected Result

as mentioned above

**Comment by jeeminso** [comment] 2024-10-04 00:08
Thank you for reporting @suyZhong. The unexpected results are caused by the precision differences in `float` and `double`. A workaround is to explicitly casting to float, i.e. `1.2::float`.

This is related to https://github.com/crate/crate/pull/16623. You can notice similar results from Postgres as well, https://www.db-fiddle.com/f/ayNeL9T4FxtmmA75Fp4f8s/0 hence I do not think this is a bug. Could you please share your thoughts as well @matriv ?

**Comment by matriv** [comment] 2024-10-04 06:17
I agree, since we follow Postgres behavior, and in this case the decimal literals without specific type are considered by default `double`, I agree to close the issue, since there is a workaround, by properly casting the literal to `float`.

**Closed by matriv** 2024-10-04 06:17 UTC
Labels: triage
