### ISSUE TITLE
Aliasing column to `"CHAR"` does not work, while it works for all other reserved words

### ISSUE THREAD

**Issue by amotl** [crate/crate#17108] opened 2024-12-07 15:42 UTC
### CrateDB version

Nightly

### CrateDB setup information

Docker standard.

### Problem description

It looks like "CHAR" is a very special keyword, as it can't be used as an alias for column names, while many other potentially reserved words work well as column aliases.

### Steps to Reproduce

```sql
SELECT 'foo' AS "CHAR";
```

### Actual Result

```
cr> SELECT 'foo' AS "CHAR";
SQLParseException[line 1:17: no viable alternative at input 'SELECT 'foo' AS "CHAR"']
```

### Expected Result

It works for many other potentially reserved words, just not for `char`/`CHAR`.

```
cr> SELECT 'foo' AS "TABLE";
+-------+
| TABLE |
+-------+
| foo   |
+-------+
SELECT 1 row in set (0.001 sec)
```
```
cr> SELECT 'foo' AS "INT";
+-----+
| INT |
+-----+
| foo |
+-----+
SELECT 1 row in set (0.001 sec)
```
```
cr> SELECT 'foo' AS "GEO_POINT";
+-----------+
| GEO_POINT |
+-----------+
| foo       |
+-----------+
SELECT 1 row in set (0.001 sec)
```

**Comment by mfussenegger** [comment] 2024-12-09 10:14
This is a side effect of `"` being part of the type name. It's `"CHAR"` not `CHAR`.

https://github.com/crate/crate/blob/46cefb218a07abce5cbaa0cc120a71c0847984ce/libs/sql-parser/src/main/antlr/io/crate/sql/parser/antlr/SqlBaseLexer.g4#L177


Unless this causes some compatibility issues I'd close this as working as intended

**Comment by amotl** [comment] 2024-12-09 11:40
Hi. I've submitted a draft patch, which demonstrates the problem per GHA workflow run over here.

- PR: https://github.com/crate/cratedb-examples/pull/767
- CI: [cratedb-examples, run #12234558808](https://github.com/crate/cratedb-examples/actions/runs/12234558808/job/34124004513?pr=767#step:6:193)

## Evaluation
The problem is likely originating at [SQLFrame](https://github.com/eakmanrq/sqlframe) or [SQLGlot](https://github.com/tobymao/sqlglot), where I am preparing two little adapters to, both deriving from their PostgreSQL dialect adapters (not published yet, will add links to patches here). Personally, for this very test case at hand (https://github.com/crate/cratedb-examples/pull/765), I can easily continue using a different column name that works well, as I did by using `character`.

However, it is not guaranteed that others will do the same, possibly in a different constellation, using pure SQL, or any other framework which does similar things.

If you can demonstrate a workaround, I can check if the dialect implementation in SQLGlot or SQLFrame can be adjusted. As a client-side programmer to CrateDB, how would I treat "aliasing to `char`" differently? Just make sure it is a special keyword in the regard that it should explicitly NOT be quoted, like `SELECT 42 AS char;` works perfectly well? That would kind of contradict a catch-all measure to "always quote", which some dialects apply, and apparently SQLFrame/SQLGlot as well. I mean, it is in general not the worst assumption for a dialect to make, right?

Please kindly advise, or close the ticket if you think it's too much of a spurious and synthetic case I am making up here. If so, we should at least outline this special case somewhere within the documentation?

**Closed** 2024-12-09 13:18 UTC
Labels: needs info or feedback

**Comment by seut** [comment] 2024-12-09 13:19
@amotl Thanks for reporting. It's solved by #17113, will be available with the next nightly or `5.10.x`.

**Comment by amotl** [comment] 2024-12-09 14:58
Sweet. Thanks for the quick fix.

**Comment by amotl** [comment] 2024-12-10 19:07
After your improvement trickled down into a nightly release, validating the relevant change succeeds now. Thanks!

- https://github.com/crate/cratedb-examples/pull/767
- https://github.com/crate/cratedb-examples/actions/runs/12234558808
