### ISSUE TITLE
io.crate.integrationtests.LuceneQueryBuilderIntegrationTest#testNullOperators

### ISSUE THREAD

**Issue by matriv** [crate/crate#16519] opened 2024-08-21 10:07 UTC
Fails consistently with:
```
REPRODUCE WITH: ./mvnw -pl server test -Dtest=io.crate.integrationtests.LuceneQueryBuilderIntegrationTest -Dtests.method=testNullOperators -Dtests.seed=FBAF698F31CAA4EF -Dtests.locale=sv-Latn-SE -Dtests.timezone=Canada/Mountain
```
(Just the seed is enough to reproduce)

```
Expecting actual:
  [-2L, -2L, 1L]
to contain exactly (and in same order):
  [1L, 1L, 1L]
but some elements were not found:
  [1L, 1L]
and others were not expected:
  [-2L, -2L]

    at __randomizedtesting.SeedInfo.seed([FBAF698F31CAA4EF:51D7754B679854A6]:0)
    at io.crate.integrationtests.LuceneQueryBuilderIntegrationTest.testNullOperators(LuceneQueryBuilderIntegrationTest.java:361)
    at java.base/java.lang.reflect.Method.invoke(Method.java:580)
    at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
    at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
    at java.base/java.lang.Thread.run(Thread.java:1570)
```

**Comment by mfussenegger** [comment] 2024-08-21 12:42
Was this with https://github.com/crate/crate/pull/16511 included? I can't reproduce the failure with the given seed.

**Comment by matriv** [comment] 2024-08-21 13:06
I had updated master for sure (to get my PR ready to be merged) and I had `DYNAMIC` policy in the code, but probably had some stale build locally. Indeed, after rebuilding everything (including the https://github.com/crate/crate/pull/16511) I cannot reproduce it anymore, closing.

Thx and sorry for the noise.

**Comment by BaurzhanSakhariev** [comment] 2024-08-29 11:58
Failure from 29.08

https://wacklig.pipifein.dev/github/crate/crate/a8d26a78-806a-46c2-9eeb-c014a883f7aa/f9b401eb-1810-41d1-9295-fee725ee8e3a

```
org.opentest4j.AssertionFailedError: 

Expecting actual:
  [1L, -2L, 1L]
to contain exactly (and in same order):
  [1L, 1L, 1L]
but some elements were not found:
  [1L]
and others were not expected:
  [-2L]

	at __randomizedtesting.SeedInfo.seed([4C154FE032C88BF8:E66D5324649A7BB1]:0)
	at io.crate.integrationtests.LuceneQueryBuilderIntegrationTest.testNullOperators(LuceneQueryBuilderIntegrationTest.java:361)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
```

**Comment by mfussenegger** [comment] 2024-09-02 12:05
Hopefully fixed with https://github.com/crate/crate/pull/16557 - but can't tell for sure as I wasn't able to reproduce the failure. Closing this anyway for now, we'll notice if it's still broken

**Closed by mfussenegger** 2024-09-02 12:05 UTC
Labels: test-failure

**Comment by matriv** [comment] 2024-09-02 12:53
I was able to reproduce it beforehand, locally, with the seed: `4C154FE032C88BF8`, but not anymore.
