### ISSUE TITLE
Query against partitions / shards unresponsive due to missing shards

### ISSUE THREAD

**Issue by mikethebeer** [crate/crate#13898] opened 2023-03-29 14:13 UTC
### CrateDB version

5.2.3

### CrateDB setup information

Number of Nodes: 3
CRATE_HEAP_SIZE: 6g

Table settings: (0 Replicas)

```sql
...
CLUSTERED BY ("s") INTO 3 SHARDS
PARTITIONED BY ("a", "b")
WITH (
   "allocation.max_retries" = 5,
   "blocks.metadata" = false,
   "blocks.read" = false,
   "blocks.read_only" = false,
   "blocks.read_only_allow_delete" = false,
   "blocks.write" = false,
   codec = \'default\',
   column_policy = \'strict\',
   "mapping.total_fields.limit" = 10000,
   max_ngram_diff = 1,
   max_shingle_diff = 3,
   number_of_replicas = \'0\',
   "routing.allocation.enable" = \'all\',
   "routing.allocation.total_shards_per_node" = -1,
   "store.type" = \'fs\',
   "translog.durability" = \'REQUEST\',
   "translog.flush_threshold_size" = 134217728,
   "translog.sync_interval" = 5000,
   "unassigned.node_left.delayed_timeout" = 60000,
   "write.wait_for_active_shards" = \'1\'
```

Num. Shards in Cluster:

```sql
cr> select count(*) from sys.shards;
+----------+
| count(*) |
+----------+
|     1618 |
+----------+
```

### Problem description

We run concurrent inserts (batch inserts with max. 100 rows) and queries against Crate into different schemas + tables like the following log shows:

```
2023-03-29T13:52:13.183736695Z  | INFO  gi.view.CrateStatsWriter {tenant=moore} - Upsert 5 records. Schema: moore
2023-03-29T13:52:13.579390595Z  | INFO  gi.view.CrateStatsWriter {tenant=galileo} - Upsert 15 records. Schema: galileo
2023-03-29T13:52:14.111380521Z  | INFO  gi.view.CrateStatsWriter {tenant=galileo} - Upsert 37 records. Schema: galileo
2023-03-29T13:52:14.263401690Z  | INFO  gi.view.CrateStatsWriter {tenant=jennings} - Upsert 100 records. Schema: jennings
2023-03-29T13:52:14.290855767Z  | INFO  gi.view.CrateStatsWriter {tenant=otf10} - Upsert 1 records. Schema: otf10
2023-03-29T13:52:14.317674906Z  | INFO  gi.view.CrateStatsWriter {tenant=otf10} - Upsert 6 records. Schema: otf10
2023-03-29T13:52:14.740389626Z  | INFO  gi.view.CrateStatsWriter {tenant=jennings} - Upsert 100 records. Schema: jennings
2023-03-29T13:52:15.227398629Z  | INFO  gi.view.CrateStatsWriter {tenant=jennings} - Upsert 100 records. Schema: jennings
2023-03-29T13:52:15.705710780Z  | INFO  gi.view.CrateStatsWriter {tenant=jennings} - Upsert 100 records. Schema: jennings
2023-03-29T13:52:16.178953068Z  | INFO  gi.view.CrateStatsWriter {tenant=jennings} - Upsert 100 records. Schema: jennings
2023-03-29T13:52:16.688381347Z  | INFO  gi.view.CrateStatsWriter {tenant=jennings} - Upsert 100 records. Schema: jennings
2023-03-29T13:52:16.858373951Z  | INFO  gi.view.CrateStatsWriter {tenant=dev} - Upsert 5 records. Schema: dev
2023-03-29T13:52:17.198410846Z  | INFO  gi.view.CrateStatsWriter {tenant=demo} - Upsert 5 records. Schema: demo
2023-03-29T13:52:17.338498864Z  | INFO  gi.view.CrateStatsWriter {tenant=kepler} - Upsert 5 records. Schema: kepler
2023-03-29T13:52:17.462171890Z  | INFO  gi.view.CrateStatsWriter {tenant=demo} - Upsert 5 records. Schema: demo
2023-03-29T13:52:17.511514318Z  | INFO  gi.view.CrateStatsWriter {tenant=kepler} - Upsert 5 records. Schema: kepler
2023-03-29T13:52:17.520325949Z  | INFO  gi.view.CrateStatsWriter {tenant=jennings} - Upsert 100 records. Schema: jennings
2023-03-29T13:52:17.567103686Z  | INFO  gi.view.CrateStatsWriter {tenant=demo} - Upsert 5 records. Schema: demo
2023-03-29T13:52:17.743326089Z  | INFO  gi.view.CrateStatsWriter {tenant=jennings} - Upsert 38 records. Schema: jennings
```

Once per week we run into an issue that causes missing shards. Due to statistical probability, most of the time tables that contain a lot of shards / partitions are affected.

### Steps to Reproduce

```sql
cr> select * from sys.health where health != 'GREEN' order by table_schema;                                                                                                                                                                                     
+--------+----------------+---------------------------------------------------------------------------------------------------------------------------------+----------+------------+-------------------+------------------------+
| health | missing_shards | partition_ident                                                                                                                 | severity | table_name | table_schema      | underreplicated_shards |
+--------+----------------+---------------------------------------------------------------------------------------------------------------------------------+----------+------------+-------------------+------------------------+
| RED    |              1 | 08t6eqave9gnenrkbtgmsobcf5q6iorjbthm2p9j60sj2e1d6kq3ec1d6gs32dpdc9i36o9d60q62dhkccs30dr46lh5uc0e64qj4chl6go3gc1g60o30           |        3 | gi_stats   | analytics         |                      0 |
| RED    |              1 | 08t6eqave9gnenrkbtgmsobcf5q6iorjbtijgdb46oq38e9dcpgj0phd6gq6cdhdc9j66c9dc4pj6oj269im2dpk68rluc0e64qj2dpk6gpj4c1g60o30           |        3 | gi_stats   | analytics         |                      0 |
| RED    |              1 | 0906eqave9gnenrkbth6urb2c5p68qb5e8mmspbnc5p6mnpg6csjepj468s2qcpj6pgiqc9hclh2qoj1cpj2qc1i6gp30o9g60o62dho1oojcchi6ko3adhg60o30c0 |        3 | gi_stats   | foo               |                      0 |
| RED    |              1 | 08qmeqave9gnenrkbti6arbfbsrj0e346lj3gc1d6ko3iohd64omae9d71h68dpd60p38chgc4o30c316cpluc0e64r3echl6coj4c1g60o30                   |        3 | gi_stats   | demo              |                      0 |
| RED    |              1 | 08qmeqave9gnenrkbti6arbfbsrj0e346lj3gc1d6ko3iohd64omae9d71h68dpd60p38chgc4o30c316cpluc0e64r3cdpi6oo3gc1g60o30                   |        3 | gi_stats   | demo              |                      0 |
| RED    |              1 | 08u6eqave9gnenrkbtpmqobiehimspbictslue9hccqjaoplccmmcdhj64mj2cb574mm4dr6ccmj0chk68o62c1g61gm8oiv60732dhn68qj6c9i60o30c1g        |        3 | gi_stats   | baz               |                      0 |
| RED    |              1 | 08q6eqave9gnenrkbtpnas3jd5fjac9o6gp32dr15ko34cpi5koj2pb15lh68cj15ko34d1i61gj0c1gc5ijg3hh6orjachg74r30c1g60o0                    |        3 | gi_stats   | bar               |                      0 |
+--------+----------------+---------------------------------------------------------------------------------------------------------------------------------+----------+------------+-------------------+------------------------+
```

### Actual Result

Crate logs prints:

```
 Caused by: [foo..partitioned.gi_stats.08smeqave9gnenrkbtl6arjed5n6esqvccqj6cpm75ij0bb1cgp6cb9h65im8bb16gq6ab9g68q34c3160o30cpi6lfj03hh6orjachg74r30c1g60o0/wI66Ho8TQiuWhh040AwuYA][[foo..partitioned.gi_stats.08smeqave9gnenrkbtl6arjed5n6esqvccqj6cpm75ij0bb1cgp6cb9h65im8bb16gq6ab9g68q34c3160o30cpi6lfj03hh6orjachg74r30c1g60o0][0]] org.elasticsearch.env.ShardLockObtainFailedException: [foo..partitioned.gi_stats.08smeqave9gnenrkbtl6arjed5n6esqvccqj6cpm75ij0bb1cgp6cb9h65im8bb16gq6ab9g68q34c3160o30cpi6lfj03hh6orjachg74r30c1g60o0][0]: obtaining shard lock for [starting shard] timed out after [5000ms], lock already held for [closing shard] with age [99730430ms]
 	at org.elasticsearch.env.NodeEnvironment$InternalShardLock.acquire(NodeEnvironment.java:741)
 	at org.elasticsearch.env.NodeEnvironment.shardLock(NodeEnvironment.java:644)
 	at org.elasticsearch.index.IndexService.createShard(IndexService.java:308)
 	... 15 more
 ]]
 java.io.IOException: failed to obtain in-memory shard lock
 	at org.elasticsearch.index.IndexService.createShard(IndexService.java:382) ~[crate-server.jar:?]
 	at org.elasticsearch.indices.IndicesService.createShard(IndicesService.java:488) ~[crate-server.jar:?]
 	at org.elasticsearch.indices.IndicesService.createShard(IndicesService.java:119) ~[crate-server.jar:?]
 	at org.elasticsearch.indices.cluster.IndicesClusterStateService.createShard(IndicesClusterStateService.java:626) ~[crate-server.jar:?]
 	at org.elasticsearch.indices.cluster.IndicesClusterStateService.createOrUpdateShards(IndicesClusterStateService.java:602) ~[crate-server.jar:?]
 	at org.elasticsearch.indices.cluster.IndicesClusterStateService.applyClusterState(IndicesClusterStateService.java:261) ~[crate-server.jar:?]
 	at org.elasticsearch.cluster.service.ClusterApplierService.callClusterStateAppliers(ClusterApplierService.java:502) ~[crate-server.jar:?]
 	at org.elasticsearch.cluster.service.ClusterApplierService.callClusterStateAppliers(ClusterApplierService.java:492) ~[crate-server.jar:?]
 	at org.elasticsearch.cluster.service.ClusterApplierService.applyChanges(ClusterApplierService.java:469) ~[crate-server.jar:?]
 	at org.elasticsearch.cluster.service.ClusterApplierService.runTask(ClusterApplierService.java:416) ~[crate-server.jar:?]
 	at org.elasticsearch.cluster.service.ClusterApplierService$UpdateTask.run(ClusterApplierService.java:163) ~[crate-server.jar:?]
 	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:259) ~[crate-server.jar:?]
 	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:222) ~[crate-server.jar:?]
 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
 	at java.lang.Thread.run(Thread.java:1589) ~[?:?]
 Caused by: org.elasticsearch.env.ShardLockObtainFailedException: [foo..partitioned.gi_stats.08smeqave9gnenrkbtl6arjed5n6esqvccqj6cpm75ij0bb1cgp6cb9h65im8bb16gq6ab9g68q34c3160o30cpi6lfj03hh6orjachg74r30c1g60o0][0]: obtaining shard lock for [starting shard] timed out after [5000ms], lock already held for [closing shard] with age [99730430ms]
 	at org.elasticsearch.env.NodeEnvironment$InternalShardLock.acquire(NodeEnvironment.java:741) ~[crate-server.jar:?]
 	at org.elasticsearch.env.NodeEnvironment.shardLock(NodeEnvironment.java:644) ~[crate-server.jar:?]
 	at org.elasticsearch.index.IndexService.createShard(IndexService.java:308) ~[crate-server.jar:?]
 	... 15 more
```

### Expected Result

I tried to solve these issues using:

```sql
alter cluster reroute retry failed
```

However, (most of the time) this does not help anything which causes me to do a full cluster restart. After a restart the missing shards are back to GREEN again.

We might think that increasing the replication factor to 2 might be able to solve at least the necessity to restart the cluster but it feels better to tackle the problem were it occurs.

**Comment by mikethebeer** [comment] 2023-03-29 14:15
Probably related to https://github.com/crate/crate/issues/9748

**Comment by mfussenegger** [comment] 2023-04-04 06:41
Do you see nodes dropping out of the cluster and rejoining in the logs of the master node?

**Comment by mikethebeer** [comment] 2023-04-05 08:03
We indeed have sometimes network outages (running in Docker Swarm). However, we don't know if the issue occurs exactly at the time of the outage.

**Comment by mfussenegger** [comment] 2023-04-05 09:42
Can you try and see if you can correlate them?

`ShardLockObtainFailedException` errors on shard creation are usually caused by either:

- Deleting partitions and re-creating them very quickly. Deleting closes shards, and re-creating partitions tries to acquire the same shard-lock that may still be in use if the delete takes some time (e.g. due to other queries using the shard for reads)
- Node dropping out and joining, which also can cause shards to close and re-open

There are some improvements we can make to the shard-lock acquisition to handle this better but it's unlikely that this would be part of a hotfix.

**Comment by mikethebeer** [comment] 2023-04-05 11:52
Thanks for clarifying this. Would a dedicated master - client - data node setup help to tackle this as well? Asking because our cluster state is quite big and we have now quite a lot partitions in there.  Alone this query takes 35 secs to complete.

```sql
cr> select count(*) from information_schema.table_partitions;
+----------+
| count(*) |
+----------+
|     4399 |
+----------+
SELECT 1 row in set (35.375 sec)
```

**Comment by mikethebeer** [comment] 2023-04-07 07:03
@mfussenegger Shard lock popped again up this night (Crate 4.5) . I think this time due to a node drop and re-join (see charts). 

![grafik](https://user-images.githubusercontent.com/6863216/230557808-2e3df099-7c47-4d48-8090-a14715d1f8ea.png)

```
base_crate.0.kuayp5djine7@s9.schruns.ls.af    | 	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(Object, ChannelPromise)(Unknown Source) ~[netty-transport-4.1.63.Final.jar:4.1.63.Final]
base_crate.0.kuayp5djine7@s9.schruns.ls.af    | [2023-04-06T19:54:44,098][WARN ][o.e.t.OutboundHandler    ] [s9.schruns.ls.af] send message failed [channel: Netty4TcpChannel{localAddress=/10.135.226.170:4300, remoteAddress=/10.135.125.130:47280}]
base_crate.0.kuayp5djine7@s9.schruns.ls.af    | io.netty.channel.StacklessClosedChannelException: null
base_crate.0.tpxwwya09opi@s7.schruns.ls.af    | [2023-04-06T19:53:02,999][WARN ][o.e.t.TransportService   ] [s7.schruns.ls.af] Received response for a request that has timed out, sent [15034ms] ago, timed out [5009ms] ago, action [internal:coordination/fault_detection/follower_check], node [{s9.schruns.ls.af}{RYNQQ342SkOUp5MJaBc19w}{OtuZpGwcSOm3Vrv4qVgnIg}{10.135.226.170}{10.135.226.170:4300}{http_address=10.135.226.170:4200}], id [8438999]
base_crate.0.kuayp5djine7@s9.schruns.ls.af    | 	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(Object, ChannelPromise)(Unknown Source) ~[netty-transport-4.1.63.Final.jar:4.1.63.Final]
base_crate.0.kuayp5djine7@s9.schruns.ls.af    | [2023-04-06T19:54:44,098][WARN ][o.e.t.OutboundHandler    ] [s9.schruns.ls.af] send message failed [channel: Netty4TcpChannel{localAddress=/10.135.226.170:4300, remoteAddress=/10.135.226.155:52174}]
base_crate.0.kuayp5djine7@s9.schruns.ls.af    | io.netty.channel.StacklessClosedChannelException: null
base_crate.0.kuayp5djine7@s9.schruns.ls.af    | 	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(Object, ChannelPromise)(Unknown Source) ~[netty-transport-4.1.63.Final.jar:4.1.63.Final]
base_crate.0.kuayp5djine7@s9.schruns.ls.af    | [2023-04-06T19:54:44,098][WARN ][o.e.t.OutboundHandler    ] [s9.schruns.ls.af] send message failed [channel: Netty4TcpChannel{localAddress=/10.135.226.170:4300, remoteAddress=/10.135.226.155:52174}]
base_crate.0.kuayp5djine7@s9.schruns.ls.af    | io.netty.channel.StacklessClosedChannelException: null
base_crate.0.tpxwwya09opi@s7.schruns.ls.af    | [2023-04-06T19:54:17,352][INFO ][o.e.c.s.MasterService    ] [s7.schruns.ls.af] node-left[{s9.schruns.ls.af}{RYNQQ342SkOUp5MJaBc19w}{OtuZpGwcSOm3Vrv4qVgnIg}{10.135.226.170}{10.135.226.170:4300}{http_address=10.135.226.170:4200} followers check retry count exceeded], term: 693, version: 67346, reason: removed {{s9.schruns.ls.af}{RYNQQ342SkOUp5MJaBc19w}{OtuZpGwcSOm3Vrv4qVgnIg}{10.135.226.170}{10.135.226.170:4300}{http_address=10.135.226.170:4200},}
base_crate.0.kuayp5djine7@s9.schruns.ls.af    | 	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(Object, ChannelPromise)(Unknown Source) ~[netty-transport-4.1.63.Final.jar:4.1.63.Final]
base_crate.0.kuayp5djine7@s9.schruns.ls.af    | [2023-04-06T19:54:44,096][WARN ][o.e.t.OutboundHandler    ] [s9.schruns.ls.af] send message failed [channel: Netty4TcpChannel{localAddress=/10.135.226.170:4300, remoteAddress=/10.135.226.156:42076}]
base_crate.0.kuayp5djine7@s9.schruns.ls.af    | io.netty.channel.StacklessClosedChannelException: null
base_crate.0.tpxwwya09opi@s7.schruns.ls.af    | [2023-04-06T19:54:26,215][INFO ][o.e.c.s.ClusterApplierService] [s7.schruns.ls.af] removed {{s9.schruns.ls.af}{RYNQQ342SkOUp5MJaBc19w}{OtuZpGwcSOm3Vrv4qVgnIg}{10.135.226.170}{10.135.226.170:4300}{http_address=10.135.226.170:4200},}, term: 693, version: 67346, reason: Publication{term=693, version=67346}
base_crate.0.tpxwwya09opi@s7.schruns.ls.af    | [2023-04-06T19:54:26,586][INFO ][o.e.c.r.DelayedAllocationService] [s7.schruns.ls.af] scheduling reroute for delayed shards in [50.5s] (587 delayed shards)
base_crate.0.kuayp5djine7@s9.schruns.ls.af    | 	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(Object, ChannelPromise)(Unknown Source) ~[netty-transport-4.1.63.Final.jar:4.1.63.Final]
base_crate.0.tpxwwya09opi@s7.schruns.ls.af    | [2023-04-06T19:54:47,949][INFO ][o.e.c.s.MasterService    ] [s7.schruns.ls.af] node-join[{s9.schruns.ls.af}{RYNQQ342SkOUp5MJaBc19w}{OtuZpGwcSOm3Vrv4qVgnIg}{10.135.226.170}{10.135.226.170:4300}{http_address=10.135.226.170:4200} join existing leader], term: 693, version: 67349, reason: added {{s9.schruns.ls.af}{RYNQQ342SkOUp5MJaBc19w}{OtuZpGwcSOm3Vrv4qVgnIg}{10.135.226.170}{10.135.226.170:4300}{http_address=10.135.226.170:4200},}
base_crate.0.tpxwwya09opi@s7.schruns.ls.af    | [2023-04-06T19:54:57,915][INFO ][o.e.c.s.ClusterApplierService] [s7.schruns.ls.af] added {{s9.schruns.ls.af}{RYNQQ342SkOUp5MJaBc19w}{OtuZpGwcSOm3Vrv4qVgnIg}{10.135.226.170}{10.135.226.170:4300}{http_address=10.135.226.170:4200},}, term: 693, version: 67349, reason: Publication{term=693, version=67349}
base_crate.0.tpxwwya09opi@s7.schruns.ls.af    | [2023-04-06T19:55:23,749][WARN ][o.e.c.r.a.AllocationService] [s7.schruns.ls.af] failing shard [failed shard, shard [dbnetz..partitioned.gi_stats.08qmeqave9gnenrkbti64rj5eht5ueb4chh32pb3c4mj2d1h60mj2cb5c8mjgopk70mj0chk68o62c1g61gj6dge64r3gc1j60rj4c1g60o30][0], node[RYNQQ342SkOUp5MJaBc19w], [P], recovery_source[existing store recovery; bootstrap_history_uuid=false], s[INITIALIZING], a[id=UEzj6ZavSQe-RZs9lqYHZg], unassigned_info[[reason=NODE_LEFT], at[2023-04-06T19:54:17.103Z], delayed=true, details[node_left [RYNQQ342SkOUp5MJaBc19w]], allocation_status[deciders_throttled]], message [failed to create shard], markAsStale [true], failure [java.io.IOException: failed to obtain in-memory shard lock
base_crate.0.tpxwwya09opi@s7.schruns.ls.af    | 	at org.elasticsearch.index.IndexService.createShard(IndexService.java:366)
base_crate.0.tpxwwya09opi@s7.schruns.ls.af    | 	at org.elasticsearch.indices.IndicesService.createShard(IndicesService.java:482)
base_crate.0.tpxwwya09opi@s7.schruns.ls.af    | 	at org.elasticsearch.indices.IndicesService.createShard(IndicesService.java:111)
base_crate.0.tpxwwya09opi@s7.schruns.ls.af    | 	at org.elasticsearch.indices.cluster.IndicesClusterStateService.createShard(IndicesClusterStateService.java:610)
base_crate.0.tpxwwya09opi@s7.schruns.ls.af    | 	at org.elasticsearch.indices.cluster.IndicesClusterStateService.createOrUpdateShards(IndicesClusterStateService.java:586)
base_crate.0.tpxwwya09opi@s7.schruns.ls.af    | 	at org.elasticsearch.indices.cluster.IndicesClusterStateService.applyClusterState(IndicesClusterStateService.java:245)
base_crate.0.tpxwwya09opi@s7.schruns.ls.af    | 	at org.elasticsearch.cluster.service.ClusterApplierService.lambda$callClusterStateAppliers$5(ClusterApplierService.java:507)
base_crate.0.tpxwwya09opi@s7.schruns.ls.af    | 	at java.lang.Iterable.forEach(Iterable.java:75)
base_crate.0.tpxwwya09opi@s7.schruns.ls.af    | 	at org.elasticsearch.cluster.service.ClusterApplierService.callClusterStateAppliers(ClusterApplierService.java:504)
base_crate.0.tpxwwya09opi@s7.schruns.ls.af    | 	at org.elasticsearch.cluster.service.ClusterApplierService.applyChanges(ClusterApplierService.java:481)
base_crate.0.kuayp5djine7@s9.schruns.ls.af    | [2023-04-06T19:54:44,099][WARN ][o.e.t.OutboundHandler    ] [s9.schruns.ls.af] send message failed [channel: Netty4TcpChannel{localAddress=/10.135.226.170:4300, remoteAddress=/10.135.226.155:52174}]
base_crate.0.tpxwwya09opi@s7.schruns.ls.af    | 	at org.elasticsearch.cluster.service.ClusterApplierService.runTask(ClusterApplierService.java:428)
base_crate.0.kuayp5djine7@s9.schruns.ls.af    | io.netty.channel.StacklessClosedChannelException: null
base_crate.0.tpxwwya09opi@s7.schruns.ls.af    | 	at org.elasticsearch.cluster.service.ClusterApplierService$UpdateTask.run(ClusterApplierService.java:176)
base_crate.0.tpxwwya09opi@s7.schruns.ls.af    | 	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:259)
base_crate.0.tpxwwya09opi@s7.schruns.ls.af    | 	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:222)
base_crate.0.tpxwwya09opi@s7.schruns.ls.af    | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
base_crate.0.kuayp5djine7@s9.schruns.ls.af    | 	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(Object, ChannelPromise)(Unknown Source) ~[netty-transport-4.1.63.Final.jar:4.1.63.Final]
base_crate.0.tpxwwya09opi@s7.schruns.ls.af    | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
base_crate.0.kuayp5djine7@s9.schruns.ls.af    | [2023-04-06T19:54:44,099][WARN ][o.e.t.OutboundHandler    ] [s9.schruns.ls.af] send message failed [channel: Netty4TcpChannel{localAddress=/10.135.226.170:4300, remoteAddress=/10.135.226.156:42076}]
base_crate.0.kuayp5djine7@s9.schruns.ls.af    | io.netty.channel.StacklessClosedChannelException: null
```

So we can confirm, that shard-locks occurs exactly at the time of the outage.

Since we run our servers on a cloud service provider this can happen from time to time and we can't really predict this. Additionally we use host-networking and no Docker overlay in between so we think the drop-out can't really be caused by Docker / Docker Swarm.

Would you recommend to introduce replicas in order to fix it? ATM we use 0 replicas on these tables.

**Comment by dobe** [comment] 2023-04-07 08:09
here some additional logs directly from the container that was going down on s9:

```
[2023-04-06T04:12:12,053][WARN ][o.e.m.j.JvmGcMonitorService] [s9.schruns.ls.af] [gc][22813] overhead, spent [1s] collecting in the last [1.2s]
[2023-04-06T09:10:06,271][WARN ][o.e.m.j.JvmGcMonitorService] [s9.schruns.ls.af] [gc][40666] overhead, spent [646ms] collecting in the last [1s]
[2023-04-06T09:42:55,588][INFO ][o.e.m.j.JvmGcMonitorService] [s9.schruns.ls.af] [gc][42633] overhead, spent [518ms] collecting in the last [1.3s]
[2023-04-06T19:23:14,315][INFO ][o.e.m.j.JvmGcMonitorService] [s9.schruns.ls.af] [gc][77433] overhead, spent [276ms] collecting in the last [1s]
[2023-04-06T19:53:03,003][WARN ][o.e.m.j.JvmGcMonitorService] [s9.schruns.ls.af] [gc][young][79203][1782] duration [15.3s], collections [1]/[15.7s], total [15.3s]/[56.9s], memory [8.8gb]->[6.2gb]/[12gb], all_pools {[young] [2.6gb]->[16mb]/[0b]}{[old] [6.2gb]->[6.2gb]/[12gb]}{[survivor] [25.7mb]->[32.5mb]/[0b]}
[2023-04-06T19:53:03,003][WARN ][o.e.m.j.JvmGcMonitorService] [s9.schruns.ls.af] [gc][79203] overhead, spent [15.3s] collecting in the last [15.7s]
[2023-04-06T19:54:43,613][WARN ][o.e.m.j.JvmGcMonitorService] [s9.schruns.ls.af] [gc][young][79245][1783] duration [56.2s], collections [1]/[59.5s], total [56.2s]/[1.8m], memory [8.8gb]->[6.2gb]/[12gb], all_pools {[young] [2.5gb]->[48mb]/[0b]}{[old] [6.2gb]->[6.2gb]/[12gb]}{[survivor] [32.5mb]->[17.4mb]/[0b]}
[2023-04-06T19:54:43,613][WARN ][o.e.m.j.JvmGcMonitorService] [s9.schruns.ls.af] [gc][79245] overhead, spent [56.2s] collecting in the last [59.5s]
[2023-04-06T19:54:43,634][WARN ][o.e.t.OutboundHandler    ] [s9.schruns.ls.af] send message failed [channel: Netty4TcpChannel{localAddress=/10.135.226.170:4300, remoteAddress=/10.135.226.154:36980}]
io.netty.channel.StacklessClosedChannelException: null
	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(Object, ChannelPromise)(Unknown Source) ~[netty-transport-4.1.63.Final.jar:4.1.63.Final]
```

looks like the breaking node was spending too much time with GC.

**Comment by mikethebeer** [comment] 2023-06-06 06:26
@mfussenegger we have identified the issue that causes the shard-lock symptom. A bug in our http client app (data export feature) triggered a lot of queries affecting the same shard that caused the same same (1) or 0 record(s) to be returned every time. 

![grafik](https://github.com/crate/crate/assets/6863216/777e5b86-e9a2-4863-bdee-900ed0c6b14a)
It's definitely a lot more queries than this graph shows (approx 8 queries / sec) but I think the queue got filled up massively, since the whole data export procedure on the client app would have lead in worst case to ~53k queries (depending on time range to export) against Crate.

![grafik](https://github.com/crate/crate/assets/6863216/4668653f-376f-45a9-b047-07d83f4c860c)

So the bug got fixed in our app and the Cluster seems to be more reliable now.

However, I think generally a shard-lock should not leave the shard in an unrecoverable state, as for an end-user this could be seen as a loss of data since it does not receive inserts nor select until a node/cluster restart.

**Comment by mfussenegger** [comment] 2023-06-12 09:04
> However, I think generally a shard-lock should not leave the shard in an unrecoverable state

Yes, I created https://github.com/crate/crate/issues/13982 for that.

Given that the issue in this particular instance got solved on your side I'm closing this ticket here.

**Closed by mfussenegger** 2023-06-12 09:04 UTC
Labels: needs info or feedback

**Comment by mikethebeer** [comment] 2023-06-13 05:33
@mfussenegger thanks for effort.

**Comment by mikethebeer** [comment] 2023-06-13 05:33
@mfussenegger thanks for your effort.
