### ISSUE TITLE
Bad performance on ORDER BY primary key with Crate 2.2.4

### ISSUE THREAD

**Issue by tsubasa617** [crate/crate#6631] opened 2017-12-06 16:10 UTC
**CrateDB version**: 2.2.4

**JVM version**: 1.8.0_121

**OS version / environment description**: Linux version 3.10.0-327.22.2.el7.x86_64 (builder@kbuilder.dev.centos.org) (gcc version 4.8.3 20140911 (Red Hat 4.8.3-9) (GCC) ) #1 SMP Thu Jun 23 17:05:11 UTC 2016

**Problem description**:

The performance of ORDER BY primary key is vary weak with Crate 2.2.4, which is 30 times slower than with version 2.1.7。

Our table has 28.1 Million records, which is 21.9GB, with 6 Shards and 0-1 Replicas.
We have 3 nodes, each has 4 CPU cores, 16 GB Memory (Crate use 8GB) and 300GB SSD.

`SELECT * FROM xxx ORDER BY aaa limit 15;`

'aaa' is the primary key of table 'xxx'.
When doing this query in Crate 2.1.7, it costs 0.311 Sec, while in Crate 2.2.4, 9.942 Sec.
![d70403b2e34614302005779c849e6a6e](https://user-images.githubusercontent.com/5774420/33672354-ffd1f300-dae4-11e7-9ed8-69733fc4fb2d.jpg)
![04e8a19c56b63d2ab5f88bc356496d18](https://user-images.githubusercontent.com/5774420/33672314-e7778860-dae4-11e7-940b-c90e856bbe45.jpg)

**Steps to reproduce**:

CREATE TABLE IF NOT EXISTS "doc"."test_performance" (
   "info" int,
   "name" STRING,
   PRIMARY KEY ("name")
)
CLUSTERED BY ("name") INTO 6 SHARDS;

insert into test_performance (name, info) values ('a', 1);
insert into test_performance (name, info) values ('b', 2);
insert into test_performance (name, info) values ('c', 3);
.....
insert into test_performance (name, info) values ('xxx', 10000000);

select * from test_performance order by name limit 15;

**Comment by mfussenegger** [comment] 2017-12-07 10:55
Thanks for reporting. We'll take a look at this.

**Comment by mfussenegger** [comment] 2017-12-07 19:13
This will be fixed with 2.2.5 (PR for the fix is https://github.com/crate/crate/pull/6638)

Turns out we actually would've had performance regression tests for this particular case (see https://github.com/crate/crate-benchmarks/blob/ed8e872842dcc9261cb6ed35f59a2cdfb75d169a/py/specs/queries.toml#L38) but for whatever reasons we didn't notice it. We'll take measures to improve things in that regard.

**Closed by mfussenegger** 2017-12-07 19:13 UTC
