### ISSUE TITLE
COPY FROM into partitioned table using large dataset - not all data is loaded and job hangs and cannot be killed

### ISSUE THREAD

**Issue by grestocla** [crate/crate#6036] opened 2017-07-27 16:34 UTC
**CrateDB version**:
2.0.5 / 2.0.6

**JVM version**:
OpenJDK 1.8.0_131

**OS version / environment description**:
CentOS 7 (3.10.0-514.26.2.el7.x86_64)

**Problem description**:
When performing an initial import of data (large dataset, serveral hundred million rows, spread over 40+ partitions) in a freshly created partitioned table using the COPY FROM command, after some time the import stops (cluster load drops), the job is still visible in sys.jobs even it appears that it doesn't do anything and cannot be killed using the KILL command (KILL ALL doesn't affect it either). Not all data was importet, rows are still missing.

I tried with only 1 partition importing a few million rows, same result - not all data is imported, job hangs, cannot be killed. Unfortunately there are no messages in the logfile, no stacktrace et cetera.

When I import only a few rows, everything is working fine. It appears to me, that datasets that are bigger than 2gb are affected, but I am not 100% sure.

When I manually pre-create the partition with a "dummy" insert then the few million rows are imported perfectly fine in this partition.

Because I am not allowed to post the exact CREATE TABLE statement due to confidential reasons, here are some pointers:

My table consists of 46 columns, mostly numeric (short, integer, long), some boolean, two strings. It has two generated columns, one sum column of several integer columns and one generated column _yearmonth_ (year*100+month). This _yearmonth_ column is used for partitioning (i.e. CLUSTERED INTO 8 SHARDS, PARTITIONED BY ("yearmonth")). 8 of the columns are a combined primary key.

**Comment by seut** [comment] 2017-07-28 09:26
@grestocla thanks for reporting, we are looking into that and will keep you up to date.

**Comment by seut** [comment] 2017-07-31 14:35
@grestocla 
Unfortunately we can't reproduce this yet.
Can you please tell us your used ``COPY FROM`` statement or at least from what source you're importing (s3, fs/nfs) and the used `WITH` options?
How much nodes are you running? Do all nodes have access to the import resource (eg. s3 access or if the FS file available on all nodes)?
Thanks a lot.

**Comment by grestocla** [comment] 2017-07-31 15:12
@seut 
Thank you for looking into it.

I copied the file directly on one node of the cluster and imported from there with
`COPY myschema.mytable FROM '/path/to/import.json';`. The other nodes do not have access to that file on the node. The file is located on the same mount where crate stores ists cluster data.
We use ext4 as our filesystem on all of our 8 nodes. They have 64 gb ram (CRATE_HEAP_SIZE=29g) each.

Here are some file sizes of tests we performed to give you a better understanding of our imports:
- Size: 44 gb     Rows: 81.913.891
- Size: 23 gb     Rows: 42.521.736
- Size: 258 gb   Rows: 484.162.722

The largest file contained data that affected more than one partition.

**Comment by seut** [comment] 2017-08-04 14:14
@grestocla 
We've found a issue related to the "job cannot be killed" issue, see https://github.com/crate/crate/commit/90cba7f77ac3fcf185d3e13c509c4e38db2eb4ab. This will be release with the next 2.0 hotfix release.
This issue has been already fixed on the 2.1.0 release (and also master) along with some performance improvements.
As far as I figured out, at 2.0.6, performance of inserts is not really good when lot of partitions are in play, also the default `bulk_size` of 100 is really to low in that case, but I can't reproduce lost inserts, its just very slow sometimes.
Can you please increase it to let say `10000` and see if that improves it?
Also maybe you can test this scenario with the current 2.1.0 testing release?
We're planning to make a stable 2.1 release soon, so at least at this point I'd highly recommend to update.

**Comment by grestocla** [comment] 2017-08-08 08:06
@seut 
Thank you for your feedback, I appreciate your effort. We will increase the bulk_size and run some tests again. We also will update our cluster to 2.1. as soon as it is released stable for production.

**Comment by seut** [comment] 2017-08-11 11:34
@grestocla As I think this issue is already fixed by 2.1, I'm closing it now. If you're still having problems, feel free to re-open it.

**Closed by seut** 2017-08-11 11:34 UTC
