### ISSUE TITLE
create table xxx as select * from yyy

### ISSUE THREAD

**Issue by cmdares** [crate/crate#7551] opened 2018-07-30 16:35 UTC
support:  create table xxx as select * from yyy
To improve the convenience of syntax, create temporary tables, use data ETL and so on.
Migration of compilation from traditional database (oracle/mysql/hive) to cratedb.
it is useful,thanks!

**Comment by chaudum** [comment] 2018-07-31 12:33
duplicate of https://github.com/crate/crate/issues/7396

**Comment by mfussenegger** [comment] 2020-07-07 08:43
Duplicate of https://github.com/crate/crate/issues/9999 - keeping the other issue because it has a more detailed description.

**Closed by mfussenegger** 2020-07-07 08:43 UTC
Labels: complexity: 5-8, contributions welcome, feature: sql: ddl
