### ISSUE TITLE
Long GC Pauses found on current master node.

### ISSUE THREAD

**Issue by sybrandy** [crate/crate#5234] opened 2017-03-30 15:37 UTC
**CrateDB version**: 1.0.0

**JVM version**: 1.8.0_31

**OS version / environment description**: centos7.0.1406

**Problem description**:

Same cluster as @shaunoconnell, I'm seeing the current master node experiencing log GC pauses.  On my screen right now, I see pauses ranging from 7.8s to 1.2m.  Below is one example of this:

```
org.elasticsearch.monitor.jvm.JvmMonitorService$JvmMonitor [<hostname>]
[gc][old][171668][1084] duration [49.1s], collections [6]/[49.3s], total [49.1s]/[41.7m],
memory [1.9gb]->[1.9gb]/[1.9gb], all_pools {[young] [546.1mb]/[546.1mb]}
{[survivor] [64mb]->[66.8mb]/[66.2mb]}{[old] [1.3gb]->[1.3gb]/[1.3gb]}
```

I discovered this because I could see on a different node that it was getting "Received response for a request that has timed out" messages when communicating with the master.

Not sure if this is related to #5188 or not.

**Comment by mfussenegger** [comment] 2017-03-30 15:54
Is the master node also a data node? This log entry indicates that it cannot free anything at all. So either there is some memory leak (May be related to https://github.com/crate/crate/issues/4972 ) or there is too much activity / state and it does require that much memory - in that case you'll have to increase the heap size. 

If it is caused by a memory leak, it would be great if you could provide us with a heap dump so that we can analyze it and figure out what's leaking.
We already have a pending fix in regards to memory leaks (will be in 1.0.6) - that was related to error handling in group by queries. So unless you've a lot of group by queries that run into failures, you shouldn't be affected by that

**Comment by sybrandy** [comment] 2017-03-30 16:13
Yes, it is a data node.  I was looking into that as well and it looks like the documentation doesn't mention separating nodes into master and data nodes, so our configuration does not do this.

As for the heap dump, I didn't get one as I already restarted it to try to get it running again.  I'll try to get one the next time it happens.

Oddly enough, I was running a few queries manually when I noticed this occurring that had group-by's, but I can hardly believe that I ran that many.

**Comment by mfussenegger** [comment] 2017-03-30 17:34
Having dedicated master nodes can get interesting in a larger cluster. For smaller ones it's usually okay to use the nodes as both, data node and master node.

Queries by default may take up to 60% of the Heap before they're interrupted to avoid out of memory issues. It might be that this is a bit too much in your case. (https://crate.io/docs/reference/configuration.html#query-circuit-breaker)

Depending on the cardinality of the columns and number of records, GROUP BY queries can use that up quickly if you have only 2GB of HEAP.

Do you have some kind of JVM metric monitoring in place? It would allow to tell if this is caused by a like (old heap space size growing slowly over time), or if it was caused by a burst of queries.

**Comment by sybrandy** [comment] 2017-03-30 18:32
Re: master nodes: That type of configuration is what's recommended by ElasticSearch and so far it's been working well in our setup, so we were thinking about trying it out with Crate as well.

Re: heap: I'll talk to one of the other devs about increasing the heap size.  You may be right: we just need more heap space.

RE: heap monitoring: no, not yet.  Since the ElasticSearch APIs are still there, we were planning on leveraging Telegraf to collect heap metrics and display them in Grafana.

**Comment by mfussenegger** [comment] 2017-04-06 13:43
I'm closing this as I think there's nothing here for us to do?

**Closed by mfussenegger** 2017-04-06 13:43 UTC
