### ISSUE TITLE
Inserting record with duplicate primary key into table with replica inserts the record with new version

### ISSUE THREAD

**Issue by ghotikun** [crate/crate#3946] opened 2016-08-08 16:50 UTC
If you create a table with one replica (the default) and have multiple nodes in a cluster, then crate allows inserts with duplicate primary keys. Crate throws a DuplicateKeyException but the record will still be inserted with a different _version. Making a request for count will return the expected count (suggesting the duplicate has not been added), but selecting all of the records will toggle between both versions of the record.

This is particularly detrimental when inserting many responses at once into a table with many responses already there. This will result in different combinations of versions being returned for each select. If you delete all rows, version 1 will all be deleted, but some arbitrary number of version 2 will remain. Selecting all will toggle between two different sets of version 2 records.

Details to reproduce follow:
This is for crate 0.55.2 on Mac OS X 10.9.5

1) Create 3 nodes with docker:
`docker run -d --name=c1 crate -Des.discovery.zen.minimum_master_nodes=2 -Des.gateway.expected_nodes=3 -Des.gateway.recover_after_nodes=3
docker run -d --name=c2 crate -Des.discovery.zen.minimum_master_nodes=2 -Des.gateway.expected_nodes=3 -Des.gateway.recover_after_nodes=3
docker run -d --name=c0 -p 4200:4200 -p 4300:4300 crate -Des.discovery.zen.minimum_master_nodes=2 -Des.gateway.expected_nodes=3 -Des.gateway.recover_after_nodes=3`

2) Create a table with a primary key:
`create table test (
  id string primary key,
  content string
);`

3) Insert a record:
`insert into test (id, content) values ('1', 'test');`

4) Insert a record with a duplicate primary key but different content:
`insert into test (id, content) values ('1', 'fail');`

5) Request all records multiple times. Each time you request, note that a different version is returned:
`select _version, * from test limit 100;`
`select _version, * from test limit 100;`

**Comment by seut** [comment] 2016-08-09 11:54
Seems like you just forgot to issue a `refresh test;` after inserting and before selecting.
That explains why you're seeing different versions on select using replicas because read request will go to primaries or replicas and their current view on the data could differ without a `refresh`.
See also https://crate.io/docs/reference/en/stable/sql/refresh.html

**Comment by ghotikun** [comment] 2016-08-09 14:31
I didn't think to try an explicit refresh. I went ahead and tried it, but unfortunately I'm still getting the same results. Also, I thought that a table would be refreshed every 1000 ms automatically by default. Is that not true? Thanks!

**Comment by seut** [comment] 2016-08-09 14:40
Ok I've not read all of your comment and missed out that 2nd insert throws a DuplicateKeyException but was still inserted. I've could not reproduce this on a short test, but we'll investigate this. thanks for reporting.

**Comment by ghotikun** [comment] 2016-08-09 14:47
Thanks. I should also note that a request for the number of records will still return the correct number of records --- 1 in the test example above. It's as if there are two versions of the data, one on the primary and the other on the replica; but, the replica is not syncing properly with the primary. Doing subsequent selects seems to toggle between the primary and the replica.

**Comment by seut** [comment] 2016-08-12 12:47
@ghotikun this issue was fixed by https://github.com/crate/crate/commit/8d63e05740867640a1e8d08608398a4b5a05c959 and will be released asap with the next hotfix release. again, thanks for reporting!

**Closed by seut** 2016-08-12 12:47 UTC
Labels: bug

**Comment by ghotikun** [comment] 2016-08-12 14:13
Great. Thank you!
