### ISSUE TITLE
Support for correlated subqueries: Select t1.pk,(select count(0) from table2 t2 where t2.fk = t1.pk) as c from table1 t1

### ISSUE THREAD

**Issue by gongweibiao1986** [crate/crate#8038] opened 2018-12-30 02:01 UTC
**Use case**:

**Feature description**:
Select t1.pk,(select count(0) from table2 t2 where t2.fk = t1.pk) as c from table1 t1
can this syntax be supported in future upgrades?

**Comment by mfussenegger** [comment] 2020-01-21 15:19
Closing this as duplicate of https://github.com/crate/crate/issues/9320

**Closed by mfussenegger** 2020-01-21 15:19 UTC
Labels: feature: sql: relations
