### ISSUE TITLE
Huge performance hit between 2.2.7 and 2.3.4

### ISSUE THREAD

**Issue by echarlus** [crate/crate#7017] opened 2018-03-13 10:37 UTC
**CrateDB version**:
2.3.4 
**JVM version**:

JVM[Oracle Corporation/Java HotSpot(TM) 64-Bit Server VM/1.8.0_162/25.162-b12]

**OS version / environment description**:
MacOS 10.13.3 16GB RAM/Intel core I7 quad core 2.9GHz/ SSD
 
Linux 4.15 also impacted 

**Problem description**:

I’m running a two nodes cluster with both nodes on the same machine (node.max_local_storage_nodes: 2)
I’ve notice performance degradation after I upgraded from version 2.2.7 to versions 2.3.x (now on 2.3.4)
Here are some samples of query timing on both versions, on 2.3.7 the response time is sometimes longer by a factor > 50 ! but in any case it’s always slower than on 2.2.7 (14.73 and 21,73 times slower computed on 7 timings per query per version) :

```
select 
    i.date_created as date, i.indicators[‘temperature’] as value
from 
    indicators i 
    left join message m on i.message_id=m.id 
where 
    m.sensor_id = ‘70B3D59BA0005E24_1514907608248783789’ 
   and i.date_created>=‘1489331358210’ 
   and i.date_created<=‘1520867358210’  
   and m.type_id=1  
order by 
    i.date_created asc 
limit 1000;
```
result is 224 rows fetched  (same query ran 7 times on each version, same host, same dataset): 

Crate 2.3.4 timings : 
85.417/85.756/116.229/2.188/2.092/2.106/2.084 AVG = 41.95s

Crate 2.2.7 timings : 
2.150/1.907/1.886/1.887/1.895/1.865/1.961/ AVG = 1.93s

Factor version 2.2.7/2.3.4  = 21,73

Same query but adding a non null condition on a the queried value which is stored in an object(ANY) column : 

```
select 
    i.date_created as date, 
    i.indicators[‘temperature’] as value 
from 
    indicators i 
    left join message m on i.message_id=m.id 
where 
    m.sensor_id = ‘70B3D59BA0005E24_1514907608248783789’ 
    and i.date_created>=‘1489331358210’ 
    and i.date_created<=‘1520867358210’  
    and m.type_id=1 
    and i.indicators[‘temperature’] is not null 
order by i.date_created asc 
limit 1000;
```
Result is 224 rows fetched in (same query ran 7 times on each version, same host, same dataset): 

Crate 2.2.7 timings : 
0.407/0.323s/0.336/0.326/0.324/0.305/0.359 AVG = 0,349s

Crate 2.3.4 timings : 
0.583/0.495/0.352/0.360/15.179/17.689/0.348 AVG = 4,998s

Factor 2.2.7/2.3.4 = 14.7

Tests have been run on the same machine which is not under any sort of load (laptop)

The whole DB has 176k records. 
Table indicators has 84k records, table messages has 60k records. Do you see what could be causing this ? Have had reports about such issues ?
Table definitions are : 

```
CREATE TABLE IF NOT EXISTS "message" (
   "command_id" INTEGER,
   "date_created" TIMESTAMP NOT NULL,
   "date_processed" TIMESTAMP NOT NULL,
   "decrypted_payload" STRING,
   "delivered_at" TIMESTAMP,
   "encrypted_payload" STRING,
   "id" STRING,
   "month" TIMESTAMP GENERATED ALWAYS AS date_trunc('month', "date_created"),
   "protocol_data" OBJECT (DYNAMIC),
   "sensor_id" STRING NOT NULL,
   "type_id" SHORT NOT NULL,
   PRIMARY KEY ("id", "month")
)
CLUSTERED INTO 4 SHARDS
PARTITIONED BY ("month")
```

```
CREATE TABLE IF NOT EXISTS "indicators" (
   "date_created" TIMESTAMP NOT NULL,
   "date_processed" TIMESTAMP NOT NULL,
   "id" STRING,
   "indicators" OBJECT (DYNAMIC),
   "message_id" STRING NOT NULL,
   "month" TIMESTAMP GENERATED ALWAYS AS date_trunc('month', "date_created"),
   PRIMARY KEY ("id", "month")
)
CLUSTERED INTO 4 SHARDS
PARTITIONED BY ("month")
```

**Comment by m-kharbat** [comment] 2018-03-13 10:48
Thank you for reporting.. we will take a look at this.

**Comment by echarlus** [comment] 2018-03-13 10:52
thanks if you need more info let me know.

**Comment by echarlus** [comment] 2018-03-13 17:05
I see you've flagged this as enhancement, I'd rather mark it as a regression since it's really a big from problem and should not happen when moving to a newer version ... If flagged as enhancement, will it be processed quickly ?

**Comment by chaudum** [comment] 2018-03-16 07:00
Hi @echarlus 
We've been looking into your issue and discovered that under specific circumstances the queries take a very long time. It probably has to do with shard distribution across nodes, but we don't know the real cause yet. However, we are on something already.
The slow queries should not happen when you have multiple nodes on multiple hosts and less than N-1 replicas (where N is the amount of nodes).
We'll keep you posted about our progress.
One other question: How many partitions do you have in total?

**Comment by echarlus** [comment] 2018-03-16 08:05
Hi @chaudum thanks for the update. I'm glad to hear you've already found some hints about the issue.
If you manage to get rid of the very slow queries that will already be great. However if you look at the measures I've made you'll notice that 2.3.4 is always slower than 2.2.7 (if you do not take into account the very long queries). Can there be something else in the join that has degraded performances a bit between the two versions ? 
Regarding the number of partitions I ran this : `query select count(*) from sys.shards where partition_ident <>''` which yields 696. Is that what you're looking for ?

**Comment by chaudum** [comment] 2018-03-16 09:19
You can query the information_schema.table_partitions table:

```sql
select count(*), schema_name || '.' || table_name as t from information_schema.table_partitions group by 2;
```

In general our internal benchmarks show that JOIN performance improved slightly from 2.2. to 2.3. Your setup with 2 CrateDB instances on the same host does not guarantee accurate benchmark results. Please use a distributed setup if you want to get more reliable numbers.

**Comment by echarlus** [comment] 2018-03-16 09:30
@chaudum Here's the result for the partitions: 
9 | sensor_location
38 | indicators
40 | message
Noted for the results, I'll move to a distributed setup soon and then be able to check again.
Let me know if you need more info.

**Comment by chaudum** [comment] 2018-03-16 14:43
@echarlus We've identified the problem and it might sound a bit counter-intuitive at first. The slow queries happen only if *all* data that needs to be collected is collected from shards on the same node that also performs the JOIN (nested loop operation). In your case that is the node you send the request to. The problem is, that iterating the right side of the nested loop is resulting in Lucene operations (if data of the right table is on same node) that have a certain overhead and it multiplies with the amount of shards that are involved.
You have quite some shards (312) that are involved in the JOIN which makes the huge difference.

That described problem can happen if you run a single node (always), or multiple nodes with N-1 replicas (1/N chance to happen). It does not happen if you have for example 3 nodes and 1 replica.

We are working on a block nested loop implementation of the JOIN over the next few weeks. This will eliminate the issue completely. Also, we already have the hash join implementation on master (available in upcoming 3.0 release which is already available via [nightly](https://cdn.crate.io/downloads/releases/nightly/) builds).
That's why we decided not to change anything for 2.3.x, also because it's a bit of an edge case.

I would be interested in how your JOIN queries would perform with the nightly build, if you could do a test run :)

Best, Christian

**Comment by echarlus** [comment] 2018-03-16 15:01
@chaudum thanks for the detailed explanation. I'm not sure I understand why you marked the issue as won't fix since you said you'll work on the block nested loop implementation ... or is that on master ? 
As far as nightly is concerned, I've tested it following the advice of @jodok on slack and it does indeed provide a huge performance improvement on the queries. 
My (very limited) benchark gave Nightly 3.0.0-201803110203-6a4e651 : 
0.099/0.053/0.113/0.065/0.067/0.072/0.087 AVG = 0,078  which is 4.4 times faster than 2.2.7. As a side note I did not encounter the very slow query that I see on 2.3.4 (issue you've identified).

In order to fix my issue without having to wait for the 3.0 I managed to change my data model and to migrate my production data to the new model in order to avoid the join. I now have much better performances on the whole application !

**Comment by chaudum** [comment] 2018-03-19 12:42
I'm glad to hear that the nightly release provides such a good performance boost. Also, that changing your schema has a great impact on your application :)

The `wontfix` means that we do not provide a "fix" for the edge case you've experienced on 2.3. Of course the new join implementation will eliminate the issue.

**Closed by chaudum** 2018-03-19 12:42 UTC
Labels: bug, feature: performance, won't fix
