### ISSUE TITLE
Windows release Zip archives contain duplicate files

### ISSUE THREAD

**Issue by amotl** [crate/crate#11105] opened 2021-03-05 11:37 UTC
Hi there,

when evaluating CrateDB on Windows (see also [1]), we observed that the zip release archives apparently contain duplicate start script and configuration files. So, when inflating them, the `unzip` program will prompt the user multiple times.

```sh
wget https://cdn.crate.io/downloads/releases/cratedb/x64_windows/crate-4.4.2.zip
unzip crate-4.4.2.zip
```

```text
replace crate-4.2.0-ee80a3c/bin/crate? [y]es, [n]o, [A]ll, [N]one, [r]ename: n
replace crate-4.2.0-ee80a3c/bin/crate.bat? [y]es, [n]o, [A]ll, [N]one, [r]ename: n
replace crate-4.2.0-ee80a3c/bin/crate.in.sh? [y]es, [n]o, [A]ll, [N]one, [r]ename: n
replace crate-4.2.0-ee80a3c/config/crate.yml? [y]es, [n]o, [A]ll, [N]one, [r]ename: n
replace crate-4.2.0-ee80a3c/config/log4j2.properties? [y]es, [n]o, [A]ll, [N]one, [r]ename: n
```

This issue might also block automated extraction processes when not being invoked with the `-o  overwrite files WITHOUT prompting` option like `unzip -o crate-4.4.2.zip`.

With kind regards,
Andreas.

[1] https://gist.github.com/amotl/69046c2c4a8e6744b1d6cde3f9523119

---

### More details

```
$ unzip -l crate-4.2.0.zip | grep bin/crate
     6379  07-07-2020 14:24   crate-4.2.0-ee80a3c/bin/crate
     3323  07-07-2020 14:25   crate-4.2.0-ee80a3c/bin/crate.bat
     3158  07-07-2020 14:25   crate-4.2.0-ee80a3c/bin/crate.in.sh
     6379  07-07-2020 14:24   crate-4.2.0-ee80a3c/bin/crate
     3323  07-07-2020 14:25   crate-4.2.0-ee80a3c/bin/crate.bat
     3158  07-07-2020 14:25   crate-4.2.0-ee80a3c/bin/crate.in.sh
     9763  07-07-2020 14:26   crate-4.2.0-ee80a3c/bin/crate-node
     7167  07-07-2020 14:26   crate-4.2.0-ee80a3c/bin/crate-node.bat
```

```
$ unzip -l crate-4.2.0.zip | grep config
        0  07-07-2020 14:24   crate-4.2.0-ee80a3c/config/
    27327  07-07-2020 14:24   crate-4.2.0-ee80a3c/config/crate.yml
     2044  07-07-2020 14:24   crate-4.2.0-ee80a3c/config/log4j2.properties
    27327  07-07-2020 14:24   crate-4.2.0-ee80a3c/config/crate.yml
     2044  07-07-2020 14:24   crate-4.2.0-ee80a3c/config/log4j2.properties
```

**Comment by mfussenegger** [comment] 2021-04-19 15:35
Ran into this while looking at gradle warning for the 7.0 upgrade. I think I've already a fix for it.

**Comment by amotl** [comment] 2021-05-06 20:55
Hi Mathias,

I tried to download and extract the Zip archive of the most recent release but it croaks with `error: invalid zip file with overlapped components (possible zip bomb)`.

```shell
$ wget https://cdn.crate.io/downloads/releases/cratedb/x64_windows/crate-4.5.1.zip
```

```shell
$ unzip crate-4.5.1.zip

Archive:  crate-4.5.1.zip
   creating: crate-4.5.1/
   creating: crate-4.5.1/bin/
  inflating: crate-4.5.1/bin/crate
  inflating: crate-4.5.1/bin/crate.bat
  inflating: crate-4.5.1/bin/crate.in.sh
   creating: crate-4.5.1/config/
  inflating: crate-4.5.1/config/crate.yml
  inflating: crate-4.5.1/config/log4j2.properties
error: invalid zip file with overlapped components (possible zip bomb)
```

With kind regards,
Andreas.

**Comment by BaurzhanSakhariev** [comment] 2021-06-10 11:22
UPD: Couldn't reproduce locally, was told that it might be one time issue with manual upload - waiting for the next release. If issue stays after automatic upload will investigate further.

**Comment by BaurzhanSakhariev** [comment] 2021-06-16 17:32
issue stays with the latest release(
```
wget https://cdn.crate.io/downloads/releases/cratedb/x64_windows/crate-4.5.2.zip
unzip  crate-4.5.2.zip
inflating: crate-4.5.2/bin/crate   
inflating: crate-4.5.2/bin/crate.bat  
inflating: crate-4.5.2/bin/crate.in.sh  
creating: crate-4.5.2/config/
inflating: crate-4.5.2/config/crate.yml  
inflating: crate-4.5.2/config/log4j2.properties  
```

**Comment by BaurzhanSakhariev** [comment] 2021-06-23 14:52
should be fixed by https://github.com/crate/crate/commit/a101fc9e7a268055e6653925f102f4fbd292824b
left the issue open - will check it again after the next release and then close

**Closed** 2021-07-13 12:05 UTC
Labels: complexity: 1-3, feature: packaging, platform: windows
