### ISSUE TITLE
Filtering on a column with `INDEX OFF` doesn't behave correctly

### ISSUE THREAD

**Issue by matriv** [crate/crate#14407] opened 2023-07-12 16:55 UTC
### CrateDB version

5.4.0

### Problem description

Filtering on a column with `INDEX OFF` doesn't behave consistently.

### Steps to Reproduce

```
cr> create table t(a int INDEX OFF);
CREATE OK, 1 row affected  (0.327 sec)
```

```
cr> select * from t where a = 1;
SQLParseException[Cannot search on field [a] since it is not indexed.]
```
this seems fine, but:

```
cr> select * from t where a > 1;
+---+
| a |
+---+
+---+
SELECT 0 rows in set (0.008 sec)
```
and:
```
cr> insert into t(a) values(2), (3);
INSERT OK, 2 rows affected  (0.043 sec)
cr> refresh table t;
REFRESH OK, 1 row affected  (0.003 sec)
cr> select * from t where a > 1;
+---+
| a |
+---+
+---+
SELECT 0 rows in set (0.003 sec)
cr> select * from t where a + 1 > 1;
+---+
| a |
+---+
| 3 |
| 2 |
+---+
SELECT 2 rows in set (0.008 sec)
```

**Comment by jeeminso** [comment] 2023-07-13 22:30
Thanks for reporting, it seems like `LuceneQueryBuilder` does not look for all references with indexType off (but only the ones immediately available to `EqOperator`).

**Comment by matriv** [comment] 2023-07-14 07:12
We can either throw an error for other comparisons, or implement a generic function filter, the current behavior is quite bad, as it returns 0 rows.
It would be great to check when this was introduced, or at least make sure it's not a `5.4.0` regression.

**Comment by jeeminso** [comment] 2023-07-14 13:21
> It would be great to check when this was introduced, or at least make sure it's not a 5.4.0 regression.

Compared to `5.3` there is a slight behaviour change (bug to bug):
```
select * from t where a > 1;                                                                                                                 
+---+
| a |
+---+
| 2 |
| 3 |
+---+
SELECT 2 rows in set (0.010 sec)
```

but I wouldn't call it a regression.

**Comment by jeeminso** [comment] 2023-07-14 13:43
> or implement a generic function filter

At least according to the document we should not fall back to generic filters:

https://crate.io/docs/crate/reference/en/5.3/general/ddl/fulltext-indices.html#sql-ddl-index-off
> Consider that a column without an index can only be used as a result column and will never produce a hit when queried.

But it looks like we allow `is null` to fall back to generic filters: https://github.com/crate/crate/pull/12679

**Comment by matriv** [comment] 2023-07-14 15:03
> > It would be great to check when this was introduced, or at least make sure it's not a 5.4.0 regression.
> 
> Compared to `5.3` there is a slight behaviour change (bug to bug):
> 
> ```
> select * from t where a > 1;                                                                                                                 
> +---+
> | a |
> +---+
> | 2 |
> | 3 |
> +---+
> SELECT 2 rows in set (0.010 sec)
> ```
> 
> but I wouldn't call it a regression.

I think it should, at least with 5.3 you got back the correct results and now 0 rows.

**Comment by matriv** [comment] 2023-07-14 15:05
@mfussenegger What's your opinion on this?
1. should we consider this a regression of 5.4.0?
2. should we use generic function filtering or throw an exception for any filtering on `INDEX OFF` cols?

**Comment by mfussenegger** [comment] 2023-07-17 07:34
> should we consider this a regression of 5.4.0?

```
❮ cr8 run-crate 5.3.x -- @crash <<EOF
create table tbl (x int index off);
insert into tbl (x) values (1), (10);
refresh table tbl;
select * from tbl;
select * from tbl where x > 5;
select * from tbl where x < 5;
EOF
```

Results in, same with 5.4.0:

```
CONNECT OK
CREATE OK, 1 row affected  (0.114 sec)
INSERT OK, 2 rows affected  (0.029 sec)
REFRESH OK, 1 row affected  (0.021 sec)
+----+
|  x |
+----+
|  1 |
| 10 |
+----+
SELECT 2 rows in set (0.010 sec)
+---+
| x |
+---+
+---+
SELECT 0 rows in set (0.006 sec)
+---+
| x |
+---+
+---+
SELECT 0 rows in set (0.002 sec)
```


So doesn't look like a regression to me.


> should we use generic function filtering or throw an exception for any filtering on INDEX OFF cols?


I'd tend towards generic function filter to match PostgreSQL behavior when you don't have an index. But I also wouldn't consider an error that says it's not supported as a bug. So either option would be fine as a fix.

**Comment by matriv** [comment] 2023-07-17 08:34
> So doesn't look like a regression to me.

Apologies, from: https://github.com/crate/crate/issues/14407#issuecomment-1635859338 I understood that in 5.3 it was returning rows.

**Comment by matriv** [comment] 2023-07-17 10:18
> I'd tend towards generic function filter to match PostgreSQL behavior when you don't have an index. But I also wouldn't consider an error that says it's not supported as a bug. So either option would be fine as a fix.

I'd also prefer the generic function filter over an error message, and also provide it (generic function filter) for `=` as well.

**Comment by jeeminso** [comment] 2023-07-17 22:32
It looks like up to `5.3.2`, the query works:

```
cr> select * from tbl where x > 5;                                                                                                                             
+----+
|  x |
+----+
| 10 |
+----+
SELECT 1 row in set (0.004 sec)
```

then starts to return nothing.

**Comment by mfussenegger** [comment] 2023-07-18 05:58
> It looks like up to 5.3.2, the query works:

Because 5.3.0-5.3.2 incorrectly indexed the values despite `INDEX OFF`. In 5.2.x it's also broken.

We should also look into making use of queries on doc-values if the index is not available. I suspect that would still be faster than using the generic function query.

**Comment by matriv** [comment] 2023-07-26 16:03
@jeeminso ^^ Then we need to provide generic function filter for those cases as well.

**Comment by jeeminso** [comment] 2023-08-08 20:16
`Like` and `ILIKE` should be fixed by https://github.com/crate/crate/pull/14561

**Comment by jeeminso** [comment] 2023-10-06 00:24
Another variant found:
```
cr> create table tbl (a int, b int index off, c int index off storage with (columnstore = false));                                                
CREATE OK, 1 row affected  (0.128 sec)
cr> insert into tbl values (1, 1, 1);                                                                                                             
INSERT OK, 1 row affected  (0.009 sec)
cr> select * from tbl where a = any([1]);                                                                                                         
+---+---+---+
| a | b | c |
+---+---+---+
| 1 | 1 | 1 |
+---+---+---+
SELECT 1 row in set (0.085 sec)
cr> select * from tbl where b = any([1]);                                                                                                         
+---+---+---+
| a | b | c |
+---+---+---+
+---+---+---+
SELECT 0 rows in set (0.003 sec)
cr> select * from tbl where c = any([1]);                                                                                                         
+---+---+---+
| a | b | c |
+---+---+---+
+---+---+---+
SELECT 0 rows in set (0.004 sec)
```

**Closed** 2023-11-06 14:18 UTC
Labels: bug
