### ISSUE TITLE
Restoring empty partitioned table from snapshot restores unrelated table

### ISSUE THREAD

**Issue by hammerhead** [crate/crate#14144] opened 2023-05-16 07:56 UTC
### CrateDB version

5.3.1

### CrateDB setup information

Fresh single-node Docker container

### Problem description

When creating a full snapshot, and restoring an empty partitioned table from it, a second (unrelated) table is restored as well.
Also, the empty partitioned table is not included in the snapshot's metadata when querying `sys.snapshots`.

### Steps to Reproduce

```sql
cr> CREATE REPOSITORY r1 TYPE s3 WITH (bucket = 'my-favorite-bucket', base_path = 'empty_tables_issue', access_key = '...', secret_key = '...');
CREATE OK, 1 row affected  (1.332 sec)
cr> CREATE TABLE empty (a INTEGER);
CREATE OK, 1 row affected  (0.350 sec)
cr> CREATE TABLE empty_but_partitioned (a INTEGER) PARTITIONED BY (a);
CREATE OK, 1 row affected  (0.046 sec)
cr> CREATE SNAPSHOT r1.s1 ALL;
CREATE OK, 1 row affected  (0.149 sec)
cr> SELECT * FROM sys.snapshots;
+------------------+----------+---------------+------+------------+---------------+---------+------------------+---------------+---------+
| concrete_indices | failures |      finished | name | repository |       started | state   | table_partitions | tables        | version |
+------------------+----------+---------------+------+------------+---------------+---------+------------------+---------------+---------+
| ["empty"]        | []       | 1684223054949 | s1   | r1         | 1684223054549 | SUCCESS | []               | ["doc.empty"] | 5.3.1   |
+------------------+----------+---------------+------+------------+---------------+---------+------------------+---------------+---------+
SELECT 1 row in set (0.205 sec)
```
Issue 1: `doc.empty` is returned in `tables`, but `doc.empty_but_partitioned` is not. In scenarios where I want to generate `DROP TABLE` statement from the snapshot's metadata for cleanup purposes prior to restoring, `doc.empty_but_partitioned` will be missed, leading to an error later on during restoring.

Continuing:
```sql
cr> DROP TABLE empty;
DROP OK, 1 row affected  (0.064 sec)
cr> DROP TABLE empty_but_partitioned;
DROP OK, 1 row affected  (0.031 sec)
cr> SELECT table_name
    FROM information_schema.tables
    WHERE table_schema = 'doc';
+------------+
| table_name |
+------------+
+------------+
SELECT 0 rows in set (0.004 sec)
cr> RESTORE SNAPSHOT r1.s1 TABLE empty_but_partitioned WITH ("wait_for_completion" = TRUE);
RESTORE OK, 1 row affected  (0.951 sec)
cr> SELECT table_name
    FROM information_schema.tables
    WHERE table_schema = 'doc';
+-----------------------+
| table_name            |
+-----------------------+
| empty_but_partitioned |
| empty                 |
+-----------------------+
SELECT 2 rows in set (0.005 sec)
```
Issue 2: `empty` is restored as well, although the scope of `RESTORE SNAPSHOT` was limited to `empty_but_partitioned`.

### Actual Result

See above.

### Expected Result

Issue 1: `empty_but_partitioned` is included in `sys.snapshot`'s `tables` column as well. This is already the case for partitioned tables that aren't empty.
Issue 2: `empty` is not restored.

**Comment by matriv** [comment] 2023-05-16 10:20
This is reproducible with `TYPE fs` local repos as well.
The issue is that we only have in hand `concreteIndices`, and for parted tables, until the 1st partition is created we don't have such a `concreteIndex`, only its metadata in the cluster state. Therefore, it doesn't show as a table in the `sys.snapshots`, but it's restored (even if not included) as it's included in the `ClusterState`.

**Comment by BaurzhanSakhariev** [comment] 2023-05-19 11:25
Probably having https://github.com/crate/crate/issues/11939 can help with the issue 1

**Comment by matriv** [comment] 2023-05-19 11:28
Definitely, in the current state, we don't save at all those empty parted tables in the snapshot metadata, so we cannot read it and provide this info in `sys.snapshots`.

**Comment by matriv** [comment] 2023-05-19 12:51
Thx for reporting the issue @hammerhead ! Fix for 2. is merged and will be available with next hotfix release.

Issue 1. is more complex and I've opened a new issue: https://github.com/crate/crate/issues/14165 to track it.

**Closed as completed** 2023-05-19 12:50 UTC
Labels: bug
