### ISSUE TITLE
UPDATE query crashes node (java.lang.StackOverflowError: null)

### ISSUE THREAD

**Issue by rps-v** [crate/crate#6928] opened 2018-02-19 08:23 UTC
**CrateDB version**: 2.1.6, 2.3.2

**JVM version**:
openjdk version "1.8.0_151"
OpenJDK Runtime Environment (build 1.8.0_151-8u151-b12-0ubuntu0.16.04.2-b12)
OpenJDK 64-Bit Server VM (build 25.151-b12, mixed mode)

**OS version / environment description**:
Ubuntu 16.04.2 LTS (GNU/Linux 4.4.0-47-generic x86_64)

**Problem description**:

UPDATE query crashes node.

```
[2018-02-16T23:00:01,485][ERROR][o.e.b.ElasticsearchUncaughtExceptionHandler] [s1] fatal error in thread [elasticsearch[s1][bulk][T#2]], exiting
java.lang.StackOverflowError: null
	at java.util.HashMap.hash(HashMap.java:339) ~[?:1.8.0_151]
	at java.util.HashMap.get(HashMap.java:557) ~[?:1.8.0_151]
	at java.util.Collections$UnmodifiableMap.get(Collections.java:1454) ~[?:1.8.0_151]
	at io.crate.operation.scalar.DateTruncFunction.intervalAsUnit(DateTruncFunction.java:192) ~[crate-app-2.1.6.jar:2.1.6]
	at io.crate.operation.scalar.DateTruncFunction.rounding(DateTruncFunction.java:170) ~[crate-app-2.1.6.jar:2.1.6]
	at io.crate.operation.scalar.DateTruncFunction.compile(DateTruncFunction.java:116) ~[crate-app-2.1.6.jar:2.1.6]
	at io.crate.operation.BaseImplementationSymbolVisitor.visitFunction(BaseImplementationSymbolVisitor.java:53) ~[crate-app-2.1.6.jar:2.1.6]
	at io.crate.operation.BaseImplementationSymbolVisitor.visitFunction(BaseImplementationSymbolVisitor.java:39) ~[crate-app-2.1.6.jar:2.1.6]
	at io.crate.analyze.symbol.Function.accept(Function.java:62) ~[crate-app-2.1.6.jar:2.1.6]
	at io.crate.analyze.symbol.SymbolVisitor.process(SymbolVisitor.java:32) ~[crate-app-2.1.6.jar:2.1.6]
	at io.crate.operation.InputFactory$Context.add(InputFactory.java:166) ~[crate-app-2.1.6.jar:2.1.6]
	at io.crate.executor.transport.TransportShardUpsertAction.resolveSymbols(TransportShardUpsertAction.java:319) ~[crate-app-2.1.6.jar:2.1.6]
	at io.crate.executor.transport.TransportShardUpsertAction.processGeneratedColumns(TransportShardUpsertAction.java:573) ~[crate-app-2.1.6.jar:2.1.6]
	at io.crate.executor.transport.TransportShardUpsertAction.prepareUpdate(TransportShardUpsertAction.java:381) ~[crate-app-2.1.6.jar:2.1.6]
	at io.crate.executor.transport.TransportShardUpsertAction.indexItem(TransportShardUpsertAction.java:240) ~[crate-app-2.1.6.jar:2.1.6]
	at io.crate.executor.transport.TransportShardUpsertAction.indexItem(TransportShardUpsertAction.java:261) ~[crate-app-2.1.6.jar:2.1.6]
        [repeated 100+ times]
```

**Steps to reproduce**:

SCHEMA:
```sql
CREATE TABLE IF NOT EXISTS "myschema"."notification" (
   "company_id" STRING GENERATED ALWAYS AS substr("group_id", 1, 6),
   "created_at" TIMESTAMP NOT NULL,
   "deleted_at" TIMESTAMP,
   "details" OBJECT (DYNAMIC) AS (
      "coordinates" GEO_POINT,
      "device_sn" STRING,
      "document_id" STRING,
      "geofence_id" STRING,
      "group_id" STRING,
      "limit" LONG,
      "seal_id" STRING,
      "speed" LONG,
      "user_id" STRING,
      "vehicle_id" STRING
   ),
   "group_id" STRING,
   "id" STRING NOT NULL,
   "month" TIMESTAMP GENERATED ALWAYS AS date_trunc('month', "created_at"),
   "persistent" BOOLEAN NOT NULL,
   "status" STRING NOT NULL,
   "timestamp" TIMESTAMP,
   "type" STRING NOT NULL,
   "updated_at" TIMESTAMP NOT NULL
)
CLUSTERED BY ("id") INTO 6 SHARDS
PARTITIONED BY ("month")
WITH (
   "allocation.max_retries" = 5,
   "blocks.metadata" = false,
   "blocks.read" = false,
   "blocks.read_only" = false,
   "blocks.write" = false,
   column_policy = 'dynamic',
   "mapping.total_fields.limit" = 1000,
   number_of_replicas = '1',
   "recovery.initial_shards" = 'quorum',
   refresh_interval = 1000,
   "routing.allocation.enable" = 'all',
   "routing.allocation.total_shards_per_node" = -1,
   "translog.durability" = 'REQUEST',
   "translog.flush_threshold_size" = 536870912,
   "translog.sync_interval" = 5000,
   "unassigned.node_left.delayed_timeout" = 60000,
   "warmer.enabled" = true,
   "write.wait_for_active_shards" = 'all'
)
```

QUERY
```sql
update "myschema"."notification"
set "deleted_at" = CURRENT_TIMESTAMP
where "timestamp" < 1518904800000 and "persistent" = false and "deleted_at" is null;
```

**NOTE**: Only fails if there are rows in table that match WHERE conditions.
**NOTE 2**: Transforming the UPDATE into a DELETE query does not crash the node - it works as expected.

**Use case**:

**Feature description**:

**Comment by matriv** [comment] 2018-02-19 16:01
Hello @rps-v,

I've tried with 2.1.6 and 2.3.2 versions and wasn't able to reproduce. I've created 100k sample records that match the `where` clause and all 100k of them were updated correctly.
Is it possible to send also data from this table (maybe rows that match the `where` clause)? If so please send to `marios AT crate.io`.

**Comment by matriv** [comment] 2018-02-19 16:17
@rps-v 
Can you try maybe to do the update but also add the `month` in the where clause so that you "access" only 1 (and then maybe 2-3 partitions) but not all of them?

**Comment by rps-v** [comment] 2018-02-20 11:35
@matriv 

Forgot to mention that it only seems to happen on multi-node clusters. The query works on our dev server (1 node), and my dev machine (also 1 node), but fails in production (5 node cluster: 2 data-only nodes, 3 data+masterable nodes).

I am now transferring a snapshot of the data but it will take some time before that completes.

**Comment by matriv** [comment] 2018-02-20 11:42
@rps-v ok, thanks for the info, will try to reproduce on a cluster also.
Would be great to have some real data though when you can, thanks!

**Comment by matriv** [comment] 2018-02-21 10:43
@rps-v Unfortunately couldn't reproduce also on a 8-node cluster.
Waiting for your data.

**Comment by rps-v** [comment] 2018-02-21 12:07
@matriv Finally managed to get the data and replicate the issue locally. Check your email 😉

**Comment by matriv** [comment] 2018-02-21 12:55
@rps-v Thank you!  Received and reproducable. Will continue the investigation.

**Comment by matriv** [comment] 2018-02-21 13:42
@rps-v The document that causes the issue is with _id: AWGOgCvq3g58eQ8H13w2.
So as quick workaround take a backup of this document with:
```select * from "tracknamic"."notification" where _id='AWGOgCvq3g58eQ8H13w2';```
and saving the output. Then delete it: ```delete from "tracknamic"."notification" where _id='AWGOgCvq3g58eQ8H13w2';``` and insert it again: ```insert into "tracknamic"."notification" (....) values(....)```

**Comment by rps-v** [comment] 2018-02-21 14:20
@matriv Thanks for the workaround, however it doesn't seem to work on the production cluster.

That document only contains 1 row, as reported by `select *`. Running the `select count(*) from .. where _id='AWGOgCvq3g58eQ8H13w2'` query returns 0 or 1, randomly
 Also tried the `delete` query, with no results. It always returns 0 rows affected and the data is still there.
Can we delete the document using other methods ? Maybe the ES API ?

**Comment by matriv** [comment] 2018-02-21 14:58
Can you try to `refresh` the table first: ```REFRESH TABLE "tracknamic"."notification"```;
You still can't delete it?

For ES API you need to enable it with ```es.api.enabled: true``` in your config file.
Then you can delete the doc with ```curl -XDELETE host:port/tracknamic..partitioned.notification.04732d1p70s3cdpi60o30c1g/_doc/AWGOgCvq3g58eQ8H13w2```

Of course the partition id you see here is from the data you've sent via email, in production can be different.

**Comment by matriv** [comment] 2018-02-21 16:38
@rps-v You can also try to do: ```OPTIMIZE TABLE "tracknamic"."notification" WITH (max_num_segments=1)```

**Comment by rps-v** [comment] 2018-02-22 08:23
@matriv 

Tried `REFRESH` and `OPTIMIZE`, they did nothing. Also tried to delete via ES API and I always get `404 Not Found`, even though the index and id is correct (it randomly appears when running `GET /tracknamic.notification/_search?q=id:a8c3ccd0-c6df-46ee-8fba-f3cffee57283` - same as executing the `SELECT` SQL query).
Could it be because other queries are running against that table (SELECTs mostly, but there could be INSERTs also) ?

**Comment by matriv** [comment] 2018-02-22 14:02
@rps-v It seems somehow that this document exists in one of the replica shards but not on the primary. `DELETE FROM "tracknamic"."notification" WHERE id='a8c3ccd0-c6df-46ee-8fba-f3cffee57283'` is also unsuccessful?

**Comment by rps-v** [comment] 2018-02-22 17:52
@matriv Yes, tried that already - it always returns `0 rows affected`.

**Comment by seut** [comment] 2018-02-26 13:29
@rps-v Your state is a bit strange, did you have any node failures recently while inserting new documents? Also could you maybe try to disable and re-enable replicas by:
`alter table "tracknamic"."notification" set (number_of_replicas=0);`
`alter table "tracknamic"."notification" set (number_of_replicas=1);`

to see if this would solve it?

**Comment by rps-v** [comment] 2018-02-27 07:53
@seut That seems to have fixed it ! The document is now gone and the update query works without crashing.

Thank you !

**Comment by seut** [comment] 2018-02-27 08:11
@rps-v Great to hear that this solves your issue. Anyway this should not happen even when a node crashes with in-flight inserts. I'm closing this issue for now but also try to investigate how documents could get into this persistent version state. Thx for reporting.

**Closed by seut** 2018-02-27 08:11 UTC
Labels: needs feedback
