### ISSUE TITLE
Documentation missing for blob data backup/restore

### ISSUE THREAD

**Issue by daniel11c** [crate/crate#7940] opened 2018-11-29 15:44 UTC
**Use case**:
We need full backup of our data (including blob data). We can do proper backups with snapshot and restore but blob data is not included in snapshots.
We can also do rsync backups of blob files, but this won't help us to restore exact blob tables we had before (we have only blob files without metadata - eg: last_modified column)

**Feature description**:
Please either create a feature to backup/restore blobs or post proper documentation on how metadata can be restored. I see that right now there is no option to create a blob table with a given index_uuid and index_path so we can reuse additional files copied with rsync (_state/state*.st files) in order to restore entire blob table.

**Comment by mfussenegger** [comment] 2018-11-29 16:01
There is currently not support for blob backup built-in. This is a duplicate of https://github.com/crate/crate/issues/5939

**Closed by mfussenegger** 2018-11-29 16:01 UTC
