### ISSUE TITLE
JSON validation does not catch embedded quotes

### ISSUE THREAD

**Issue by michael-card** [crate/crate#6634] opened 2017-12-06 18:16 UTC
**CrateDB version**:
2.2.4

**JVM version**:
1.8

**OS version / environment description**:
Mac OS X  Sierra 10.12.6

**Problem description**:
When importing data, sometimes the JSON validation in CrateDB does not catch embedded quotes in a string field that make the JSON invalid and if that happens the invalid JSON is passed on and CrateDB attempts to insert it into elasticsearch resulting in an exception which does not include the offending line number or any indication that the problem is due to invalid JSON, i.e.
SQLActionException[NotXContentException: Compressor detection can only be called on some xcontent bytes or compressed xcontent bytes]

SQLActionException[NotXContentException: Compressor detection can only be called on some xcontent bytes or compressed xcontent bytes]

**Steps to reproduce**:
First create a table in crash like this:

CREATE TABLE review (id STRING PRIMARY KEY, aboutid STRING INDEX USING PLAIN, rating INTEGER, revlanguage STRING, revtext STRING INDEX USING FULLTEXT);

Next, attempt to copy the record from the attached file into the table like this:

COPY review FROM 'file:///path/walmart_review_9304.json'

[walmart_review_9034.json.zip](https://github.com/crate/crate/files/1536351/walmart_review_9034.json.zip)

**Use case**:

**Feature description**:

**Comment by mikethebeer** [comment] 2017-12-07 10:00
@michael-card Thanks for the detailed description. This is an **expected/known behavior** since for performance reasons CrateDB does not do JSON validation before ingesting the data. I understand your concerns that it's hard to narrow down the root cause of the issue however, the main use-case of `COPY FROM` lies in the backup/restore process of data where data initially is exported from CrateDB via `COPY TO` and imported back again via `COPY FROM`. This will always produce valid JSON so the validation process would only harm the performance here.
I hope this answers your question.

**Comment by mikethebeer** [comment] 2017-12-11 09:02
Closing this since the behavior is expected because of performance reasons.

**Closed by mikethebeer** 2017-12-11 09:02 UTC
Labels: question
