### ISSUE TITLE
return all not any

### ISSUE THREAD

**Issue by junphine** [crate/crate#7575] opened 2018-08-09 03:21 UTC
**CrateDB version**: 3.0.0

**Problem description**:

when search condition use   match(field_keywords,'ios android') using best_fields with (operator='and') 
some of the result only contains ios or android , not both.
 
Or there is some solution to return both ios and android?

**Comment by joemoe** [comment] 2018-08-09 06:51
hi @junphine, can you provide the exact query and maybe also some sample data?

**Comment by junphine** [comment] 2018-08-09 10:35
`SELECT field_resume_keywords FROM "hr"."content_resume"  
where match(field_resume_keywords,'ios android') using best_fields with (operator='and')  and field_resume_status!=1 order by _score desc   limit 100;`


result:

field_resume_keywords
--
android ios 研发工程师
IOS &Android 工程师
android 和ios开发工程师
ios  leader
android技术部  \|  android工程师
Android  leader
android  leader
iOS team leader / iOS架构师
iOS leader
iOS Leader
IOS Leader
IOS Leader
iOS leader
IOS 开发
Ios Leader
ios leader
iOS leader
iOS 开发
IOS Leader
IOS Leader
iOS Leader
iOS 开发

**Comment by junphine** [comment] 2018-08-09 10:39
Unconventional， the data is insert use elasticsearch rest  api，not crate sql.

**Comment by seut** [comment] 2018-08-09 11:06
The usage of the ES API is deprecated and was always kinda unsupported (but was mostly safe for read operations).
As we cannot reproduce this issue using your supplied query and data set when using CrateDB's SQL for all operations (table creation, write, read), I'm closing this now.
Feel free to reopen if this still appears when using SQL for everything.

**Comment by junphine** [comment] 2018-08-10 03:53
I use crate sql to create table,insert data.
the result is same.

**Comment by seut** [comment] 2018-08-10 08:00
Please tell us the steps to reproduce it.

**Comment by junphine** [comment] 2018-08-13 06:48
simple produce data: 
create table resume(
 title string INDEX USING fulltext
);
insert INTO resume(title) values('android'),('ios'),('android both ios'),('ios before android');

then query:

SELECT * FROM "doc"."resume"  where match(title,'ios android')  using best_fields with (operator='and') 

or use minimum_should_match
SELECT * FROM "doc"."resume"  where match(title,'ios android')  using best_fields with (minimum_should_match=2) 

the result is：

ios before android
android both ios
ios
android

I expect result ：

ios before android
android both ios

**Comment by junphine** [comment] 2018-08-13 06:52
use elasticsearch _search dsl ,the result is right.
the mapping is:
 "properties" : {
          "title" : {
            "type" : "text",
            "analyzer" : "standard"
          }
        }

**Comment by seut** [comment] 2018-08-14 10:06
@junphine Thanks for the detailed information, we can reproduce this issue now and are working on a fix.

**Comment by seut** [comment] 2018-08-14 13:40
@junphine We've fixed this by https://github.com/crate/crate/pull/7586, it will be released with the next 3.0 hotfix release (and the next nightly snapshot release). Thanks for reporting!

**Closed by seut** 2018-08-14 13:40 UTC
