### ISSUE TITLE
Unable to create new partitions after rolling upgrade on table that had `index.warmer.enabled = TRUE`

### ISSUE THREAD

**Issue by hammerhead** [crate/crate#17150] opened 2024-12-17 12:30 UTC
### CrateDB version

5.7.5 / 5.8.5 / 5.9.5

### CrateDB setup information

Three nodes locally using Docker compose:

```yaml
services:
  cratedb01:
    image: crate:5.7.5
    ports:
      - "4201:4200"
      - "5532:5432"
    volumes:
      - /tmp/crate/hot-01:/data
    command: ["crate",
              "-Ccluster.name=crate-docker-cluster",
              "-Cnode.name=cratedb01",
              "-Cnetwork.host=_site_",
              "-Cdiscovery.seed_hosts=cratedb02,cratedb03",
              "-Ccluster.initial_master_nodes=cratedb01,cratedb02,cratedb03",
              "-Cgateway.expected_nodes=3",
              "-Cgateway.recover_after_nodes=2"]

  cratedb02:
    image: crate:5.7.5
    ports:
      - "4202:4200"
      - "5632:5432"
    volumes:
      - /tmp/crate/hot-02:/data
    command: ["crate",
              "-Ccluster.name=crate-docker-cluster",
              "-Cnode.name=cratedb02",
              "-Cnetwork.host=_site_",
              "-Cdiscovery.seed_hosts=cratedb01,cratedb03",
              "-Ccluster.initial_master_nodes=cratedb01,cratedb02,cratedb03",
              "-Cgateway.expected_nodes=3",
              "-Cgateway.recover_after_nodes=2"]

  cratedb03:
    image: crate:5.7.5
    ports:
      - "4203:4200"
      - "5732:5432"
    volumes:
      - /tmp/crate/hot-03:/data
    command: ["crate",
              "-Ccluster.name=crate-docker-cluster",
              "-Cnode.name=cratedb03",
              "-Cnetwork.host=_site_",
              "-Cdiscovery.seed_hosts=cratedb01,cratedb02",
              "-Ccluster.initial_master_nodes=cratedb01,cratedb02,cratedb03",
              "-Cgateway.expected_nodes=3",
              "-Cgateway.recover_after_nodes=2"]

```

### Problem description

A table was created on 5.7.5 with `warmer.enabled = TRUE`. After resetting that parameter and a rolling upgrade to 5.8.5, creating new partitions on that table is no longer possible.

### Steps to Reproduce

Start with a three-node cluster, all nodes on 5.7.5. Then create a table with `warmer.enabled = TRUE` and populate it:

```sql
CREATE TABLE IF NOT EXISTS metrics (
   "ts" TIMESTAMP WITH TIME ZONE NOT NULL,
   "ts_month" TIMESTAMP WITH TIME ZONE GENERATED ALWAYS AS date_trunc('month', "ts") NOT NULL,
   "value" INTEGER,
   PRIMARY KEY ("ts", "ts_month")
)
PARTITIONED BY ("ts_month")
WITH ("warmer.enabled" = TRUE);

INSERT INTO metrics (ts, value) VALUES ('2024-02-01 12:00:00', 1);
INSERT INTO metrics (ts, value) VALUES ('2024-02-01 13:00:00', 1);
INSERT INTO metrics (ts, value) VALUES ('2024-02-01 14:00:00', 1);
```

Next, we reset `warmer.enable` back to the default value:
```sql
ALTER TABLE metrics RESET ("warmer.enabled");
```

Now, perform a rolling upgrade to 5.8.5 by updating the CrateDB version number in the Docker compose configuration one by one.
**Important**: In each intermediate state (i.e. after updating each node), perform further `INSERT` statements on old and new partitions. Then continue with the next node until the cluster is fully on 5.8.5.

Once the cluster is on 5.8.5, try creating yet another new partition:
```sql
-- would create a new partition
INSERT INTO metrics (ts, value) VALUES ('2027-02-01 20:00:00', 1);
```

Upgrading further to 5.9.5 doesn't change the issue.

**Workaround**: A full cluster restart appears to resolve the issue.

### Actual Result

The partition is not created and an exception is thrown:
```
io.crate.exceptions.SQLParseException: unknown setting [index.warmer.enabled] please check that any required plugins are installed, or check the breaking changes documentation for removed settings
	at io.crate.exceptions.SQLExceptions.esToCrateException(SQLExceptions.java:211)
	at io.crate.exceptions.SQLExceptions.prepareForClientTransmission(SQLExceptions.java:200)
	at io.crate.rest.action.SqlHttpHandler.sendResponse(SqlHttpHandler.java:162)
	at io.crate.rest.action.SqlHttpHandler.lambda$channelRead0$0(SqlHttpHandler.java:117)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2194)
	at io.crate.rest.action.RestRowCountReceiver.fail(RestRowCountReceiver.java:84)
	at io.crate.action.sql.RowConsumerToResultReceiver.accept(RowConsumerToResultReceiver.java:63)
	at io.crate.planner.operators.InsertFromValues.lambda$execute$2(InsertFromValues.java:304)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2194)
	at io.crate.action.FutureActionListener.onFailure(FutureActionListener.java:40)
	at org.elasticsearch.action.support.master.TransportMasterNodeAction$AsyncSingleAction.lambda$doStart$2(TransportMasterNodeAction.java:173)
	at org.elasticsearch.action.ActionListener$7.onFailure(ActionListener.java:294)
	at org.elasticsearch.action.ActionListener$2.onFailure(ActionListener.java:106)
	at org.elasticsearch.action.ActionListener.accept(ActionListener.java:55)
	at org.elasticsearch.action.ActionListener.accept(ActionListener.java:38)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2194)
	at org.elasticsearch.cluster.AckedClusterStateUpdateTask.onFailure(AckedClusterStateUpdateTask.java:96)
	at org.elasticsearch.cluster.service.MasterService$SafeClusterStateTaskListener.onFailure(MasterService.java:477)
	at org.elasticsearch.cluster.service.MasterService$TaskOutputs.notifyFailedTasks(MasterService.java:404)
	at org.elasticsearch.cluster.service.MasterService.runTasks(MasterService.java:176)
	at org.elasticsearch.cluster.service.MasterService.lambda$doStart$0(MasterService.java:121)
	at org.elasticsearch.cluster.service.TaskBatcher.runIfNotProcessed(TaskBatcher.java:170)
	at org.elasticsearch.cluster.service.BatchedTask.run(BatchedTask.java:70)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:231)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:194)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1570)
Caused by: java.lang.IllegalArgumentException: unknown setting [index.warmer.enabled] please check that any required plugins are installed, or check the breaking changes documentation for removed settings
	at org.elasticsearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:421)
	at org.elasticsearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:362)
	at org.elasticsearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:333)
	at org.elasticsearch.indices.IndicesService.createIndexService(IndicesService.java:437)
	at org.elasticsearch.indices.IndicesService.createIndex(IndicesService.java:364)
	at org.elasticsearch.action.admin.indices.create.TransportCreatePartitionsAction.executeCreateIndices(TransportCreatePartitionsAction.java:237)
	at org.elasticsearch.action.admin.indices.create.TransportCreatePartitionsAction.lambda$new$0(TransportCreatePartitionsAction.java:102)
	at org.elasticsearch.cluster.service.MasterService.executeTasks(MasterService.java:665)
	at org.elasticsearch.cluster.service.MasterService.calculateTaskOutputs(MasterService.java:280)
	at org.elasticsearch.cluster.service.MasterService.runTasks(MasterService.java:175)
	... 8 more
```

### Expected Result

Successful creation of a new partition.

**Comment by BaurzhanSakhariev** [comment] 2024-12-17 12:34
Maybe related to https://github.com/crate/crate/pull/16356 (we had a regression caused by removal of the `warmer.enabled `setting)

**Comment by romseygeek** [comment] 2024-12-17 12:59
The fix in #16356 checks that the index in question was created in an older version; I think the fact that this is a new partition is bypassing that check, and so rather than logging and ignoring the warning we get an exception.

I think ideally we would just remove the offending setting from the index metadata, but that may get complicated in mixed-version clusters.

**Comment by BaurzhanSakhariev** [comment] 2024-12-23 15:40
Looks like template is not being upgraded. 

I thought it's somehow related to https://github.com/crate/crate/commit/c8edfff8fe7713b071841b9db1aea26e3f500245 but reproduction scenario in https://github.com/crate/crate-qa/pull/330 passes without RESET, ie it RESET seems to be somehow important to cause an error.

Added some dummy `throw IllegalArgumentException`: in the template upgrade code and run crate-qa with   UpgradePath('5.7.x', '/path/to/local/crate'), and got

```
Caused by: java.lang.IllegalArgumentException: Template upgrade!
        at org.elasticsearch.plugins.MetadataUpgrader.lambda$new$1(MetadataUpgrader.java:49) ~[crate-server-5.10.0.jar:?]
        at org.elasticsearch.gateway.GatewayMetaState.applyPluginUpgraders(GatewayMetaState.java:272) ~[crate-server-5.10.0.jar:?]
        at org.elasticsearch.gateway.GatewayMetaState.upgradeMetadata(GatewayMetaState.java:230) ~[crate-server-5.10.0.jar:?]
        at org.elasticsearch.gateway.GatewayMetaState.upgradeMetadataForNode(GatewayMetaState.java:210) ~[crate-server-5.10.0.jar:?]
        at org.elasticsearch.gateway.GatewayMetaState.start(GatewayMetaState.java:138) ~[crate-server-5.10.0.jar:?]
        at org.elasticsearch.node.Node.start(Node.java:1051) ~[crate-server-5.10.0.jar:?]
```
so template upgrade code is being called in `GatewayMetaState`. Checking what's special about RESET case. It's a bit strange that it matters given that warmer.enabled has default value (but set explicitly) and RESET is basically no-op in such case.

**Comment by BaurzhanSakhariev** [comment] 2024-12-24 10:11
>Checking what's special about RESET case.

There is another [issue](https://github.com/crate/support/issues/509) where version created might be a problem for partitioned tables and according to @jeeminso he managed to get multiple versions created values for a partitioned table using alter table statements

Nevertheless, this should work regardless of version_created being problematic or not - we must ensure that upgrade logic kicks in when required. 

This means that ideally not only templates must be fixed via upgrade in proper place (this issue) but also indices must always go through upgrade (when needed) on mixed clusters. Hence, https://github.com/crate/crate/pull/16356 must be reverted and instead we need do upgrade index metadata in a way that we never even encounter unknown settings after upgrade.

**Closed** 2024-12-31 08:21 UTC
Labels: bug
