### ISSUE TITLE
Upgrade from 3.6.x to 4.0.9: invalid index.write.wait_for_active_shards

### ISSUE THREAD

**Issue by fetzerms** [crate/crate#9450] opened 2019-12-11 16:45 UTC
**CrateDB version**: 4.0.9

**Environment description**:

 - JVM version: openjdk version "11.0.5" 2019-10-15
 - Kernel: Linux de1 4.19.0-0.bpo.6-amd64 #1 SMP Debian 4.19.67-2+deb10u2~bpo9+1 (2019-11-12) x86_64 GNU/Linux
 - Distribution: Debian 9
 - Number of nodes; 2

**Problem description**:
I upgraded both of my nodes to v4.0.9 from v3.6.x. Both nodes were in the same cluster and only had one table. After migrating to the new settings in the .yml configuration, one of my nodes now refuses to start:

```
Dec 11 17:36:34 de1 crate[9129]: org.elasticsearch.transport.RemoteTransportException: [de1][my.ip.add.ress:4300][internal:cluster/coordination/join]
Dec 11 17:36:34 de1 crate[9129]: Caused by: java.lang.IllegalArgumentException: invalid index.write.wait_for_active_shards[2]: cannot be greater than number of shard copies [1]
Dec 11 17:36:34 de1 crate[9129]:         at org.elasticsearch.cluster.metadata.IndexMetaData$Builder.build(IndexMetaData.java:1088) ~[crate-app.jar:4.0.9]
Dec 11 17:36:34 de1 crate[9129]:         at org.elasticsearch.cluster.metadata.MetaData$Builder.put(MetaData.java:877) ~[crate-app.jar:4.0.9]
Dec 11 17:36:34 de1 crate[9129]:         at org.elasticsearch.cluster.metadata.MetaData$Builder.updateNumberOfReplicas(MetaData.java:1002) ~[crate-app.jar:4.0.9]
```

My other node does not seem to bootstrap either. I cannot see and/or use any of my previous tables. Is there any way to recover the data? Maybe even form the lucene index?

**Steps to reproduce**:

I am not sure.

**Comment by mfussenegger** [comment] 2019-12-12 08:59
It looks like your table has some meta data that is no longer valid. Since the node didn't start up I think the data migration of 4.0 didn't kick in yet, so you're still able to go back to 3.x again.

So you could try going back to 3.x, start up the nodes and fix the meta data by running alter table on your table:

`ALTER TABLE ... SET ("write.wait_for_active_shards" = 1)`

And after that retry the upgrade.


Could you also post your `crate.yml` file?

**Comment by fetzerms** [comment] 2019-12-13 03:22
My crate.yml file on that node:

path.data: /opt/crate-data
gateway.expected_nodes: 1              # Total amount of nodes
gateway.recover_after_nodes: 1         # More than half of the nodes
auth.host_based.enabled: true
auth:
  host_based:
    config:
      0:
        user: crate
        address: _local_
        method: trust
      99:
        method: password
cluster.name: rdb
node.name: de1.rdb.my.fqdn
network.bind_host: 0.0.0.0
network.publish_host: my.ip.add.ress
network.host: my.ip.add.ress

As it cannot join the cluster (and the 2-node cluster does not start without it), I tried to strip down the config as much as possible and removed all the cluster and host discovery entries. The data is replicated onto all the nodes.

**Comment by fetzerms** [comment] 2019-12-13 03:24
After downgrade to 3.x:

Dec 13 04:14:13 de1 crate[41918]: org.elasticsearch.ElasticsearchException: java.io.IOException: failed to read [id:103, file:/opt/crate-data/nodes/0/_state/global-103.st]
Dec 13 04:14:13 de1 crate[41918]:         at org.elasticsearch.ExceptionsHelper.maybeThrowRuntimeAndSuppress(ExceptionsHelper.java:164) ~[crate-app.jar:3.3.6]
Dec 13 04:14:13 de1 crate[41918]:         at org.elasticsearch.gateway.MetaDataStateFormat.loadLatestState(MetaDataStateFormat.java:304) ~[crate-app.jar:3.3.6]
Dec 13 04:14:13 de1 crate[41918]:         at org.elasticsearch.gateway.MetaStateService.loadGlobalState(MetaStateService.java:111) ~[crate-app.jar:3.3.6]
Dec 13 04:14:13 de1 crate[41918]:         at org.elasticsearch.gateway.MetaStateService.loadFullState(MetaStateService.java:56) ~[crate-app.jar:3.3.6]
Dec 13 04:14:13 de1 crate[41918]:         at org.elasticsearch.gateway.GatewayMetaState.<init>(GatewayMetaState.java:86) [crate-app.jar:3.3.6]
Dec 13 04:14:13 de1 crate[41918]:         at org.elasticsearch.node.Node.<init>(Node.java:487) [crate-app.jar:3.3.6]
Dec 13 04:14:13 de1 crate[41918]:         at io.crate.node.CrateNode.<init>(CrateNode.java:65) [crate-app.jar:3.3.6]
Dec 13 04:14:13 de1 crate[41918]:         at org.elasticsearch.bootstrap.BootstrapProxy$1.<init>(BootstrapProxy.java:193) [crate-app.jar:3.3.6]
Dec 13 04:14:13 de1 crate[41918]:         at org.elasticsearch.bootstrap.BootstrapProxy.setup(BootstrapProxy.java:193) [crate-app.jar:3.3.6]
Dec 13 04:14:13 de1 crate[41918]:         at org.elasticsearch.bootstrap.BootstrapProxy.init(BootstrapProxy.java:264) [crate-app.jar:3.3.6]
Dec 13 04:14:13 de1 crate[41918]:         at io.crate.bootstrap.CrateDB.init(CrateDB.java:155) [crate-app.jar:3.3.6]
Dec 13 04:14:13 de1 crate[41918]:         at io.crate.bootstrap.CrateDB.execute(CrateDB.java:135) [crate-app.jar:3.3.6]
Dec 13 04:14:13 de1 crate[41918]:         at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:85) [crate-app.jar:3.3.6]
Dec 13 04:14:13 de1 crate[41918]:         at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124) [elasticsearch-cli-6.5.1.jar:3.3.6]
Dec 13 04:14:13 de1 crate[41918]:         at org.elasticsearch.cli.Command.main(Command.java:90) [elasticsearch-cli-6.5.1.jar:3.3.6]
Dec 13 04:14:13 de1 crate[41918]:         at io.crate.bootstrap.CrateDB.main(CrateDB.java:88) [crate-app.jar:3.3.6]
Dec 13 04:14:13 de1 crate[41918]:         at io.crate.bootstrap.CrateDB.main(CrateDB.java:81) [crate-app.jar:3.3.6]
Dec 13 04:14:13 de1 crate[41918]: Caused by: java.io.IOException: failed to read [id:103, file:/opt/crate-data/nodes/0/_state/global-103.st]
Dec 13 04:14:13 de1 crate[41918]:         at org.elasticsearch.gateway.MetaDataStateFormat.loadLatestState(MetaDataStateFormat.java:298) ~[crate-app.jar:3.3.6]
Dec 13 04:14:13 de1 crate[41918]:         ... 15 more
Dec 13 04:14:13 de1 crate[41918]: Caused by: java.lang.IllegalArgumentException: Unexpected field [cluster_uuid_committed]
Dec 13 04:14:13 de1 crate[41918]:         at org.elasticsearch.cluster.metadata.MetaData$Builder.fromXContent(MetaData.java:1266) ~[crate-app.jar:3.3.6]
Dec 13 04:14:13 de1 crate[41918]:         at org.elasticsearch.cluster.metadata.MetaData$1.fromXContent(MetaData.java:1296) ~[crate-app.jar:3.3.6]
Dec 13 04:14:13 de1 crate[41918]:         at org.elasticsearch.cluster.metadata.MetaData$1.fromXContent(MetaData.java:1287) ~[crate-app.jar:3.3.6]
Dec 13 04:14:13 de1 crate[41918]:         at org.elasticsearch.gateway.MetaDataStateFormat.read(MetaDataStateFormat.java:196) ~[crate-app.jar:3.3.6]
Dec 13 04:14:13 de1 crate[41918]:         at org.elasticsearch.gateway.MetaDataStateFormat.loadLatestState(MetaDataStateFormat.java:294) ~[crate-app.jar:3.3.6]
Dec 13 04:14:13 de1 crate[41918]:         ... 15 more
Dec 13 04:14:13 de1 crate[41918]: [2019-12-13T04:14:13,915][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [de1.rdb.my.fqdn] uncaught exception in thread [main]
Dec 13 04:14:13 de1 crate[41918]: org.elasticsearch.bootstrap.StartupException: ElasticsearchException[java.io.IOException: failed to read [id:103, file:/opt/crate-data/nodes/0/_state/global-103.st]]; nested: IOException[failed to read [id:103, file:/opt/crate-data/nodes/0/_state/global-103.st]]; nested: IllegalArgumentException[Unexpected field [cluster_uuid_committed]];
Dec 13 04:14:13 de1 crate[41918]:         at org.elasticsearch.bootstrap.StartupExceptionProxy.<init>(StartupExceptionProxy.java:31) ~[crate-app.jar:3.3.6]
Dec 13 04:14:13 de1 crate[41918]:         at io.crate.bootstrap.CrateDB.init(CrateDB.java:159) ~[crate-app.jar:3.3.6]
Dec 13 04:14:13 de1 crate[41918]:         at io.crate.bootstrap.CrateDB.execute(CrateDB.java:135) ~[crate-app.jar:3.3.6]
Dec 13 04:14:13 de1 crate[41918]:         at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:85) ~[crate-app.jar:3.3.6]
Dec 13 04:14:13 de1 crate[41918]:         at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124) ~[elasticsearch-cli-6.5.1.jar:3.3.6]
Dec 13 04:14:13 de1 crate[41918]:         at org.elasticsearch.cli.Command.main(Command.java:90) ~[elasticsearch-cli-6.5.1.jar:3.3.6]
Dec 13 04:14:13 de1 crate[41918]:         at io.crate.bootstrap.CrateDB.main(CrateDB.java:88) ~[crate-app.jar:3.3.6]
Dec 13 04:14:13 de1 crate[41918]:         at io.crate.bootstrap.CrateDB.main(CrateDB.java:81) ~[crate-app.jar:3.3.6]
Dec 13 04:14:13 de1 crate[41918]: Caused by: org.elasticsearch.ElasticsearchException: java.io.IOException: failed to read [id:103, file:/opt/crate-data/nodes/0/_state/global-103.st]
Dec 13 04:14:13 de1 crate[41918]:         at org.elasticsearch.ExceptionsHelper.maybeThrowRuntimeAndSuppress(ExceptionsHelper.java:164) ~[crate-app.jar:3.3.6]
Dec 13 04:14:13 de1 crate[41918]:         at org.elasticsearch.gateway.MetaDataStateFormat.loadLatestState(MetaDataStateFormat.java:304) ~[crate-app.jar:3.3.6]
Dec 13 04:14:13 de1 crate[41918]:         at org.elasticsearch.gateway.MetaStateService.loadGlobalState(MetaStateService.java:111) ~[crate-app.jar:3.3.6]
Dec 13 04:14:13 de1 crate[41918]:         at org.elasticsearch.gateway.MetaStateService.loadFullState(MetaStateService.java:56) ~[crate-app.jar:3.3.6]
Dec 13 04:14:13 de1 crate[41918]:         at org.elasticsearch.gateway.GatewayMetaState.<init>(GatewayMetaState.java:86) ~[crate-app.jar:3.3.6]
Dec 13 04:14:13 de1 crate[41918]:         at org.elasticsearch.node.Node.<init>(Node.java:487) ~[crate-app.jar:3.3.6]
Dec 13 04:14:13 de1 crate[41918]:         at io.crate.node.CrateNode.<init>(CrateNode.java:65) ~[crate-app.jar:3.3.6]
Dec 13 04:14:13 de1 crate[41918]:         at org.elasticsearch.bootstrap.BootstrapProxy$1.<init>(BootstrapProxy.java:193) ~[crate-app.jar:3.3.6]
Dec 13 04:14:13 de1 crate[41918]:         at org.elasticsearch.bootstrap.BootstrapProxy.setup(BootstrapProxy.java:193) ~[crate-app.jar:3.3.6]
Dec 13 04:14:13 de1 crate[41918]:         at org.elasticsearch.bootstrap.BootstrapProxy.init(BootstrapProxy.java:264) ~[crate-app.jar:3.3.6]
Dec 13 04:14:13 de1 crate[41918]:         at io.crate.bootstrap.CrateDB.init(CrateDB.java:155) ~[crate-app.jar:3.3.6]
Dec 13 04:14:13 de1 crate[41918]:         ... 6 more
Dec 13 04:14:13 de1 crate[41918]: Caused by: java.io.IOException: failed to read [id:103, file:/opt/crate-data/nodes/0/_state/global-103.st]
Dec 13 04:14:13 de1 crate[41918]:         at org.elasticsearch.gateway.MetaDataStateFormat.loadLatestState(MetaDataStateFormat.java:298) ~[crate-app.jar:3.3.6]
Dec 13 04:14:13 de1 crate[41918]:         at org.elasticsearch.gateway.MetaStateService.loadGlobalState(MetaStateService.java:111) ~[crate-app.jar:3.3.6]
Dec 13 04:14:13 de1 crate[41918]:         at org.elasticsearch.gateway.MetaStateService.loadFullState(MetaStateService.java:56) ~[crate-app.jar:3.3.6]
Dec 13 04:14:13 de1 crate[41918]:         at org.elasticsearch.gateway.GatewayMetaState.<init>(GatewayMetaState.java:86) ~[crate-app.jar:3.3.6]
Dec 13 04:14:13 de1 crate[41918]:         at org.elasticsearch.node.Node.<init>(Node.java:487) ~[crate-app.jar:3.3.6]
Dec 13 04:14:13 de1 crate[41918]:         at io.crate.node.CrateNode.<init>(CrateNode.java:65) ~[crate-app.jar:3.3.6]
Dec 13 04:14:13 de1 crate[41918]:         at org.elasticsearch.bootstrap.BootstrapProxy$1.<init>(BootstrapProxy.java:193) ~[crate-app.jar:3.3.6]
Dec 13 04:14:13 de1 crate[41918]:         at org.elasticsearch.bootstrap.BootstrapProxy.setup(BootstrapProxy.java:193) ~[crate-app.jar:3.3.6]
Dec 13 04:14:13 de1 crate[41918]:         at org.elasticsearch.bootstrap.BootstrapProxy.init(BootstrapProxy.java:264) ~[crate-app.jar:3.3.6]
Dec 13 04:14:13 de1 crate[41918]:         at io.crate.bootstrap.CrateDB.init(CrateDB.java:155) ~[crate-app.jar:3.3.6]
Dec 13 04:14:13 de1 crate[41918]:         ... 6 more
Dec 13 04:14:13 de1 crate[41918]: Caused by: java.lang.IllegalArgumentException: Unexpected field [cluster_uuid_committed]
Dec 13 04:14:13 de1 crate[41918]:         at org.elasticsearch.cluster.metadata.MetaData$Builder.fromXContent(MetaData.java:1266) ~[crate-app.jar:3.3.6]
Dec 13 04:14:13 de1 crate[41918]:         at org.elasticsearch.cluster.metadata.MetaData$1.fromXContent(MetaData.java:1296) ~[crate-app.jar:3.3.6]
Dec 13 04:14:13 de1 crate[41918]:         at org.elasticsearch.cluster.metadata.MetaData$1.fromXContent(MetaData.java:1287) ~[crate-app.jar:3.3.6]
Dec 13 04:14:13 de1 crate[41918]:         at org.elasticsearch.gateway.MetaDataStateFormat.read(MetaDataStateFormat.java:196) ~[crate-app.jar:3.3.6]
Dec 13 04:14:13 de1 crate[41918]:         at org.elasticsearch.gateway.MetaDataStateFormat.loadLatestState(MetaDataStateFormat.java:294) ~[crate-app.jar:3.3.6]
Dec 13 04:14:13 de1 crate[41918]:         at org.elasticsearch.gateway.MetaStateService.loadGlobalState(MetaStateService.java:111) ~[crate-app.jar:3.3.6]
Dec 13 04:14:13 de1 crate[41918]:         at org.elasticsearch.gateway.MetaStateService.loadFullState(MetaStateService.java:56) ~[crate-app.jar:3.3.6]
Dec 13 04:14:13 de1 crate[41918]:         at org.elasticsearch.gateway.GatewayMetaState.<init>(GatewayMetaState.java:86) ~[crate-app.jar:3.3.6]
Dec 13 04:14:13 de1 crate[41918]:         at org.elasticsearch.node.Node.<init>(Node.java:487) ~[crate-app.jar:3.3.6]
Dec 13 04:14:13 de1 crate[41918]:         at io.crate.node.CrateNode.<init>(CrateNode.java:65) ~[crate-app.jar:3.3.6]
Dec 13 04:14:13 de1 crate[41918]:         at org.elasticsearch.bootstrap.BootstrapProxy$1.<init>(BootstrapProxy.java:193) ~[crate-app.jar:3.3.6]
Dec 13 04:14:13 de1 crate[41918]:         at org.elasticsearch.bootstrap.BootstrapProxy.setup(BootstrapProxy.java:193) ~[crate-app.jar:3.3.6]
Dec 13 04:14:13 de1 crate[41918]:         at org.elasticsearch.bootstrap.BootstrapProxy.init(BootstrapProxy.java:264) ~[crate-app.jar:3.3.6]
Dec 13 04:14:13 de1 crate[41918]:         at io.crate.bootstrap.CrateDB.init(CrateDB.java:155) ~[crate-app.jar:3.3.6]
Dec 13 04:14:13 de1 crate[41918]:         ... 6 more

**Comment by fetzerms** [comment] 2019-12-13 04:04
Update: On the other node I tried to fix the issue with `unsafe-bootstrap` - which resulted in the same (initial) error of `index.write.wait_for_active_shards[2]`.

**Comment by fetzerms** [comment] 2019-12-13 06:49
Update: I manually (hexedited) the indices and changed the value for wait_for_active_shards and adjusted the checksum of the index accordingly. Now my unsafe-bootstrapped node started successfully. The data is now accessible.

**Comment by mfussenegger** [comment] 2020-01-07 22:43
Glad that you were able to resolve the issue.

I wanted to have a closer look to see what we can do that others don't run into this in the first place, but haven't managed to reproduce it. Do you have any more pointers how you ended up running into this?

**Comment by fetzerms** [comment] 2020-01-11 15:24
Its hard to say. I manually set "write.wait_for_active_shards=2" for my tables, but did not do anything special with them otherwise. The tables that had issues were also created with '''number_of_replicas = '0-all''''

**Comment by mfussenegger** [comment] 2020-01-14 10:25
I still wasn't able to reproduce it (creating a table with `number_of_replicas = '0-all'` and `write.wait_for_active_shards = 2` in 3.3.6 and then upgrading to 4.0.10).

I'll close it for now. If anybody runs into this and has more information on how to reproduce it please re-open and add the information.

**Closed by mfussenegger** 2020-01-14 10:25 UTC
