### ISSUE TITLE
Transport response handler not found

### ISSUE THREAD

**Issue by bputt-e** [crate/crate#10306] opened 2020-08-03 20:09 UTC
**CrateDB version**: 4.1.2

**Environment description**:

Centos 7.latest
OpenJDK 11.0.7
Data nodes: 8cpu, 64gb ram
Node makeup: 48 data, 3 master, 2 ingest, 2 query
While we have 48 data nodes, it's essentially over 2 availability zones (24 per zone)

**Problem description**:
Our cluster health will occasionally get stuck in yellow and will require us to restart crate on the affected nodes for the health to go back to green. We typically have a nagios check that runs the alter cluster command which ends up resolving the problem, however, there are cases that require manual intervention.

We typically see shards stay unassigned until we run ```ALTER CLUSTER REROUTE RETRY FAILED```. Some logs from a related issue #9748 

```
shard has exceeded the maximum number of retries [20] on failed allocation attempts - manually execute 'alter cluster....' [unassigned_info[[reason=ALLOCATION_FAILED], at ..... failed to create shard, failure IOException[failed to obtain in-memory shard lock]...


[WARN ][o.e.i.c.IndicesClusterStateService] [hostname][[namespace..partitioned.tablename.someuuid][1]] marking and sending shard failed due to [failed to create shard] java.io.IOException: failed to obtain in-memory shard lock
    at org.elasticsearch.index.IndexService.createShard(IndexService.java:358)
    at org.elasticsearch.indices.IndicesService.createShard(IndicesService.java:440)
    at org.elasticsearch.indices.IndicesService.createShard(IndicesService.java:112)
    at org.elasticsearch.indices.cluster.IndicesClusterStateService.createShard(IndicesClusterStateService.java:551)
...


[INFO ][o.e.i.s.TransportNodesListShardStoreMetaData] [hostname][namespace..partitioned.tablename.someuuid][1]: failed to obtain shard lock
org.elasticsearch.env.ShardLockObtainFailedException: [namespace..partitioned.tablename.someuuid][1]: obtaining shard lock timed out after 5000ms, previous lock details: [shard creation] trying to lock for [read metadata snapshot]
    at org.elasticsearch.env.NodeEnvironment$InternalShardLock.acquire(NodeEnvironment.java:748)
    at org.elasticsearch.NodeEnvironment.shardLock(NodeEnvironment.java:663)
    at org.elasticsearch.index.Store.readMetadataSnapshot(Store.java:443)
....
```

**AFTER running the retry command** we get shards stuck in the ```RELOCATING``` state with the following log message that emits at a very fast rate:

```
[WARN ][o.e.t.TransportService][node]Transport response handler not found of id [9285317]
```

**Comment by seut** [comment] 2020-09-07 13:57
@bputt-e 
Shard lock errors mostly indicate that a node is overloaded and briefly leaves the cluster. In such cases a shard may be removed from that node and then assigned straight back to it again before the node has had a chance to shut the previous shard instance down.

This case could be mitigated by adjusting the `unassigned.node_left.delayed_timeout` table setting, see https://crate.io/docs/crate/reference/en/4.2/sql/statements/create-table.html#unassigned-node-left-delayed-timeout.

We already have some backports in the pipeline to improve the error messages of shard locks to include more details about the root cause, see https://github.com/crate/crate/pull/10493.
We plan to get this into the 4.3 release.

The log entry
```
[WARN ][o.e.t.TransportService][node]Transport response handler not found of id [9285317]
```
indicates that some internal request timed out while a response is received later on. Because the request timed out, no response handler is available anymore. This could also be caused by overloaded nodes.

**Comment by gruselglatz** [comment] 2020-09-09 06:24
Could this issue be repoened, or better documented how to handle it. Because in 4.2.4 it's not resolved. 

Even on a cluster with NO load this starts to happen after 24-72h. with only one Table with 3 partitions, 6 shards, 200 million records.

**Comment by seut** [comment] 2020-09-09 08:49
@gruselglatz Sure I've reopened it, you can do so any time as well.

With the given information it is hard to tell what causes such issues.
From your description you are using multiple zones, can you please verify that this setup is not causing the timeouts by e.g. high network latency or packet drops?
The reallocation of shards could be caused by nodes being unresponsible due to e.g. network issues, high cpu load, high memory pressure (and thus long GC durations), etc.
Log messages about not found response handlers also indicates such issues.

**Comment by bputt-e** [comment] 2020-09-09 20:42
@seut appreciate the info, we'll give ```unassigned.node_left.delayed_timeout``` a try and see if it yields any improvements. One thing to note that as the cluster begins moving shards around, that inherently increases the load across a majority of the data nodes which can cause a widespread impact. Certainly understand that network latency/load need to be taken into account, but I think or issue is currently related to high load due to high IOWAIT

**Comment by gruselglatz** [comment] 2020-09-10 06:19
@seut We only have 3 Nodes no zones or anything. 3 Nodes in the same Nework with these latencies:


When the cluster is relocating or recovering the load gets around 3-6. But no ioWait. Its more CPU bound it seems. Network latency is also good (under 10ms) we also use "write.wait_for_active_shards" = '1'  and  "unassigned.node_left.delayed_timeout" = 60000, on all our tables.

But we constantly get the above mentioned messages.

When we INSERT and SELECT, like a typical usecase, nothing heavy. We get this, and at some point one node is crashing with these messages:
```
[2020-09-10T07:08:21,834][WARN ][o.e.t.TransportService   ] [crate1] Transport response handler not found of id [1241177]
[2020-09-10T07:08:21,837][WARN ][o.e.t.TransportService   ] [crate1] Transport response handler not found of id [1241177]
[2020-09-10T07:08:25,616][ERROR][i.c.p.p.PostgresWireProtocol] [crate1] Uncaught exception:
io.netty.channel.unix.Errors$NativeIoException: readAddress(..) failed: Connection reset by peer
[2020-09-10T07:08:25,616][ERROR][i.c.p.p.PostgresWireProtocol] [crate1] Uncaught exception:
io.netty.channel.unix.Errors$NativeIoException: readAddress(..) failed: Connection reset by peer
[2020-09-10T07:08:25,616][ERROR][i.c.p.p.PostgresWireProtocol] [crate1] Uncaught exception:
io.netty.channel.unix.Errors$NativeIoException: readAddress(..) failed: Connection reset by peer
[2020-09-10T07:08:25,616][ERROR][i.c.p.p.PostgresWireProtocol] [crate1] Uncaught exception:
io.netty.channel.unix.Errors$NativeIoException: readAddress(..) failed: Connection reset by peer
[2020-09-10T07:08:33,308][ERROR][i.c.p.p.PostgresWireProtocol] [crate1] Uncaught exception:
io.netty.channel.unix.Errors$NativeIoException: readAddress(..) failed: Connection reset by peer
[2020-09-10T07:08:33,308][ERROR][i.c.p.p.PostgresWireProtocol] [crate1] Uncaught exception:
io.netty.channel.unix.Errors$NativeIoException: readAddress(..) failed: Connection reset by peer
[2020-09-10T07:08:33,308][ERROR][i.c.p.p.PostgresWireProtocol] [crate1] Uncaught exception:
io.netty.channel.unix.Errors$NativeIoException: readAddress(..) failed: Connection reset by peer
[2020-09-10T07:08:33,308][ERROR][i.c.p.p.PostgresWireProtocol] [crate1] Uncaught exception:
io.netty.channel.unix.Errors$NativeIoException: readAddress(..) failed: Connection reset by peer
[2020-09-10T07:08:33,308][ERROR][i.c.p.p.PostgresWireProtocol] [crate1] Uncaught exception:
io.netty.channel.unix.Errors$NativeIoException: readAddress(..) failed: Connection reset by peer
```

**Comment by seut** [comment] 2020-09-10 07:20
@gruselglatz Thank you for that information.
What client are you using?
Does the node really crash or is it unresponsible? Do you have some more log messages while it crashes?
Do you maybe have insights which queries are running before the node crashes? 
E.g. you could set `stats.jobs_log_persistent_filter` to `true` to log all queries to the regular crate logfile, see https://crate.io/docs/crate/reference/en/4.2/config/cluster.html#stats-jobs-log-persistent-filter (could result in quite big log files).

**Comment by gruselglatz** [comment] 2020-09-10 08:25
@seut 
now I got this log on one node. They didnt even get to restore the shards in the cluster without selects or other load.

```
[2020-09-10T08:38:02,355][WARN ][o.e.t.TransportService   ] [crate3] Transport response handler not found of id [916888]
[2020-09-10T08:38:02,357][WARN ][o.e.t.TransportService   ] [crate3] Transport response handler not found of id [916889]
[2020-09-10T08:38:02,357][WARN ][o.e.t.TransportService   ] [crate3] Transport response handler not found of id [916889]
[2020-09-10T08:38:02,364][WARN ][o.e.t.TransportService   ] [crate3] Transport response handler not found of id [916890]
[2020-09-10T08:38:02,364][WARN ][o.e.t.TransportService   ] [crate3] Transport response handler not found of id [916890]
[2020-09-10T08:38:02,367][WARN ][o.e.t.TransportService   ] [crate3] Transport response handler not found of id [916891]
[2020-09-10T08:38:02,367][WARN ][o.e.t.TransportService   ] [crate3] Transport response handler not found of id [916891]
[2020-09-10T08:38:04,459][WARN ][o.e.t.TransportService   ] [crate3] Transport response handler not found of id [916893]
[2020-09-10T08:38:04,459][WARN ][o.e.t.TransportService   ] [crate3] Transport response handler not found of id [916893]
[2020-09-10T09:19:59,478][WARN ][o.e.t.TransportService   ] [crate3] Transport response handler not found of id [932654]
[2020-09-10T09:19:59,478][WARN ][o.e.t.TransportService   ] [crate3] Transport response handler not found of id [932654]
[2020-09-10T09:21:13,653][WARN ][o.e.t.TransportService   ] [crate3] Transport response handler not found of id [933198]
[2020-09-10T09:21:13,653][WARN ][o.e.t.TransportService   ] [crate3] Transport response handler not found of id [933198]
[2020-09-10T09:23:33,092][WARN ][o.e.t.TransportService   ] [crate3] Transport response handler not found of id [934233]
[2020-09-10T09:23:33,092][WARN ][o.e.t.TransportService   ] [crate3] Transport response handler not found of id [934233]
[2020-09-10T09:26:15,460][WARN ][o.e.m.j.JvmGcMonitorService] [crate3] [gc][86378] overhead, spent [762ms] collecting in the last [1.1s]
[2020-09-10T09:26:16,475][WARN ][o.e.m.j.JvmGcMonitorService] [crate3] [gc][86379] overhead, spent [645ms] collecting in the last [1.2s]
[2020-09-10T09:26:21,117][WARN ][o.e.m.j.JvmGcMonitorService] [crate3] [gc][86381] overhead, spent [3.2s] collecting in the last [3.6s]
[2020-09-10T09:26:23,763][WARN ][o.e.m.j.JvmGcMonitorService] [crate3] [gc][86382] overhead, spent [2.1s] collecting in the last [2.6s]
[2020-09-10T09:26:26,330][WARN ][o.e.m.j.JvmGcMonitorService] [crate3] [gc][86383] overhead, spent [2.2s] collecting in the last [2.5s]
[2020-09-10T09:26:28,308][WARN ][o.e.m.j.JvmGcMonitorService] [crate3] [gc][86384] overhead, spent [1.9s] collecting in the last [1.9s]
[2020-09-10T09:26:30,240][WARN ][o.e.m.j.JvmGcMonitorService] [crate3] [gc][86385] overhead, spent [1.9s] collecting in the last [1.9s]
[2020-09-10T09:26:32,145][WARN ][o.e.m.j.JvmGcMonitorService] [crate3] [gc][86386] overhead, spent [1.8s] collecting in the last [1.9s]
[2020-09-10T09:26:34,026][WARN ][o.e.m.j.JvmGcMonitorService] [crate3] [gc][86387] overhead, spent [1.8s] collecting in the last [1.8s]
[2020-09-10T09:26:35,916][WARN ][o.e.m.j.JvmGcMonitorService] [crate3] [gc][86388] overhead, spent [1.8s] collecting in the last [1.8s]
[2020-09-10T09:26:37,757][WARN ][o.e.m.j.JvmGcMonitorService] [crate3] [gc][86389] overhead, spent [1.8s] collecting in the last [1.8s]
[2020-09-10T09:26:39,615][WARN ][o.e.m.j.JvmGcMonitorService] [crate3] [gc][86390] overhead, spent [1.8s] collecting in the last [1.8s]
[2020-09-10T09:26:43,372][WARN ][o.e.m.j.JvmGcMonitorService] [crate3] [gc][86391] overhead, spent [3.7s] collecting in the last [1.8s]
[2020-09-10T09:29:05,176][WARN ][o.e.m.j.JvmGcMonitorService] [crate3] [gc][86392] overhead, spent [1.5m] collecting in the last [2.3m]
[2020-09-10T09:29:05,176][ERROR][o.e.ExceptionsHelper     ] [crate3] fatal error
        at org.elasticsearch.ExceptionsHelper.lambda$maybeDieOnAnotherThread$2(ExceptionsHelper.java:265)
        at java.base/java.util.Optional.ifPresent(Optional.java:176)
        at org.elasticsearch.ExceptionsHelper.maybeDieOnAnotherThread(ExceptionsHelper.java:255)
        at org.elasticsearch.transport.netty4.Netty4MessageChannelHandler.exceptionCaught(Netty4MessageChannelHandler.java:74)
        at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:302)
        at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:281)
        at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:273)
        at io.netty.handler.logging.LoggingHandler.exceptionCaught(LoggingHandler.java:205)
        at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:302)
        at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:281)
        at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:273)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.exceptionCaught(DefaultChannelPipeline.java:1377)
        at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:302)
        at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:281)
        at io.netty.channel.DefaultChannelPipeline.fireExceptionCaught(DefaultChannelPipeline.java:907)
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.handleReadException(AbstractEpollStreamChannel.java:728)
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:818)
        at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe$1.run(AbstractEpollChannel.java:387)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at java.base/java.lang.Thread.run(Thread.java:832)
[2020-09-10T09:30:09,680][WARN ][o.e.m.j.JvmGcMonitorService] [crate3] [gc][86393] overhead, spent [1m] collecting in the last [1m]
[2020-09-10T09:29:08,963][ERROR][o.e.ExceptionsHelper     ] [crate3] fatal error
        at org.elasticsearch.ExceptionsHelper.lambda$maybeDieOnAnotherThread$2(ExceptionsHelper.java:265)
        at java.base/java.util.Optional.ifPresent(Optional.java:176)
        at org.elasticsearch.ExceptionsHelper.maybeDieOnAnotherThread(ExceptionsHelper.java:255)
        at org.elasticsearch.transport.netty4.Netty4MessageChannelHandler.exceptionCaught(Netty4MessageChannelHandler.java:74)
        at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:302)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:381)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:311)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMess
```

**Comment by seut** [comment] 2020-09-10 09:54
@gruselglatz 
Thank you for that logs.
Did you manage to track down the queries causing this crash?
What CrateDB version and OS are you running?

**Comment by gruselglatz** [comment] 2020-09-10 10:08
@seut Yes, sry. My colleague said it was a Query without LIMIT . Something like Select * FROM Table;

The Table had around 2 Million Records (900 MB)

**Comment by seut** [comment] 2020-09-11 09:01
@gruselglatz Thank you again for that information.

I would expect that another exception is logged below the `fatal error` one. Could you please re-check? 
That exception should give us more information what is causing the crash (I guess its an OOM).

Could you also add which client you are using?

**Comment by gruselglatz** [comment] 2020-09-11 09:40
@seut The log Ends as you see above. It's cutoff. But Crate has written a HeapDump. at the moment it crashed. So it was a OOM Event.

Client: DBeaver 7.0.4

**Comment by seut** [comment] 2020-09-14 08:01
@gruselglatz Thank you for that information, that is indeed very helpful.
Do you mind to send us the whole heap dump (a link to it) to sebastian@crate.io?

**Comment by gruselglatz** [comment] 2020-09-14 10:46
@seut I will get it to you via my colleague @rene-stiams .

**Comment by seut** [comment] 2020-09-17 13:44
I'm closing this issue now as the original issue from @bputt-e was solved and another dedicated issue for the problems @gruselglatz reported was created.
Otherwise feel free to reopen.

**Closed by seut** 2020-09-17 13:44 UTC

**Comment by seut** [comment] 2020-11-23 15:22
We've finally found the issue related to the `Transport handler not found ...` log entries, see https://github.com/crate/crate/pull/10797.
Thank you for reporting, it was indeed an issue.
