### ISSUE TITLE
support group_concat

### ISSUE THREAD

**Issue by cmdares** [crate/crate#8607] opened 2019-04-26 14:04 UTC
query grammar like mysql

SELECT 
pub_id,
GROUP_CONCAT(cate_id),
GROUP_CONCAT(DISTINCT cate_id),
GROUP_CONCAT(cate_id ORDER BY cate_id ASC),
GROUP_CONCAT(cate_id ORDER BY cate_id ASC SEPARATOR ' ')
GROUP_CONCAT(DISTINCT cate_id ORDER BY  cate_id ASC)
GROUP_CONCAT(DISTINCT cate_id ORDER BY cate_id ASC SEPARATOR ' ')
FROM book_mast GROUP BY pub_id ORDER BY GROUP_CONCAT(DISTINCT cate_id) ASC;

ref:
https://www.w3resource.com/mysql/aggregate-functions-and-grouping/aggregate-functions-and-grouping-group_concat.php

**Comment by mfussenegger** [comment] 2019-05-27 13:56
This is a duplicate of https://github.com/crate/crate/issues/7262

**Closed by mfussenegger** 2019-05-27 13:56 UTC
Labels: contributions welcome
