### ISSUE TITLE
COPY FROM fails to work when reading from a fifo

### ISSUE THREAD

**Issue by reversefold** [crate/crate#1935] opened 2015-04-27 01:15 UTC
I'd like to be able to have COPY FROM read from a named pipe (fifo) in order to support using COPY FROM while streaming data onto the server to save on processing and transfer time. When I try to use COPY FROM with a fifo I get an exception that says: "Failed to parse content to map".

**Comment by dobe** [comment] 2015-04-27 06:31
We've never tested to import from a FIFO. Can you please provide the following:

- crate version you used
- your operating system
- information on how you created the FIFO

btw: if you want to achieve highest performance - try to split your file and distribute it across your crate nodes. you might also want to take a look at https://crate.io/docs/en/latest/best_practice/data_import.html

**Comment by mfussenegger** [comment] 2015-05-07 20:54
Just tested this and for me it worked just fine.

Steps I used:

    mkfifo /tmp/testfile
    cat some_testfile.json > /tmp/testfile

and in crash:

    copy t from '/tmp/testfile';

**Comment by mfussenegger** [comment] 2015-10-08 22:09
Closing this as we weren't able to reproduce it and there wasn't anymore feedback. Feel free to reopen if it turns out to still be an issue.

**Closed by mfussenegger** 2015-10-08 22:09 UTC
Labels: feedback_needed
