### ISSUE TITLE
Performance drop while joining multiple columns

### ISSUE THREAD

**Issue by olivertheobald** [crate/crate#6382] opened 2017-10-10 14:02 UTC
**CrateDB version:**
2.1.6 (Docker)

**JVM version:**
1.8.0_131

**OS version / environment description:**
Alpine 3.5 / Docker on Windows host 

**Problem description:**
CrateDB is really slow when joining multiple columns. We have 2 tables. Scheine and Leistungen.
Scheine has about 10 mil. records and Leistungen about 150 mil. Joining a single column takes a few hundred millis, while joining 2 or more columns takes over 1 minute to finish.
There is also a performance drop with smaller data sets, when using more then one column.

**Steps to reproduce:**
```
CREATE TABLE Crate.CScheine(
	ScheinId Long,
	KistenId Long,
	MengenId Long,
       Wohnort String
) WITH (number_of_replicas = '0-2');

CREATE TABLE crate.cleistungen(
	LeistungsId LONG,
	ScheinId LONG,
	KistenId LONG,
	Datum timestamp
) WITH (number_of_replicas = '0-2');

```

**Fast Query:**
```
select * from crate.cscheine as cscheine
inner join crate.cleistungen as cleistungen
on cscheine.kistenid = cleistungen.kistenid
where cscheine.kistenid=201606151300 limit 100;

```

**Slow query:**
```
select * from crate.cscheine as cscheine
inner join crate.cleistungen as cleistungen
on cscheine.kistenid = cleistungen.kistenid
and cscheine.scheinid = cleistungen.scheinid
where cscheine.kistenid=201606151300 limit 100;


```

**Comment by mfussenegger** [comment] 2017-10-10 15:38
Thanks for reporting.

Could you also post the output of the same statements but prefixed with `EXPLAIN` ?

**Comment by olivertheobald** [comment] 2017-10-11 13:22
**Single column join - Fast Query**
![single_column_join](https://user-images.githubusercontent.com/32342110/31442667-683fc23e-ae97-11e7-8115-5a862d04e3b4.PNG)

**2 column join - Slow Query**
![2_column_join](https://user-images.githubusercontent.com/32342110/31442821-e4cbca6e-ae97-11e7-9591-2532f12675e3.PNG)

**Comment by matriv** [comment] 2017-10-25 08:38
@olivertheobald I'm closing this for now, so please reopen once you have some data of your tables so we can reproduce, Thank you!

**Comment by olivertheobald** [comment] 2017-10-25 09:23
@matriv I send you an email with all the details and modified data. I also updated the first post, to match the current schema.

**Comment by matriv** [comment] 2017-10-25 10:02
@olivertheobald Thank you, reopening the issue.

**Comment by matriv** [comment] 2017-10-27 09:28
@olivertheobald 

First of all thanks for providing the data so we could investigate further into the issue.

So the problem has to do with the nature of the data. The query with the join condition on one column is matching much more rows than the query with the join condition on 2 columns.  So, when we join only on 1 column since there are lots of records that match this condition the LIMIT 100 (or 1000 or 10000) is very soon reached. If we add the 2nd column then there are much much fewer records so the NestedLoop (JOIN algorithm implementation) needs to process many more records until even the first 100 limit is full-filled.

If you do instead of `select *` `select count(*)` then the JOIN must process all the records in order to calculate the count(*). If you do that with both queries, you'll see that the amount of time spend until you get a response is more or less the same.

Also if for example you execute:
```
SELECT * FROM 
  (SELECT * FROM crate.cscheine WHERE kistenid=201606151300 LIMIT 1000) AS t1
INNER JOIN
  (SELECT * FROM crate.cleistungen LIMIT 1000) AS t2
ON t1.kistenid = t2.kistenid AND t1.scheinid = t2.scheinid
LIMIT 100000;
```

you will see that there is no matching row after processing 1000x1000 = 100k records.
If you remove the 2nd column from the condition you'll see that already lots of records match.

Since currently our only JOIN implementation is NestedLoops and there is no HashJoin in place, the operation needs to process a big portion of the Cartesian product of these 2 big tables until we fullfill the LIMIT number of records to return as a response.

**Closed by matriv** 2017-10-27 09:28 UTC
Labels: feedback_needed
