### ISSUE TITLE
Cannot group by IP address

### ISSUE THREAD

**Issue by SneakyMax** [crate/crate#6642] opened 2017-12-08 05:54 UTC
**CrateDB version**: 2.2.3

**JVM version**: `Java(TM) SE Runtime Environment (build 1.8.0_144-b01) `

**OS version / environment description**: Ubuntu 16.04

**Problem description**:

`DISTINCT ip_address` and `GROUP BY ip_address` will error with:

```
SQLActionException[SQLParseException: encoded bytes are of incorrect length]
```

**Steps to reproduce**:

- Create table with an `ip` column
- Try to group by it

**Comment by matriv** [comment] 2017-12-11 08:34
Hello @SneakyMax 

Cannot reproduce this issue with both ipv4 & ipv6 addresses.
Could you also provide the data you insert into the table?
Have you inserted the data with normal inserts or by using `copy from`?

**Comment by SneakyMax** [comment] 2017-12-11 18:03
Well that's unfortunate.

It's our main 70-million row table, so it has many many IP addresses. 

They were all inserted with `COPY FROM`. Some of them are `null`. I'll see what I can do about dumping them to check for anything weird.

**Comment by SneakyMax** [comment] 2017-12-12 00:48
@matriv if you have any other ideas on how I can figure out what's going on, without having to dump all 70 million rows, let me know.

**Comment by matriv** [comment] 2017-12-12 09:13
@SneakyMax  
Some more questions:

1.  So you have only ipv4 addresses, or only ipv6, or both?
2. The table data type is `IP` I guess?
3. The json file used for `copy from` had values as strings or as longs?
4. Did you upgrade from a previous Crate version to reach 2.2.3 and the data were already there?

**Comment by matriv** [comment] 2017-12-12 10:10
@SneakyMax Could you also provide the full stacktrace, please?

**Comment by SneakyMax** [comment] 2017-12-21 18:20
1. Only ipv4, yeah
2. Yeah, `"ip_address" IP` per `SHOW CREATE TABLE`
3. Strings
4. Yes, we've updated the cluster several times.
5. @matriv Where might I find the full stack trace? It's not returned in the XHR call in the admin panel, and it's not in the current log file at `/var/log/crate`

**Comment by matriv** [comment] 2017-12-22 11:23
@SneakyMax  You can just switch on the verbose mode in crash with `\verbose` and execute the query. Or from web UI you can execute the query from the console but before check the `Show error trace`.

**Comment by SneakyMax** [comment] 2017-12-26 20:14
Here's the trace:

```
SQLActionException: BAD_REQUEST 4000 SQLParseException: encoded bytes are of incorrect length
	at io.crate.exceptions.SQLExceptions.esToCrateException(SQLExceptions.java:183)
	at io.crate.exceptions.SQLExceptions.createSQLActionException(SQLExceptions.java:124)
	at io.crate.rest.action.RestResultSetReceiver.fail(RestResultSetReceiver.java:117)
	at io.crate.protocols.postgres.RetryOnFailureResultReceiver.fail(RetryOnFailureResultReceiver.java:76)
	at io.crate.action.sql.RowConsumerToResultReceiver.accept(RowConsumerToResultReceiver.java:52)
	at io.crate.executor.transport.executionphases.InterceptingRowConsumer$1.onResponse(InterceptingRowConsumer.java:89)
	at io.crate.executor.transport.executionphases.InterceptingRowConsumer$1.onResponse(InterceptingRowConsumer.java:85)
	at io.crate.executor.MultiActionListener.countdown(MultiActionListener.java:66)
	at io.crate.executor.MultiActionListener.onResponse(MultiActionListener.java:53)
	at org.elasticsearch.action.ActionListenerResponseHandler.handleResponse(ActionListenerResponseHandler.java:46)
	at org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.handleResponse(TransportService.java:1060)
	at org.elasticsearch.transport.TcpTransport$1.doRun(TcpTransport.java:1442)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at org.elasticsearch.common.util.concurrent.EsExecutors$1.execute(EsExecutors.java:110)
	at org.elasticsearch.transport.TcpTransport.handleResponse(TcpTransport.java:1434)
	at org.elasticsearch.transport.TcpTransport.messageReceived(TcpTransport.java:1403)
	at org.elasticsearch.transport.netty4.Netty4MessageChannelHandler.channelRead(Netty4MessageChannelHandler.java:74)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:297)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:413)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1359)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:935)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:134)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:545)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:499)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by matriv** [comment] 2017-12-27 14:36
@SneakyMax I guess this is related to https://github.com/crate/crate/issues/6701
Can you please run your query but exclude nulls? (`WHERE ip_address IS NOT NULL`)

**Comment by SneakyMax** [comment] 2017-12-27 15:47
That works! Guess the issues can be merged

**Comment by matriv** [comment] 2018-01-02 09:46
The fix has been merged and will be available with the next hotfix releases.
Thanks for reporting!

**Closed by matriv** 2018-01-02 09:46 UTC
Labels: feedback_needed
