### ISSUE TITLE
Live Query or Notification Support

### ISSUE THREAD

**Issue by crudbug** [crate/crate#2822] opened 2015-10-30 03:50 UTC
Ability of push query results or any changes to table / row back to any registered clients. 

Similar to : https://www.pipelinedb.com

**Comment by joemoe** [comment] 2015-11-23 13:16
Hi @crudbug, we are putting this on our Backlog, but as this isn't the direction we are heading to, we won't implement this in the near future. Johannes

**Comment by chaudum** [comment] 2015-11-23 14:44
Possible duplicate of https://github.com/crate/crate/issues/1376 ?

**Closed by chaudum** 2015-11-23 14:44 UTC
Labels: enhancement
