### ISSUE TITLE
Allow creating snapshots including a specific schema

### ISSUE THREAD

**Issue by hammerhead** [crate/crate#14017] opened 2023-04-25 13:49 UTC
### Problem Statement

A snapshot should be created for a specific schema. The motivation can be a multi-tenancy scenario with different tenants in each schema. Due to different obligations per tenant pertaining to backups, data retention, etc, it can be desirable to create snapshots including specific schemas.

[CREATE SNAPSHOT](https://crate.io/docs/crate/reference/en/5.3/sql/statements/create-snapshot.html#sql-create-snapshot) supports specifying a table/partition or all tables, but not a schema:
```
{ TABLE ( table_ident [ PARTITION (partition_column = value [ , ... ])] [, ...] ) | ALL }
```

### Possible Solutions

Extend the selection of tables to include a schema name:
```
{ TABLE ( table_ident [ PARTITION (partition_column = value [ , ... ])] [, ...] ) | SCHEMA schema_ident | ALL }
```

**Comment by hlcianfagna** [comment] 2023-05-12 07:09
Duplicate of https://github.com/crate/crate/issues/11292 ?

**Closed** 2023-05-15 07:04 UTC
Labels: feature: backup, complexity: no estimate
