### ISSUE TITLE
Intermittent "Must have an orderByPosition for each symbol" error when running INSERT INTO

### ISSUE THREAD

**Issue by droberts-aptos-com** [crate/crate#10884] opened 2021-01-04 20:33 UTC
**CrateDB version**:
4.1.5

**Environment description**:

Docker version: 19.03.11

Number of nodes: 3

**Problem description**:

We have an intermittent problem where a migration script sometimes craps out with the error below.  This is happening on an INSERT INTO (see steps to reproduce below for the exact statement).  Since this is intermittent, I realize you may not be able to reproduce.  Regardless, I'd be interested in someone's take on what the error "Must have an orderByPosition for each symbol" means.  Thanks.

{ message: 'SQLActionException[SQLParseException: Must have an orderByPosition for each symbol. Got ORDER BY [Ref\{schema.tableName.createdAt::timestamp with time zone, pos=3, nullable=false}
] and outputs: [Ref{schema.tableName._doc[\'id\']::text, pos=6, nullable=true}, Ref{schema.tableName._doc[\'businessDayDate\']::text, pos=1, nullable=false}, Ref{schema.tableName._doc[\'clientDeviceID\']::text, pos=2, nullable=false}, Ref{schema.tableName._doc[\'createdAt\']::timestamp with time zone, pos=3, nullable=false}, Ref{schema.tableName._doc[\'customerEmailAddress\']::text, pos=4, nullable=true}, Ref{schema.tableName._doc[\'deletedAt\']::timestamp with time zone, pos=5, nullable=true}, Literal{Receipt, type=text}, Ref{schema.tableName._doc[\'receiptId\']::text, pos=7, nullable=true}, Ref{schema.tableName._doc[\'receiptTransactionType\']::text, pos=8, nullable=true}, Ref{schema.tableName._doc[\'retailLocationId\']::text, pos=9, nullable=true}, Ref{schema.receipts._doc[\'tenantId\']::text, pos=10, nullable=true}, Ref{schema.tableName._doc[\'transactionId\']::text, pos=11, nullable=true}, Ref{schema.tableName._doc[\'transactionNumber\']::text, pos=12, nullable=false}, Ref{schema.tableName._doc[\'updatedAt\']::timestamp with time zone, pos=13, nullable=false}, Ref{schema.tableName._doc[\'workstationNumber\']::text, pos=14, nullable=false}]]',
code: 4000 }

**Steps to reproduce**:

NOTE - this problem is intermittent.  It happens in our migration scripts that upgrade an environment across multiple versions of our software.

The following two tables need to be created to set up:

CREATE TABLE IF NOT EXISTS schema.tableName (
  "id" STRING,
  "transactionId" STRING NOT NULL,
  "transactionNumber" STRING NOT NULL,
  "tenantId" STRING NOT NULL,
  "retailLocationId" STRING NOT NULL,
  "clientDeviceID" STRING NOT NULL,
  "businessDayDate" STRING NOT NULL,
  "workstationNumber" STRING NOT NULL,
  "receiptTransactionType" STRING NOT NULL,
  "receiptId" STRING,
  "customerEmailAddress" STRING,
  "createdAt" TIMESTAMP NOT NULL,
  "updatedAt" TIMESTAMP NOT NULL,
  "deletedAt" TIMESTAMP,
  PRIMARY KEY ("transactionId", "retailLocationId", "tenantId", "receiptTransactionType")
)

CREATE TABLE IF NOT EXISTS schema.tempTable (
  "id" STRING,
  "transactionId" STRING NOT NULL,
  "transactionNumber" STRING NOT NULL,
  "tenantId" STRING NOT NULL,
  "retailLocationId" STRING NOT NULL,
  "clientDeviceID" STRING NOT NULL,
  "businessDayDate" STRING NOT NULL,
  "workstationNumber" STRING NOT NULL,
  "receiptTransactionType" STRING NOT NULL,
  "receiptCategory" STRING NOT NULL,
  "receiptId" STRING,
  "customerEmailAddress" STRING,
  "createdAt" TIMESTAMP NOT NULL,
  "updatedAt" TIMESTAMP NOT NULL,
  "deletedAt" TIMESTAMP,
  PRIMARY KEY ("transactionId", "retailLocationId", "tenantId", "receiptTransactionType", "receiptCategory")
) WITH (COLUMN_POLICY = 'strict',"mapping.total_fields.limit" = 3000)

The statement below gives the error pasted above:

INSERT INTO schema.tempTable
        ("id","businessDayDate","clientDeviceID","createdAt","customerEmailAddress","deletedAt","receiptCategory","receiptId",
          "receiptTransactionType","retailLocationId","tenantId","transactionId","transactionNumber","updatedAt","workstationNumber") 
        (SELECT "id","businessDayDate","clientDeviceID","createdAt","customerEmailAddress","deletedAt",'Receipt',"receiptId",
        "receiptTransactionType","retailLocationId","tenantId","transactionId","transactionNumber","updatedAt","workstationNumber" 
        FROM schema.tableName order BY  "createdAt"  LIMIT 10000  OFFSET 0)

**Comment by seut** [comment] 2021-01-05 09:51
@droberts-aptos-com 
Thank you a lot for reporting, we can reproduce this issue and can verify that this is a bug when using an ordering on the source table on ``INSERT INTO`` statements.
But I'm wondering why this only happens intermittent, it should always raise an error, are you sure about that?

**Comment by seut** [comment] 2021-01-05 11:16
@droberts-aptos-com We've fixed this issue, it will be released with the next 4.3 hotfix release.
I'm still curious about the intermittent occurrence of this issue on your side.

**Comment by droberts-aptos-com** [comment] 2021-01-05 15:53
@seut you rock thanks.  And yeah, as for the intermittency, I think I was fooled by two things.  First, I was unable to reproduce this in the console, but on closer examination I am running 3.3.5 on my local.  Doh!  So perhaps this bug was introduced in 4.x?  If so that would explain why I couldn't reproduce on my local.

As to why this is happening intermittently in our customer environments, I think it is potentially related to the way we are running it.  We use migrate (https://www.npmjs.com/package/migrate) to run our schema changes in sequence.  On closer examination, the migration that immediately precedes this one that is giving the error adds the same receiptCategory column.

This migration that is blowing up intermittently checks for the existence of the column and does nothing if it is already there.  (I didn't include that check in the repro steps because I didn't think it was relevant.)  And since the column is added by the previous migration, the code I put in the repro steps should theoretically never be running.  So now I am puzzled by why it is ever giving an error.

I'm wondering if this has something to do with eventual consistency.  Is it possible that the first migration runs and adds the column, then the next migration runs immediately after and queries for the column.  In some cases (intermittently), it doesn't see it because of eventual consistency and then tries to add it again, and blows up because of the issue with the ORDER BY that you just fixed.  Thoughts?

Regardless, thanks much for fixing the issue.  I'd be interested in any advice/wisdom you have around eventual consistency and whether it could potentially explain the intermittency of this issue.

**Comment by seut** [comment] 2021-01-08 11:09
@droberts-aptos-com 
> First, I was unable to reproduce this in the console, but on closer examination I am running 3.3.5 on my local. Doh! So perhaps this bug was introduced in 4.x? If so that would explain why I couldn't reproduce on my local.

Yes looks like this issue does not exist on 3.3.x.

> I'm wondering if this has something to do with eventual consistency. Is it possible that the first migration runs and adds the column, then the next migration runs immediately after and queries for the column. In some cases (intermittently), it doesn't see it because of eventual consistency and then tries to add it again, and blows up because of the issue with the ORDER BY that you just fixed. Thoughts?

Meta data changes, like adding a column, are applied atomically inside the cluster state. The eventual consistency aspect of CrateDB only applies to DML operations (insert/update/delete).
But maybe your migration script does not query the tables meta data between each steps? So this then could explain why the next step isn't aware of the newly created column.

As I think this is solved from our side I will close the issue now. But feel free to re-open if you think there is still some issue.
Thank you again for reporting this regression!

**Closed by seut** 2021-01-08 11:10 UTC
Labels: bug
