### ISSUE TITLE
Circuit breaker not tripping when GC can't free memory

### ISSUE THREAD

**Issue by rps-v** [crate/crate#6472] opened 2017-11-02 09:25 UTC
**CrateDB version**:
2.1.6

**JVM version**:
openjdk version "1.8.0_131"
OpenJDK Runtime Environment (build 1.8.0_131-8u131-b11-2ubuntu1.16.04.3-b11)
OpenJDK 64-Bit Server VM (build 25.131-b11, mixed mode)

**OS version / environment description**:
Ubuntu 16.04.2 LTS (GNU/Linux 4.4.0-47-generic x86_64)

**Problem description**:
Node becomes unresponsive do to the heap being filled very fast (from 4gb to 8gb in 15 sec).
See https://github.com/crate/crate/issues/6383#issuecomment-341356565 

```
...
[2017-11-01T11:34:51,925][WARN ][o.e.m.j.JvmGcMonitorService] [s0] [gc][young][151859][9351] duration [1s], collections [1]/[1.4s], total [1s]/[4.6m], memory [3.7gb]->[4.1gb]/[7.9gb], all_pools {[young] [202.8mb]->[2mb]/[532.5mb]}{[survivor] [0b]->[66.5mb]/[66.5mb]}{[old] [3.5gb]->[4gb]/[7.3gb]}
[2017-11-01T11:34:51,925][WARN ][o.e.m.j.JvmGcMonitorService] [s0] [gc][151859] overhead, spent [1s] collecting in the last [1.4s]
[2017-11-01T11:34:52,926][INFO ][o.e.m.j.JvmGcMonitorService] [s0] [gc][151860] overhead, spent [375ms] collecting in the last [1s]
[2017-11-01T11:34:53,926][INFO ][o.e.m.j.JvmGcMonitorService] [s0] [gc][151861] overhead, spent [369ms] collecting in the last [1s]
[2017-11-01T11:34:54,926][INFO ][o.e.m.j.JvmGcMonitorService] [s0] [gc][151862] overhead, spent [416ms] collecting in the last [1s]
[2017-11-01T11:34:55,926][INFO ][o.e.m.j.JvmGcMonitorService] [s0] [gc][151863] overhead, spent [406ms] collecting in the last [1s]
[2017-11-01T11:34:57,035][INFO ][o.e.m.j.JvmGcMonitorService] [s0] [gc][151864] overhead, spent [475ms] collecting in the last [1.1s]
[2017-11-01T11:34:58,158][INFO ][o.e.m.j.JvmGcMonitorService] [s0] [gc][151865] overhead, spent [474ms] collecting in the last [1.1s]
[2017-11-01T11:35:06,245][INFO ][o.e.m.j.JvmGcMonitorService] [s0] [gc][old][151866][47] duration [7.4s], collections [1]/[8s], total [7.4s]/[31.4s], memory [7gb]->[7.3gb]/[7.9gb], all_pools {[young] [10.1mb]->[12.8mb]/[532.5mb]}{[survivor] [66.5mb]->[0b]/[66.5mb]}{[old] [6.9gb]->[7.3gb]/[7.3gb]}
[2017-11-01T11:35:06,245][WARN ][o.e.m.j.JvmGcMonitorService] [s0] [gc][151866] overhead, spent [7.4s] collecting in the last [8s]
...
[2017-11-01T11:39:08,266][INFO ][o.e.m.j.JvmGcMonitorService] [s0] [gc][old][151891][74] duration [7.4s], collections [1]/[7.4s], total [7.4s]/[4.5m], memory [7.9gb]->[7.9gb]/[7.9gb], all_pools {[young] [532.5mb]->[532.5mb]/[532.5mb]}{[survivor] [64.4mb]->[64.1mb]/[66.5mb]}{[old] [7.3gb]->[7.3gb]/[7.3gb]}
[2017-11-01T11:39:08,266][WARN ][o.e.m.j.JvmGcMonitorService] [s0] [gc][151891] overhead, spent [7.4s] collecting in the last [7.4s]
...
```

Full log: [crate.log](https://github.com/crate/crate/files/1437117/crate.log)

**Steps to reproduce**:

**Use case**:

**Feature description**:

**Comment by mfussenegger** [comment] 2017-11-03 14:36
As already mentioned in the other issue, this could be caused by a query going
rogue. This *should* be caught by the circuit breaker, but maybe it's an edge
case that is not handled properly.

Some candidates would be queries with a unusual large limit, GROUP BY or JOIN
queries.
Is there any chance you're able to reproduce this? (preferably not on your
production cluster this time)

Otherwise we'll have a really hard time to track this down.

**Comment by rps-v** [comment] 2017-11-06 08:52
@mfussenegger 

We have a few queries with large LIMITs (set to 100000), maybe those could be the cause. However I could not reproduce this on the dev cluster.

Will keep you updated if it happens again.

**Comment by joemoe** [comment] 2017-12-13 07:54
hi @rps-v, i'm closing this for now. please reopen it when it appears again.

**Closed by joemoe** 2017-12-13 07:54 UTC
Labels: bug, feedback_needed, resilience
